### ISSUE TITLE
/forex/candle OANDA & IC_MARKETS reponse issues

### ISSUE THREAD

**Issue by Dwyte** [finnhubio/Finnhub-API#100]
URL:
`https://finnhub.io/api/v1/forex/candle?token=<token>&count=500symbol=OANDA:GBP_JPY&resolution=D`

RETURNS:
`{
    "c": [
        133.667,
        133.19799999999998
    ],
    "h": [
        133.938,
        134.075
    ],
    "l": [
        132.466,
        132.55599999999998
    ],
    "o": [
        132.522,
        133.662
    ],
    "s": "ok",
    "t": [
        1585774800,
        1585861200
    ],
    "v": [
        120777,
        40285
    ]
}`

This one only returns 2 candle sticks, on other resolutions it works fine tho.

**Comment by Dwyte** [comment]
URL:
`https://finnhub.io/api/v1/forex/candle?token=<token>&count=500symbol=IC MARKETS:7&resolution=240`

RETURNS:
`{"s": "no_data"}`

4h/240 resolution doesn't return any data on ic_markets.

**Comment by Dwyte** [comment]
URL:
`https://finnhub.io/api/v1/forex/candle?token=<token>&count=500&symbol=PEPPERSTONE:7&resolution=240`

RETURNS:
`{"s": "no_data"}`

all resolutions returns none on pepperstone

**Comment by finnhubio** [comment]
Forex broker's connections usually have some downtime during Saturday. Plz try again later.

**Comment by Dwyte** [comment]
Oh right, okie, seems fine now
