### ISSUE TITLE
Gaps in candlesticks?

### ISSUE THREAD

**Issue by quibbleee** [finnhubio/Finnhub-API#103]
If there are missing candlesticks, does that mean there were no trades during that interval? I pulled down something like this (VXX 5m bars for Oct 31, 2019):

https://finnhub.io/api/v1/stock/candle?symbol=VXX&resolution=5&from=1572498000&to=1572584400&token=<token>

I expect to see 78 bars for normal trading hours, but only get back 64. It's missing all the data from 9:30 up until 10:40.

There are other dates with <78 points, like Apr 1-2, 2020. Just wondering if this is intended behavior, and if so, what it means when the data is missing?

**Comment by finnhubio** [comment]
It's not intended behavior and has been fixed. We apologize about the issue.

**Comment by quibbleee** [comment]
Thanks. I found some other dates with missing bars:

Nov 15, 2018
Mar 31, 2015 
Oct 30, 2014 

and 64 others in 2009.
