### ISSUE TITLE
Pattern recognition - Double/Triple bottom wrong timestamps

### ISSUE THREAD

**Issue by danrevah** [finnhubio/Finnhub-API#106]
For example the double bottom for AMD:
https://finnhub.io/api/v1/scan/pattern?symbol=AMD&resolution=D&token=[DROPPED]

returns: 
```json
{
   "aprice":41.04,
   "atime":1582900200,
   "bprice":50.2,
   "btime":1583245800,
   "cprice":36.75,
   "ctime":1584538200,
   "dprice":0,
   "dtime":0,
   "end_price":50.2,
   "end_time":1585920600,
   "entry":50.2,
   "eprice":0,
   "etime":0,
   "mature":0,
   "patternname":"Double Bottom",
   "patterntype":"bullish",
   "sortTime":1585920600,
   "start_price":50.2,
   "start_time":1582641000,
   "status":"incomplete",
   "stoploss":35.405,
   "symbol":"AMD.US",
   "terminal":0
}
```

`start_time` & `end_time` are not marking the right days of the detected double bottom.
Same thing happens with double/triple top & triple bottom.

**Comment by finnhubio** [comment]
Can you provide a screenshot of the pattern after plotting it on the chart ?

**Comment by danrevah** [comment]
<img width="235" alt="Screen Shot 2020-04-07 at 0 38 12" src="https://user-images.githubusercontent.com/7808742/78607653-2c192a00-7868-11ea-9e17-7c983e8d5fae.png">

**Comment by finnhubio** [comment]
plz plot the full start,a,b,c,end  point on the chart.

**Comment by danrevah** [comment]
Alright.. 
I'm drawing an orange line between A and B.
Green line between C and D, and a blue line between start and end.

Anything else that could help?

**Comment by finnhubio** [comment]
Yes it looks like a correct double bottom to me ?

**Comment by danrevah** [comment]
I might not fully understand the chart then, where's exactly that double bottom then?

**Comment by finnhubio** [comment]
Please google "double bottom" pattern. a,b,c are just the points that you should connect to get the pattern on the chart.
