### ISSUE TITLE
Quotes are wrong for ALL tracked symbols

### ISSUE THREAD

**Issue by ruralcoder** [finnhubio/Finnhub-API#107]
Good morning gents. 

I been tracking MSFT, RUBI, TSLA, AMD and SQ and it's all flatlined

For example screenshots from right now show MSFT at 161.16

<img width="661" alt="Screen Shot 2020-04-06 at 8 18 07 AM" src="https://user-images.githubusercontent.com/12993309/78574845-70acb300-77df-11ea-9412-3c3803ad6658.png">

You on the other hand return 153.83
```
https://finnhub.io/api/v1/quote?symbol=MSFT&token=xxx
```

<img width="522" alt="Screen Shot 2020-04-06 at 8 18 21 AM" src="https://user-images.githubusercontent.com/12993309/78574908-85894680-77df-11ea-8500-227e4c8b6809.png">

Please get your shit together....I cannot use your platform any longer. I am losing money!!! 

Farewell and good luck

**Comment by ruralcoder** [comment]
I am seeing data from your websockets 161.255

**Comment by finnhubio** [comment]
Our apology. We messed it up this morning. The issue has been fixed
