### ISSUE TITLE
Only receiving stream data for AAPL an AMZN.

### ISSUE THREAD

**Issue by soffio** [finnhubio/Finnhub-API#109]
```
def on_message(ws, message):
    print(message)


def on_error(ws, error):
    print(error)


def on_close(ws):
    print("### closed ###")


def on_open(ws):
    #ws.send('{"type":"subscribe","symbol":"AAPL"}')
    #ws.send('{"type":"subscribe","symbol":"AMZN"}')
    ws.send('{"type":"subscribe","symbol":"BA"}')
    ws.send('{"type":"subscribe","symbol":"AMD"}')

if __name__ == "__main__":
    websocket.enableTrace(True)
    ws = websocket.WebSocketApp("wss://ws.finnhub.io?token=mytoken",
                                on_message=on_message,
                                on_error=on_error,
                                on_close=on_close)
    ws.on_open = on_open
    ws.run_forever()
```
I'm running the Websocket example, but I can receive message for only AAPL and AMZN.
Now I'm just  receving `{"type":"ping"}` for other symbols. It was worked on Last Friday, but it doesn't work any more today. What am I missing?

**Comment by md-pt** [comment]
same for me - seems like a technical issue on the server side...

**Comment by ruralcoder** [comment]
I am seeing MSFT, but none of the other ones I am tracking.  RUBI, SQ, AMD and TSLA nothing.

All my alerts and projects are FLATLINED.....and the market moved up without me......

**Comment by finnhubio** [comment]
Our apology about the issue. It has been fixed

**Comment by ruralcoder** [comment]
No it has not.
RUBI, SQ, AMD and TSLA still nothing on websockets...

**Comment by ceddybi** [comment]
I am also having the same issue, only getting prices for `AAPL` and `MSFT`, I actually thought it was something wrong with my algos

**Comment by md-pt** [comment]
it was working for a few minutes but now down again :(
