### ISSUE TITLE
There is a problem with the Ultimate plan.

### ISSUE THREAD

**Issue by devlife2016** [finnhubio/Finnhub-API#112]
I am currently using the Ultimate plan.
However, the API Call limit seems to be limited to 60 times per minute.
This is no different from the free plan.

It works fine when you try an API that can only call Ultimate.
There seems to be a problem with the API call policy per minute.

**Comment by finnhubio** [comment]
Hi, for premium support, plz send an email to support@finnhub.io . We will take a look for you. 

My guess is that you are calling some endpoints with high weight which makes you hit the limit but feel free to email us to discuss the issue.

**Comment by devlife2016** [comment]
Thanks, where can I find a manual to know which API weights and how much?

**Comment by devlife2016** [comment]
> Hi, for premium support, plz send an email to [support@finnhub.io](mailto:support@finnhub.io) . We will take a look for you.
> 
> My guess is that you are calling some endpoints with high weight which makes you hit the limit but feel free to email us to discuss the issue.

Thanks, where can I find a manual to know which API weights and how much?

**Comment by devlife2016** [comment]
> Hi, for premium support, plz send an email to [support@finnhub.io](mailto:support@finnhub.io) . We will take a look for you.
> 
> My guess is that you are calling some endpoints with high weight which makes you hit the limit but feel free to email us to discuss the issue.


Has confirmed. Thank you.
