### ISSUE TITLE
Still Down..

### ISSUE THREAD

**Issue by kingdom017** [finnhubio/Finnhub-API#113]
still can't receive data from websocket

**Comment by finnhubio** [comment]
Market is closed right now. Which symbols are you expecting data from ?

**Comment by kingdom017** [comment]
It used to can get data from premarket...

**Comment by finnhubio** [comment]
You can still get it. I just tried it on my end and it's working normally. However there might not be pre-market trading for your symbols. As there is no reproducible example, there is no way to know what is wrong on your end or help you at all.

**Comment by kingdom017** [comment]
Check out https://finnhub.io/api/v1/quote?symbol=TQQQ
the data is out of date, current price is still the previous closed price

**Comment by finnhubio** [comment]
Quote endpoint will return official close price. To get pre/post market hour, plz use the undocumented method https://finnhub.io/api/v1/quote?symbol=TQQQ&trade=true .

**Comment by kingdom017** [comment]
Got it. Thank you very much.
For websoket. I just tried and I find out I can get data for AAPL or TSLA, but can't get data for TQQQ or SQQQ, could you plz check out it? Thank you very very much.
I'm using the python script from API document.
