### ISSUE TITLE
Price target endpoint wrong data returned??

### ISSUE THREAD

**Issue by nick-gaudreau** [finnhubio/Finnhub-API#114]
Until March 28th. Price target end point would pull US market symbols data. Now it returns data from other market around the world. 

Before and until march 28th this would return data for NYSE **$NOK**
https://finnhub.io/api/v1/stock/price-target?symbol=NOK&token=
now it returns **NOKIA.HE** which is not on the same currency. Different price target altogether.

A much worst example is 
https://finnhub.io/api/v1/stock/price-target?symbol=SAN&token=
This used to return US market Banco Santander SA **$SAN** on NYSE but now it returns **$SAN.PA** which is a completely different company based in France, Paris

**Comment by finnhubio** [comment]
I can confirm it's a bug and will be fixed within 24 hours

**Comment by finnhubio** [comment]
Issue has been fixed
