### ISSUE TITLE
News sentiment showing null for some fields

### ISSUE THREAD

**Issue by GarryWalsh** [finnhubio/Finnhub-API#116]
https://finnhub.io/api/v1/news-sentiment?symbol=TOPS&token=TOKEN

Spotchecked a few stocks and seeing null values. 

It's possible this isn't a bug and is a lack of data for these stocks..

`{
    "buzz": {
        "articlesInLastWeek": 0,
        "buzz": null,
        "weeklyAverage": 0
    },
    "companyNewsScore": null,
    "sectorAverageBullishPercent": 0.5641,
    "sectorAverageNewsScore": 0.4807,
    "sentiment": null,
    "symbol": "TOPS"
}`

**Comment by finnhubio** [comment]
this is not a bug
