### ISSUE TITLE
FinnHub.io experiencing intermittent issues?

### ISSUE THREAD

**Issue by Wilsta007** [finnhubio/Finnhub-API#117]
Hi guys ... appears there are intermittent issues with your platform when getting a quotes for AAPL and other stocks. See attached screenshot. Sometimes works, sometimes returns this error. Anything the matter?

![Capture](https://user-images.githubusercontent.com/62986671/78710404-6a4a4280-7969-11ea-8449-10e0661d00ab.JPG)

**Comment by finnhubio** [comment]
issue resolved
