### ISSUE TITLE
Inaccurate Options Data

### ISSUE THREAD

**Issue by VictorSash** [finnhubio/Finnhub-API#119]
I pulled AAPL data for all the expirations.  However, after analyzing the data for all the strikes (and comparing with my brokerage (Schwab)), I find that for the range strike 240 to 280 OI and Volume are not anywhere close to brokerage.  Attached PDF has both brokerage data and finntech supplied data.

Can we explain the anomaly?  I understand small differences but the differences are order of magnitude.  The analytics and metrics go out the window if the data quality is questionable.  

Thanks,

Victor
[Finnhub#1.pdf](https://github.com/finnhubio/Finnhub-API/files/4448028/Finnhub.1.pdf)

**Comment by finnhubio** [comment]
After beta testing this feature, unfortunately we have decided to remove options support. This endpoint has been removed from our documentation.

**Comment by VictorSash** [comment]
That is very disappointing!  I will have to look somewhere else and abandon finnhubio for the time being.  Thanks for your prompt response.

**Comment by dkrutsko** [comment]
@VictorSash Did you ever end up finding a good Options API provider?

**Comment by VictorSash** [comment]
Paid service - yes.  Livevol.com (data.cboe.com)

**Comment by VictorSash** [comment]
I am also told TD Ameritrade provides for its customers (maximum-pain.com
website support told me that).

**Comment by dkrutsko** [comment]
I know Interactive Brokers also has an API for this, but I'll check out your recommendation. Thanks!
