### ISSUE TITLE
Getting rate limits immediately on Free plan

### ISSUE THREAD

**Issue by omlid** [finnhubio/Finnhub-API#122]
Error:
`requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://finnhub.io/api/v1/quote?symbol=SPY&api_key=XXXXXXXX`

Text response says:
`API limit reached. Please sign up for a free account to continue using the API.`

But I have a free account and even have a CC attached.

Sent a few requests with a key of "random" for you to track down in the logs. Here's one of them:
`https://finnhub.io/api/v1/quote?symbol=SPY&api_key=XXXXXXX&random=0.32623933596864907`

I'm pretty sure I didn't call the API > 60 times in a minute by the way. 

Thanks for the service and support. Looking forward to upgrading after trying it out.

**Comment by finnhubio** [comment]
You need to create an account to get 60 API calls/minute. Giving random api key will not work.

**Comment by omlid** [comment]
I do have an account and free plan. I also have regen'd the key in the dashboard.

**Comment by finnhubio** [comment]
You only receive this text "API limit reached. Please sign up for a free account to continue using the API." if your token field is empty.

**Comment by cnickeson** [comment]
I figured out what this issue is. This happened for me when I tried to auth with using the x-finnhub-secret header. I instead passed the token in via a query param as token={key} and that solved it for me.

**Comment by ranisalt** [comment]
I am getting 429 immediately in all requests, always, with a brand new API key and I am sure I haven't used this in ages
