### ISSUE TITLE
Wrong Data of the day. Thursday issue.

### ISSUE THREAD

**Issue by yvesn7** [finnhubio/Finnhub-API#124]
Pre-market (trade=true) data is wrong. 

Example:
https://finnhub.io/api/v1/quote?symbol=MSFT&trade=true&token=xxxxxxxxxxxxxxx
{"c":165.73,"h":166.67,"l":163.5,"o":165.67,"pc":163.49,"t":1586437563}

"c" is stuck at 165.73. Wrong value. Correct value is 166.97 at this exact moment.

**Comment by finnhubio** [comment]
Sorry we can't really comment on this as it will take too much time to track every tick to confirm your statement. The margin is not big enough for us to investigate further.

**Comment by yvesn7** [comment]
This is a scary answer for several reasons. 

First reason is that obviously you guys by default do not trust your customers to report issues worthy of your attention. I start tracking pre-market about 30 minutes before opening, and every position I track was "stuck" on a random value, for that entire 30 minutes. I gave you one example to underline what was happening, but that doesn't mean it was a single tick. They were ALL wrong, the entire data set was wrong pre-market, and only corrected itself when the market opened. . How many examples do I need to provide for you to look into things next time? 

Second reason, that example is a difference of $1.24 in a stock price and you're saying that margin is not big enough for you to worry about? Really?

Third reason, maybe the most alarming, this was a generalized issue with your data (not a single tick was right), and it is clear from your answer that you had no idea it was happening and you won't even look. That makes me realize you have no process in place to monitor the integrity of your data and get alerted when things go wrong. That is truly scary. 

I will monitor pre-market again today and let you know if it is happening again.

**Comment by ruizrica** [comment]
"The margin is not big enough for us to investigate further"  What I took, they don't care.

**Comment by jmartin12** [comment]
Agreed. This is cringe worthy from finnhub. Definitely avoiding ever using them as a provider.
