### ISSUE TITLE
Rate limits much lower than advertised on Basic Plan

### ISSUE THREAD

**Issue by i2020github** [finnhubio/Finnhub-API#125]
I paid for the Basic Plan but I can only make 10 queries via the API and then it has to wait 50 seconds for the next batch of API calls. This was advertised as having a limit of 150 API calls/minute. Is there something I'm doing wrong? Thank you for any guidance.

**Comment by finnhubio** [comment]
Which endpoint did you call ? Have you checked the Weight ?

**Comment by i2020github** [comment]
For example (I have removed my API key):

> 
> 2020-04-10 05:26:11  1607 API returned invalid data  Array
> (
>     [call] => https://finnhub.io/api/v1/stock/profile?symbol=FBRT.L&token=KEY
>     [res] => API limit reached. Please try again later.
> )
> 
> 2020-04-10 05:27:11  1608 Trying again after 60 seconds
> 2020-04-10 05:27:11  1609 - FBRT.L has no profile, skipping stock
> 2020-04-10 05:27:12  1610 - FBT.L has no profile, skipping stock
> 2020-04-10 05:27:13  1611 + Saved FCAP.L to file
> 2020-04-10 05:27:14  1612 + Saved FCCN.L to file
> 2020-04-10 05:27:15  1613 + Saved FCH.L to file
> 2020-04-10 05:27:16  1614 - FCI.L has no profile, skipping stock
> 2020-04-10 05:27:16  1615 - FCIF.L has no profile, skipping stock
> 2020-04-10 05:27:17  1616 + Saved FCIT.L to file
> 2020-04-10 05:27:18  1617 - FCPT.L has no profile, skipping stock
> 2020-04-10 05:27:19  1618 - FCR.L has no profile, skipping stock
> 2020-04-10 05:27:20  1619 - FCRE.L has no profile, skipping stock
> 2020-04-10 05:27:21  1620 API returned invalid data  Array
> (
>     [call] => https://finnhub.io/api/v1/stock/profile?symbol=FCRM.L&token=KEY
>     [res] => API limit reached. Please try again later.
> )

**Comment by finnhubio** [comment]
Hi, plz check the Weight here: https://finnhub.io/docs/api#weight and on your endpoint's documentation.
