### ISSUE TITLE
What's the resolution of data from NASDAQ OMX NORDIC(ST)

### ISSUE THREAD

**Issue by triptec** [finnhubio/Finnhub-API#127]
Hi!
Before paying for the basic plan I'd like to know the resolutions of the intraday candles of NASDAQ OMX NORDIC(ST), because with the free account I just get {"s":"no_data"}, no sure if it's because there is no data or just me not having access.

Thank you!

**Comment by finnhubio** [comment]
Can you send a sample link ? Which symbol are you trying to access ?

**Comment by triptec** [comment]
April 1 to April 10, 1 min for example:
https://finnhub.io/api/v1/stock/candle?symbol=VOLV-B.ST&resolution=1&from=1585699200&to=1586476800&token=myKey

**Comment by finnhubio** [comment]
We just don't have data your time range. Try this and you will get some recent data: https://finnhub.io/api/v1/stock/candle?symbol=VOLV-B.ST&resolution=1&count=5000&token=

**Comment by triptec** [comment]
Hmm, the first datapoint has a timestamp saying april 7, thats between the my from and to..

**Comment by finnhubio** [comment]
> Hmm, the first datapoint has a timestamp saying april 7, thats between the my from and to..

My apology. You should request only 3-4 days of 1 minute data at a time to get the data instead.
