### ISSUE TITLE
Empty data for PPD symbol

### ISSUE THREAD

**Issue by alexkhomyakov** [finnhubio/Finnhub-API#128]
When I make a GET request to https://finnhub.io/api/v1/stock/profile?symbol=PPD I get an empty response, but PPD ticker is listed as supported at https://finnhub.io/api/v1/stock/symbol?exchange=US

**Comment by finnhubio** [comment]
Hi, it means we simply don't have data for that symbol at the moment. We will look into it and try to support it in the future if possible. Thanks for reporting.

**Comment by alexkhomyakov** [comment]
Are there many symbols like this? What worries me is that it's listed in the list as supported symbol here https://finnhub.io/api/v1/stock/symbol?exchange=US

**Comment by finnhubio** [comment]
Unfortunately, we do not have all data for all supported symbols. For example you can still get market data for PPD: https://finnhub.io/api/v1/quote?symbol=PPD&token=
