### ISSUE TITLE
Gaps in intraday minute resolution candlestick data

### ISSUE THREAD

**Issue by RasmusOrsoe** [finnhubio/Finnhub-API#129]
Hi! 
While testing out the free API to figure out if the data provided here could be used for my project, I noticed that when I do pulls like this:
r = requests.get('https://finnhub.io/api/v1/stock/candle?&symbol=AAPL&resolution=1&from=1570060800&to=1580515200&token=myKey)
I find that quite frequently between those to UNIX-timestamps in the request above, the data is not exactly one minute apart. I.e, while sorting data after date, timestamps fall as 14:30,14:32,14:38 etc. 

I checked a number of symbols and this seems to be an issue with not just APPL.

My question is:
Out of the 50.000 data points from the above request, there's about 4500 cases of gaps. Is this intended? If so - why is this the case? Am I doing something wrong?

Thanks.

**Comment by RasmusOrsoe** [comment]
I have reproduced this behavior for 5 min, 30 min, hourly and daily resolution as well for the above symbol. Surely these gaps cannot be because of 0 trade volume?

**Comment by finnhubio** [comment]
Hi,

Can you point out a few consecutive timestamps where you think having a gap is not correct ?

Thanks.

**Comment by RasmusOrsoe** [comment]
Well I guess my question is two fold. First, consider the marked dates in the picture below.
![ex](https://user-images.githubusercontent.com/48880272/79050855-1f605180-7c2d-11ea-8871-9a204d883d8b.png)
On the left side we have the 5 minute resolution request from the timeperiod mentioned earlier. On the right hand side we have the minute resolution of same period. Both are the same symbol. As you can see, the 5-min data says that at 8:10 ( I assume between 8:05:01 and 8:10:00) a volume of 2241 APPL stocks were traded. However, in the minute data we only see 10 stocks sold at 8:05. So how is this supposed to be understood?

1) Does a timestamp of let's say 08:05 mean litterally all the stocks sold at 8:05, or does it represent all stocks sold between 08:00  and 08:05, including 08:05 for 5-minute data?

2) If there are timestamp gaps between data in the one-minute data, does this mean that no stocks were traded between the two timestamps? Take the two marked values on the right hand side as an example of this. 

Thanks

**Comment by finnhubio** [comment]
1. 8:10 means the period from 8:10 to 8:15 (NOT 8:05 to 8:10) so the data is consistent across timeframes.

2. If there is a gap, it usually means there is no trades in that period. That's why I needed to ask you to point out a few gaps where you think trades should have happened so we can check them.

Hope it helps.
