### ISSUE TITLE
from:to returns no_data

### ISSUE THREAD

**Issue by foo-fc** [finnhubio/Finnhub-API#133]
I am trying to get data for the S&P500 index using:
https://finnhub.io/api/v1/stock/candle?symbol=^GSPC&resolution=1&from=1585526400&to=1586466900&token=
This gives me {'s': 'no_data'}.

However, I split it up into this:
https://finnhub.io/api/v1/stock/candle?symbol=^GSPC&resolution=1&from=1585526400&to=1585872000&token=
and
https://finnhub.io/api/v1/stock/candle?symbol=^GSPC&resolution=1&from=1586131200&to=1586466900&token=

Both statements here work. 

Do you know why I need to exclude the weekend from my data grab? Will switching to a paid version give me access to the pre-market?

**Comment by finnhubio** [comment]
Please limit the from and to range to 3-5 days at a time for 1min timeframe to get the data.
