### ISSUE TITLE
Unix time stamp for quotes refers to moment of request

### ISSUE THREAD

**Issue by scousie** [finnhubio/Finnhub-API#135]
Hello,

I'm new to Finnhub and API's at all, but when I receive quotes for symbols like AAPL or ENGI.PA the timestamp refers to the moment of request and not the moment of the quote.
So even when I sent a request in the weekend I get a timestamp in the weekend.
Is this intended to be? If it is, is there a possibility to get the real quote date and time?

For example : quote request on AAPL
{"c":267.99,"h":270.07,"l":264.7,"o":268.7,"pc":266.07,"t":1586611898}

**Comment by finnhubio** [comment]
Please ignore the "t" field at the moment. We are using it to verify data integrity internally only.

**Comment by nycweb** [comment]
It looks like starting on 4/7/2020 the "t" return when requesting minute quotes on SPY is correct and accounting for GMT.  However starting 4/6/2020 and prior the offset is wrong.  9:30am EST open candle on SPY on 4/6/2020 is the price at 1:30pm EST.  This data is corrupt.
