### ISSUE TITLE
Problem WebSocket in java

### ISSUE THREAD

**Issue by denis-laurichesse** [finnhubio/Finnhub-API#136]
I am using some java code to get quotes using the websocket feature.
Unfortunately I have the following exception during the connection:
javax.websocket.DeploymentException: Handshake error

**Comment by finnhubio** [comment]
Sorry we do not program in java so can't help you hear. However I can confirm that the web socket is working normally. Please double check your code or post it here and ask for community's helps.

**Comment by obvi-alias3** [comment]
I'm also having websocket handshake problems, but in Python 2.7.  They started out of the blue while my app was running.  Timestamps are NYC/Eastern time:

2020-04-11 19:18:49 websocket error
2020-04-11 19:18:56 websocket error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:726)

Everything was fine, my app got disconnected, then when it reconnected after backing off a few seconds, it was all handshake failures.  No hot code reloading; nothing changed on my platform.

I did some poking around on with:

openssl s_client -connect ws.finnhub.io:443

python -c "import json, urllib2; print json.load(urllib2.urlopen('https://www.howsmyssl.com/a/check'))['tls_version']"

and my best guess is the endpoint was upgraded Saturday night to be super strict about what SSL protocols it'll allow to connect, perhaps only TLSv1.3, which seems to not have universal support having only been defined August 2018.  Perhaps relax it to allow TLS 1.0 connections again?

**Comment by obvi-alias3** [comment]
I wrote a brief Python 3.5 version (basically the demo program) and it also won't connect
```
$ cat demo.py
import websocket

def on_message(ws, message):
    print('on_messsage', message)

def on_error(ws, error):
    print('on_error', error)

def on_open(ws):
    print('on_open')

def on_close(ws):
    print('on_close')

if __name__ == '__main__':
    websocket.enableTrace(True)
    TOKEN = 'secret'
    url = "wss://ws.finnhub.io?token=" + TOKEN
    ws = websocket.WebSocketApp(url,
                              on_message = on_message,
                              on_error = on_error,
                              on_close = on_close)
    ws.on_open = on_open
    ws.run_forever()

$ python3 demo.py
on_error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:726)
on_close
$ python3 -c "import json, urllib.request; print(json.loads(urllib.request.urlopen('https://www.howsmyssl.com/a/check').read().decode('UTF-8'))['tls_version'])"
TLS 1.2
```

**Comment by finnhubio** [comment]
Hi sorry for the late reply. yes we have relaxed the TLS version to 1.0 now. You can try to connect again.

**Comment by obvi-alias3** [comment]
Still not working, but I'll try again in an hour or two because propagation can take time.

If it's helpful, I had been connected as of _at least_ 2020-04-11 18:02:38 before I saw a disconnect and first handshake failure upon reconnect.

**Comment by finnhubio** [comment]
Yes we upgraded the websocket endpoint over the weekend to avoid a DDOS attack which has been going on since the beginning of last week.

**Comment by obvi-alias3** [comment]
No luck yet.  Is that demo working for you?  What's your python environment?  I'm at the limit of my SSL knowledge, but could it be someone forget to install a certificate on the upgraded endpoint?

```
$ host ws.finnhub.io
ws.finnhub.io has address 104.24.126.31
ws.finnhub.io has address 104.24.127.31
$ openssl s_client -connect ws.finnhub.io:443
CONNECTED(00000003)
139978326797056:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:769:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 305 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1586835223
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by finnhubio** [comment]
It's working fine on our end and for a lot of other users as I can see their connections right now. Can you save the following code into an html file ? Place your token into the URL then open it with chrome. Then open the chrome's console and check whether the message comes through.

`<!DOCTYPE html>
  <head>
  <meta charset="utf-8" />

  <title>WebSocket Test</title>
  <script type="text/javascript">
const socket = new WebSocket('wss://ws.finnhub.io?token=<REPLACE_TOKEN_HERE>');

// Connection opened
socket.addEventListener('open', function (event) {
    socket.send(JSON.stringify({'type':'subscribe', 'symbol': 'BINANCE:BTCUSDT'}))
    socket.send(JSON.stringify({'type':'subscribe', 'symbol': 'firehose_us'}))
    socket.send(JSON.stringify({'type':'subscribe', 'symbol': 'BITMEX:XBTUSD'}))
    socket.send(JSON.stringify({'type':'subscribe', 'symbol': 'IC MARKETS:1'}))

});

socket.addEventListener('message', function (event) {
    console.log('Message from server ', event.data);
});

	socket.onclose = function (event) {
            console.log(event)
        }

var unsubscribe = function(symbol) {
	socket.send(JSON.stringify({'type':'unsubscribe','symbol': symbol}))
}
  </script>
</head>
<body>
</body>`

**Comment by obvi-alias3** [comment]
That works, Firefox and Chrome.

I can't explain why Python doesn't work for me anymore with finnhub other than incompatible changes on the server side.  My python environment still works fine with the tiingo websockets.

**Comment by finnhubio** [comment]
> That works, Firefox and Chrome.
> 
> I can't explain why Python doesn't work for me anymore with finnhub other than incompatible changes on the server side. My python environment still works fine with the tiingo websockets.

Maybe try reinstall ssl for python. I just tested with our python sample code. It's working fine.

**Comment by obvi-alias3** [comment]
SOLVED - my problem anyway.  The solution is updating all the way to python3.8 && python3.8 -m pip install websocket_client; then the basic demo works again.

I think Python 3.5, 2.7, OpenSSL 1.0.2g, and OP's unknown Java version don't correctly navigate the CloudFlare to finnhub ssl handoff/websocket upgrade.  Open SSL 1.1.1d works.

I don't remember seeing `HTTP/1.1 101 Switching Protocols` chatter from websocket.enableTrace(True) before this weekend, older libraries might be getting jammed up with that?

**Comment by obvi-alias3** [comment]
FYI while deploying from development to test I've further isolated that either/both:
urllib3 1.13.1 bad 1.25.8 works
websocket-client 0.18.0 bad 0.57.0 works
