### ISSUE TITLE
Websocket limit

### ISSUE THREAD

**Issue by hypo-thesis** [finnhubio/Finnhub-API#137]
I am given to understand that 60 api calls a min can be made. 

1. Is it the same for websocket queries too ?
2. How to limit websocket queries to that many a minute ?

**Comment by finnhubio** [comment]
what do you mean by "websocket queries" ?

**Comment by hypo-thesis** [comment]
`const socket = new WebSocket('wss://ws.finnhub.io?token=mytoken');` has started my websocket. I am receiving many multiples query from `socket.addEventListener('message', function (event)` The responses seem to be way beyond 60 a minute.

**Comment by finnhubio** [comment]
Ah I see. we do not limit the number of messages you receive through websocket so don't worry about it.

**Comment by hypo-thesis** [comment]
Websocket is idle when there is no price change so at the point of making the connection it may receive no data for a while. Is there any way I can get the last price regardless of the changes through your API ?

**Comment by finnhubio** [comment]
You can checkout the Quote endpoint for that: https://finnhub.io/docs/api#quote
