### ISSUE TITLE
Wrong data in candles endpoint

### ISSUE THREAD

**Issue by jhassony** [finnhubio/Finnhub-API#138]
When I use the candles endpoint with from/to that are a superset of trading day hours (e.g. 5:30 AM to 5:30 AM next day), I get alot of irrelevant data points.
For example, for the following call:
https://finnhub.io/api/v1/stock/candle?symbol=AAPL&resolution=1&from=1586424638&to=1586511038&token=

I would expect to have 390 data points (1 min data point * 60 in hour * 6.5 hours in trading day). However, I get 800 data points for this request. They all include some data, however the data is wrong since no trading was done in most of these hours

**Comment by finnhubio** [comment]
Did you take into account pre/post market hours trading ?

**Comment by jhassony** [comment]
No, I didn't. However, even if looking at the normal trading hours, the data is wrong.
According to Yahoo finance, opening minute (9th April 2020 9:30 AM) has 1.68M volume, but the data received is 772952. The next minute also has wrong volume, and so on. I couldn't find one minute of data with the correct value of volume and ohlc values.

**Comment by finnhubio** [comment]
> No, I didn't. However, even if looking at the normal trading hours, the data is wrong.
> According to Yahoo finance, opening minute (9th April 2020 9:30 AM) has 1.68M volume, but the data received is 772952. The next minute also has wrong volume, and so on. I couldn't find one minute of data with the correct value of volume and ohlc values.

There are 13 exchanges in the US. Yahoo finance only gives you volume for 1 of them because it's free. You can not compare sources like that if you don't know exactly which exchanges are included.

**Comment by finnhubio** [comment]
> No, I didn't. However, even if looking at the normal trading hours, the data is wrong.
> According to Yahoo finance, opening minute (9th April 2020 9:30 AM) has 1.68M volume, but the data received is 772952. The next minute also has wrong volume, and so on. I couldn't find one minute of data with the correct value of volume and ohlc values.

There are 13 exchanges in the US and we do not know which exchanges and/or dark pools Yahoo finance include in their data so we can not comment on this issue unfortunately.

**Comment by jhassony** [comment]
My understanding is it is listed from NASDAQ. Don't you support NASDAQ & NYSE?

**Comment by finnhubio** [comment]
> My understanding is it is listed from NASDAQ. Don't you support NASDAQ & NYSE?

1 stock can be listed on 1 primary exchanges and be traded on all 13 exchanges. That's the case with most of US stocks.
