### ISSUE TITLE
News Sentiment Argument typo `:symbol` should be `symbol`

### ISSUE THREAD

**Issue by llonchj** [finnhubio/Finnhub-API#139]
## What is the issue ? 

News Sentiment documentation has a typo in the symbol argument.

## How to reproduce the error ?

Browsing to Arguments section in https://finnhub.io/docs/api#news-sentiment reads `:symbol` argument

## What is the expected result and why do you think it's the correct result ?

Should read `symbol`

**Comment by finnhubio** [comment]
Thank you for reporting. We will fix it asap

**Comment by llonchj** [comment]
Thank you! I am trying to generate the api programmatically from docSchema json and this one makes it break
