### ISSUE TITLE
Tick Data only returns the last 6 hours

### ISSUE THREAD

**Issue by knoxgon** [finnhubio/Finnhub-API#14]
The stock tick data only returns the last 6 hours of the selected date interval. Is there any way to get last 12 months respective 5 years stock price movement?

**Comment by finnhubio** [comment]
We limit the number of ticks return at a time. You need to do it iteratively based on the data returned to get all the data you need. The data is just too big to return everything in 1 API call.

**Comment by FreeGoldRush** [comment]
Please describe the API calls to receive partial data iteratively as you recommend.  The API documentation only allows for specifying a symbol and a date.  How do you specify a time window?
