### ISSUE TITLE
NULL return on /forex/candle

### ISSUE THREAD

**Issue by Dwyte** [finnhubio/Finnhub-API#141]
`/forex/candle?...` returns `null`, no status even.

`https://finnhub.io/api/v1/forex/candle?token=<token>&count=500&resolution=5&symbol=IC MARKETS:7`

Tested on GBP/JPY trading pair, for all exchanges returns **null** except for **OANDA** and **FOREX.COM**. **IC MARKETS:7**, **PEPPERSTONE:7**, etc.

Expecting OHLCV results, this was working fine last week.

**Comment by finnhubio** [comment]
Plz try again. should work now.
