### ISSUE TITLE
Wrong timestamps with M resolution (Stock Candles)

### ISSUE THREAD

**Issue by dolnikov** [finnhubio/Finnhub-API#144]
Hello
When I try to get candles with M resolution
I get the wrong dates

What I mean:
I have request:
api/v1/stock/candle?from=1554076800&to=1585180800&symbol=BA&resolution=M

Response timestamp:
"t": [
        1554076800,
        1556668800,
        1559260800,
        1561852800,
        1564444800,
        1567036800,
        1569628800,
        1572220800,
        1574812800,
        1577404800,
        1579996800,
        1582588800
    ],
------------

1554076800 = 1 april  2019
1556668800 = 1 may 2019
1559260800 = 31 may  2019
1561852800 = 30 june   2019
1564444800 = 30 july  2019
1567036800 = 29 august 2019
1569628800 = 28 september 2019
1572220800 = 28 october 2019
1574812800 = 27 november 2019
1577404800 = 27 december 2019
1579996800 = 26 january 2019
1582588800 = 25 february 2019
1585180800 = 26 march 2019

We can see the dates have shifted
This problem is only with M resolution

What i want to see:
1 april  2019
1 may 2019
1 june   2019
1 july  2019
1 august 2019
1 september 2019
1 october 2019
1 november 2019
1 december 2019
1 january 2019
1 february 2019
1 march 2019

Why does it work like this?

**Comment by finnhubio** [comment]
We are doing 30-day rolling period of US stock data at the moment.
