### ISSUE TITLE
Pip install not working

### ISSUE THREAD

**Issue by thatsis** [finnhubio/Finnhub-API#145]
The pip install order is returning the following:

ERROR: Could not find a version that satisfies the requirement finnhub (from versions: none)
ERROR: No matching distribution found for finnhub

Is it working for you?

**Comment by eljave** [comment]
No, unfortunately I have the same problem

**Comment by Ron756** [comment]
The pip install order is returning the following:
ERROR: Could not find a version that satisfies the requirement finnhub (from versions: none)
ERROR: No matching distribution found for finnhub

**Comment by finnhubio** [comment]
Plz use requests at the moment. The author of that library has decided to stop support the library. We will be making our official python library soon.

**Comment by paduel** [comment]
@thatsis  you can find a new Finnhub API client library with python that directly returns Pandas dataframes here:

https://github.com/paduel/fhub

Disclaimer, I am the developer ;D
