### ISSUE TITLE
Password reset doesn't work / fails with non-visible captcha

### ISSUE THREAD

**Issue by mruegenberg** [finnhubio/Finnhub-API#146]
Hello,
resetting passwords doesn't work for me,in 2 different browsers (Firefox & Chrome).
After receiving the password reset link and entering my new password, I get a message saying that the captcha failed, even though there is no actual captcha to be seen.

**Comment by finnhubio** [comment]
Sorry for the issue. If you still have trouble login, plz email us at support@finnhub.io . We will reset the pwd for you.

**Comment by mruegenberg** [comment]
No worries, I'm able to log in, but wanted to change my password.

**Comment by finnhubio** [comment]
We will look into the captcha issue asap.

**Comment by finnhubio** [comment]
The issue has been fixed. Plz try again.

**Comment by mruegenberg** [comment]
So now the form does send (though enter key doesn't work - I have to click the button), but it doesn't actually reset the password. When sending the form with a new password, I get logged in, but when I log out after that, only my old pw works on re-login...
