### ISSUE TITLE
Missing data for some stocks and delay in quotes

### ISSUE THREAD

**Issue by seedlit** [finnhubio/Finnhub-API#148]
Hi.
I noticed that data for some stock symbols are missing. Particularly, I know at least of these two:
SBICARD.NS
BORORENEW.NS
Both are listed on the National Stock Exchange (India).

Also, is there any delay in fetching quotes? I am facing a delay of around 2-3 minutes in getting quotes.

Thank you.

@finnhubio ?

**Comment by finnhubio** [comment]
Sr for the late reply. We added those 2 symbols. Should be able to query them next week
