### ISSUE TITLE
What is the source of your data?

### ISSUE THREAD

**Issue by boxbinary** [finnhubio/Finnhub-API#15]
I am researching gaps in aggregate data and notice that gaps in your aggregate data match with another provider (even though the gaps are erroneous, since trades were performed at those times). Are you receiving trades (and generating your own aggregates) direct from a SIP or from another data vendor?

**Comment by finnhubio** [comment]
Questions like this without a way to reproduce the error doesn't help us in assisting you at all. Plz follow the guideline before posting a question on community support forum. 

Also, we can not answer questions regarding data of other vendors so plz be considerate before posting questions here. Feel free to open a new issue with a reproducible example if you still need help.
