### ISSUE TITLE
websocket stop working with forex

### ISSUE THREAD

**Issue by gchumbes** [finnhubio/Finnhub-API#150]
hi suddenly websocket stop receiving information and in case receive any this is delayed.

work with forex only

**Comment by alphasignal** [comment]
Same here...crypto feed just stopped...nothing.

**Comment by bobo-ponsonbee** [comment]
Send on Websocket with {"type": "subscribe", "symbol": "AAPL"} returns {"type": "ping"}.
This worked correctly a few days ago, my code hasn't changed. 
Maybe linked to above two comments.

Is the service down?

**Comment by finnhubio** [comment]
> Send on Websocket with {"type": "subscribe", "symbol": "AAPL"} returns {"type": "ping"}.
> This worked correctly a few days ago, my code hasn't changed.
> Maybe linked to above two comments.
> 
> Is the service down?

You subscribed when the market is closed
