### ISSUE TITLE
websocket not working

### ISSUE THREAD

**Issue by llonchj** [finnhubio/Finnhub-API#154]
## What is the issue ? 

Since 4am America/New_York, websocket is not showing (premarket) data for: `{"symbols": ["UAL", "TXN", "TSLA", "T", "PM", "NFLX", "LUV", "LMT", "KO", "INTC", "IBM", "GOOGL", "DAL", "CTXS", "CMG", "AXP", "AMZN", "AAL"]}`

I can see in websites like investing.com or tradingview.com premarket data.

websocket only returns `ping` messages

## How to reproduce the error ?

subscribe to any of the symbols above

## What is the expected result and why do you think it's the correct result ?

i will expect receiving `trade` messages from the websocket

**Comment by ttrasn** [comment]
I have same issue today. some times there is no data for any symbol. even cryptos !

Where is problem and how to fix it ? 

@finnhubio

**Comment by finnhubio** [comment]
We are investigating the issue. Thanks for reporting

**Comment by finnhubio** [comment]
> I have same issue today. some times there is no data for any symbol. even cryptos !
> 
> Where is problem and how to fix it ?
> 
> @finnhubio

This issue has been fixed. Our apology.
