### ISSUE TITLE
How does the count argument work?

### ISSUE THREAD

**Issue by jordan-tiona** [finnhubio/Finnhub-API#155]
For example, let's say I want the last 30 one-day candles for F, my initial instinct would be something like `https://finnhub.io/api/v1/stock/candle?symbol=SBIN.NS&resolution=D&count=30&token=?` but at the moment (10:48 GMT-6) that only returns 16 results. Where are the other fourteen candles?

**Comment by finnhubio** [comment]
count param has been deprecated and will be removed in the future. Plz use from and to params instead.

If you still want to use it, here is the instruction. Count = 30 on Daily resolution will set "to" = time.now.Unix() and "from" = time.now.Unix() - 30 * 86400.  It will include weekends in between so you will never get the exact 30 candles. It's a bit confusing so we decided to remove it.

**Comment by jordan-tiona** [comment]
Ah I see, I had a feeling it was just removing non-trading days but was having trouble coming up with only 16 from the past 30. Is there a good way to determine how many full trading days there have been during a specific timeframe?

**Comment by finnhubio** [comment]
no there isn't unfortunately. You just have to query a bigger range and drop some candles.
