### ISSUE TITLE
Websocket api can't get push message for symbols without 'APPL' & 'AMZN'

### ISSUE THREAD

**Issue by yu88my** [finnhubio/Finnhub-API#156]
I use this code below for testing websocket api.
I just get data of 'AAPL' & 'AMZN', no 'NIO' AND 'TLSA''S data.
Is the code or stock symol wrong?
Thank's for answer.

CODE:
_def on_open(ws):
    ws.send('{"type":"subscribe","symbol":"AAPL"}')
    ws.send('{"type":"subscribe","symbol":"NIO"}')
    ws.send('{"type":"subscribe","symbol":"TLSA"}')
    ws.send('{"type":"subscribe","symbol":"AMZN"}')_

RESULT:
_{"data":[{"p":274.7,"s":"AAPL","t":1587474380227,"v":10}],"type":"trade"}
{"data":[{"p":274.7,"s":"AAPL","t":1587474380227,"v":10}],"type":"trade"}
{"data":[{"p":2408.58,"s":"AMZN","t":1587474381156,"v":1}],"type":"trade"}
{"data":[{"p":2408.58,"s":"AMZN","t":1587474381156,"v":1}],"type":"trade"}
{"data":[{"p":2408.58,"s":"AMZN","t":1587474381156,"v":1}],"type":"trade"}_

**Comment by finnhubio** [comment]
This issue has been fixed. Our apology.
