### ISSUE TITLE
websocket cannot connect. 

### ISSUE THREAD

**Issue by ningzesun1993** [finnhubio/Finnhub-API#158]
Hi, when I use websocket, it gives me the error of:
Connection is already closed.
I don't know why this is happened, and there is no data returned.
Can someone help me fix that?

**Comment by finnhubio** [comment]
We are investigating the issue.

**Comment by AnthoBalitrand** [comment]
On my side, since this morning, I manage to have my websocket connected from time to time, but I receive any "trade" message 3 times in a row

**Comment by finnhubio** [comment]
This issue has been fixed. Our apology.

**Comment by ttrasn** [comment]
problem comes again.

after less than second of connecting it disconnected !

**Comment by finnhubio** [comment]
> problem comes again.
> 
> after less than second of connecting it disconnected !

Check your code again. It's working fine on all of our clients socket at the moment.

**Comment by ttrasn** [comment]
> 
> 
> > problem comes again.
> > after less than second of connecting it disconnected !
> 
> Check your code again. It's working fine on all of our clients socket at the moment.

I test my connection with 
https://www.websocket.org/echo.html
but still disconnecting

**Comment by ttrasn** [comment]
> 
> 
> > > problem comes again.
> > > after less than second of connecting it disconnected !
> > 
> > 
> > Check your code again. It's working fine on all of our clients socket at the moment.
> 
> I test my connection with
> https://www.websocket.org/echo.html
> but still disconnecting

I found the problem, sorry my token was using

**Comment by finnhubio** [comment]
> > > > problem comes again.
> > > > after less than second of connecting it disconnected !
> > > 
> > > 
> > > Check your code again. It's working fine on all of our clients socket at the moment.
> > 
> > 
> > I test my connection with
> > https://www.websocket.org/echo.html
> > but still disconnecting
> 
> I found the problem, sorry my token was is use

No worry. It happens to the best of us :) Have a nice weekend.
