### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by Mitstronic** [finnhubio/Finnhub-API#16]
I am inputting the following in the browser:

https://finnhub.io/api/v1/stock/candle?symbol=IBM&resolution=1&from=1546300800&to=1548979199&format=csv&token=bpj9olfrh5rbrf4ncv50

For some reason this is not working, can it be that I have exceeded the maximum of 60API's per second?

**Comment by finnhubio** [comment]
Hi,

We are upgrading our databases so deep historical prices will not be accessible till midnight. You can still query recent OHLC data.

Sorry about the inconvenience.

**Comment by zkghost** [comment]
Midnight which timezone?

**Comment by finnhubio** [comment]
> Midnight which timezone?
New York time (EST)

**Comment by cuongvo** [comment]
> I am inputting the following in the browser:
> 
> https://finnhub.io/api/v1/stock/candle?symbol=IBM&resolution=1&from=1546300800&to=1548979199&format=csv&token=<REMOVE YOUR TOKEN>
> 
> For some reason this is not working, can it be that I have exceeded the maximum of 60API's per second?

@Mitstronic  Please edit your original issue to remove your token. This is private to you and will anyone to use your API account. I tested it and the token is still valid as of the time of this message.
