### ISSUE TITLE
No notification of changes to public API and/or behaviour

### ISSUE THREAD

**Issue by ravicheema** [finnhubio/Finnhub-API#161]
We have noticed that the Finnhub API behaviour is constantly evolving. This is a great positive since it shows positive development efforts. However, there is currently no way for an end-user to determine if the API has changed and how those changes impact our application(s). 

For example, the 'count' parameter was currently deprecated. It has been removed from the documentation, but **where was the notification to the end-user of this change?**

There are many easy ways to communicate behaviour has changed to end-users, I'm sure many users would welcome such an addition.

**Comment by finnhubio** [comment]
We apologize about this. We will do a better job regarding API changes in the future.
