### ISSUE TITLE
Stocks with '&' in name having incorrect symbols

### ISSUE THREAD

**Issue by pchhiller** [finnhubio/Finnhub-API#162]
Hey, There are a lot of symbols with the '&' in it's symbols, and API is not giving quotes for those stocks at https://finnhub.io/api/v1/stock/symbol?exchange=NS 
eg. {"description":"Cox \u0026 Kings Ltd","displaySymbol":"COX\u0026KINGS.NS","symbol":"COX\u0026KINGS.NS"}

I am not able to get the price for this

**Comment by finnhubio** [comment]
There is actually nothing wrong. You are just making the request correctly. Here is a sample python code you should follow 

import requests
params = {'symbol' : 'COX&KINGS.NS', 'token': ''}
r = requests.get('https://finnhub.io/api/v1/quote', params=params)
r.json()
