### ISSUE TITLE
major development documentation mismatch

### ISSUE THREAD

**Issue by llonchj** [finnhubio/Finnhub-API#167]
## What is the issue ?

The documentation in https://finnhub.io/docs/api#major-developments describes the response attribute `datetime` as UNIX ms and the sample response shows the attribute `date`.

## How to reproduce the error ?

`curl 'https://finnhub.io/api/v1/major-development?symbol=AAPL&token=YOURTOKEN'`

## What is the expected result and why do you think it's the correct result ?

The real API call returns `datetime` as a string in `YYYY-MM-DD HH:MM:SS`.

1. The documentation for `datetime` should be replaced with the right format.
1. The sample response (example) for this endpoint should show the attribute `date` instead of `datetime`.

**Comment by finnhubio** [comment]
Thank you for reporting. We will fix it asap
