### ISSUE TITLE
incomplete ticker data on 2020-04-24

### ISSUE THREAD

**Issue by llonchj** [finnhubio/Finnhub-API#170]
## What is the issue ?

Ticker data on 2020-04-24 appears to be incomplete.

## How to reproduce the error ?

request `/stock/tick?symbol=TSLA&date=2020-04-24` last tick is from 13:30:54 EDT.

* SNAP -> 13:24:21 EDT
* DAL -> 12:37:36 EDT
* GOOGL -> 12:48:58 EDT

## What is the expected result and why do you think it's the correct result ?

I will expect the last tick to be on or close to 20:00:00 EDT for US symbols

**Comment by finnhubio** [comment]
Should be fixed now.
