### ISSUE TITLE
Dividend Endpoint of ADR responds with empty array

### ISSUE THREAD

**Issue by Matthew-Cameron** [finnhubio/Finnhub-API#171]
Hi, 
Are dividends of ADR's not currently supported?
ex. RDS-A and RDS-B (among many others) just return an empty array.
https://finnhub.io/api/v1/stock/dividend?symbol=RDS-B&from=2019-02-01&to=2020-02-01&token=*****************

**Comment by finnhubio** [comment]
We only support dividends for common stocks at the moment. We are working to support ETF and ADR in the future.
