### ISSUE TITLE
From which Stock exchanges are Financial Fundamentals available? 

### ISSUE THREAD

**Issue by MLUY** [finnhubio/Finnhub-API#174]
If I subscribe to Finn hub what stock exchanges are available with fundamental data (full income statement, balance statement and cashflow) ? I am looking for an way to retrieve stock fundamentals from all major stock exchanges so not just USA. I would like to have access to all equities from USA&Europe such as Nasdaq, Euronex, FTSE, DAX etc etc.

**Comment by finnhubio** [comment]
we have data for all the exchanges you mentioned and more.

**Comment by MLUY** [comment]
Thanks!, so just to be clear
I need a premium account that costs 99gbp/month to get 10yr financial
statements for companies on all these exchanges?

**Comment by finnhubio** [comment]
yes that's correct.
