### ISSUE TITLE
Stock ticker symbol change

### ISSUE THREAD

**Issue by frosk1** [finnhubio/Finnhub-API#175]
Hi,

my company would like to know how are you handling stock ticker symbol changes and do you provide a list of historical stock ticker symbol changes? So what happens if a ticker is no longer available and the company changed the ticker symbol, specifically can I get historical data under the new ticker symbol or with the old one? Do you apply isin symbol lookup for that?

**Comment by finnhubio** [comment]
For enterprise support, please email us at support@finnhub.io 

In general, we keep the exact symbol as it was traded on the exchange on that day.
