### ISSUE TITLE
No real time data for free plan?

### ISSUE THREAD

**Issue by greencat2020** [finnhubio/Finnhub-API#176]
I can get data from yesterday using the following url:
https://finnhub.io/api/v1/stock/candle?symbol=MU&resolution=5&from=1588080600&to=1588081600&token=

but I cannot get today's data using the following url:
https://finnhub.io/api/v1/stock/candle?symbol=MU&resolution=5&from=1588167000&to=1588168200‬&token=

Does free plan not have real-time data?

**Comment by finnhubio** [comment]
Looks like there are special characters in your URL. Plz fix it first.

https://finnhub.io/api/v1/stock/candle?symbol=MU&resolution=5&from=1588167000&to=1588168200&token= works fine
