### ISSUE TITLE
How to get Stock Candles of indexes: SP500, NASDAQ-100, ...?

### ISSUE THREAD

**Issue by RiSaMa** [finnhubio/Finnhub-API#177]
Thank you for your amazing API, documentation, and work!

I am aware that you can retrieve the list of available stocks here:

`
https://finnhub.io/api/v1/stock/symbol?exchange=US&token=<mytoken>
`

However I was not able to find how to retrieve Stock Candles of indexes such as SP500, NASDAQ-100, FTSE (UK index), IBEX (Spanish index), ... How would it be the call?

`
https://finnhub.io/api/v1/stock/candle?symbol=XXXX&resolution=1&from=1572651390&to=1572910590&token=<myToken>
`
Thank you in advance

**Comment by finnhubio** [comment]
Try exchange=indices to get the list of indices.

**Comment by RiSaMa** [comment]
Thank you so much! Perfect!

I believe this is not in the documentation yet. Good to know.

Thanks for your work and support again!

**Comment by RiSaMa** [comment]
I am able to retrieve the list of indeces with this request:

`
https://finnhub.io/api/v1/stock/symbol?exchange=indices&token=<mytoken>
`

However, I am unable to get stock data with this one:

`
https://finnhub.io/api/v1/stock/candle?symbol=^GSPC&resolution=1&from=1572651390&to=1572910590&token=<mytoken>
`

What am I missing?

Thank you in advance

**Comment by finnhubio** [comment]
We don't support deep historical data for indices at the moment. Plz change to a more recent time range

**Comment by RiSaMa** [comment]
What's the oldest accessible data?

Thank you

**Comment by finnhubio** [comment]
Plz query iteratively to find that out. We don't have that number on top of our head for every single symbol

**Comment by RiSaMa** [comment]
OK. Thank you again :).
