### ISSUE TITLE
Stock Futures data

### ISSUE THREAD

**Issue by kennethaasan** [finnhubio/Finnhub-API#178]
## What is the issue ? Plz describe in details

How can I access the stock futures data? For example, FB (Facebook https://finnhub.io/api/v1/quote?symbol=FB.US) is valued to $213.70 as we speak in futures, while the current price in the quote endpoint is $194.19.

Thanks,
Kenneth

**Comment by finnhubio** [comment]
We do not support futures data at the moment.

**Comment by finnhubio** [comment]
If you meant pre and post market hour. You can add "&trade=true" into the quote endpoint to get them. Not if that's what you are looking for by "future" though.

**Comment by kennethaasan** [comment]
Thanks! That's what I was looking for. That should probably be added to the documentation (https://finnhub.io/docs/api#quote)
