### ISSUE TITLE
feature request: websocket minute bars

### ISSUE THREAD

**Issue by M00NSH0T** [finnhubio/Finnhub-API#18]
I like your service, but I really wish you provided live minute bars via a fast websocket connection so I get the latest as soon as its ready. I've tried building my own minute bars by streaming all updates with your websocket call, by my model looks at 818 companies in realtime, and that's just too much for a single websocket connection to handle. 

Polygon provides minute bars via a websocket and it's super fast and reliable. I get the updates typically about 4 seconds after the minute for all 800+ companies (or as many as had trades) and it works great. But I don't like being dependent on only one service... I need redundancy.  Please add minute bars to your websocket service.

**Comment by finnhubio** [comment]
Thanks for the feedback. We will look into it

**Comment by Brechard** [comment]
Will this be implemented at some point? It would be nice to be able to have candles in websockets with the ability of choosing the resolution!
