### ISSUE TITLE
Tick data of this week(28 Apr 2020) is not available

### ISSUE THREAD

**Issue by chanyk-joseph** [finnhubio/Finnhub-API#180]
Request time" 30 Apr 2020

https://finnhub.io/api/v1/stock/tick?symbol=TSLA&date=2020-04-28&token=xxxxxxxxxxxxxxxxxxx
404 page not found

same for aapl. What is the time delay for the latest tick data??
1 week?

**Comment by finnhubio** [comment]
This issue has been fixed. Sorry about the delay in updating the data.
