### ISSUE TITLE
Belgium stock Ageas (ISIN: BE0974264930, AGS) not available

### ISSUE THREAD

**Issue by jalberty2018** [finnhubio/Finnhub-API#182]
## What is the issue ?

No Symbol found for Belgium Stock Ageas AGS.BR
https://finance.yahoo.com/quote/AGS.BR
curl -k -X GET \
https://finnhub.io/api/v1/stock/symbol?token=&exchange=BR

## How to reproduce the error ?
curl -k -X GET \
https://finnhub.io/api/v1/stock/candle?symbol=AGS.BR&resolution=D&count=315576000&token=

## What is the expected result and why do you think it's the correct result ?

Candle , Quote information stock

**Comment by scousie** [comment]
Indeed: I have the same problem.
I downloaded al symbols for "BR" market, but I can't find AGEAS, however it is a BEL20-value.

AGEAS | BE0974264930 | Euronext Brussels

https://finnhub.io/api/v1/quote?symbol=AGS.BR&token=xxxxxxxx
--> no symbol found

**Comment by finnhubio** [comment]
We added AGS.BR into our system. Should be available starting next week. Our apology for the issue.

**Comment by finnhubio** [comment]
We just updated the full stock list on Euronext. Any missing symbols should be available now.
