### ISSUE TITLE
AEX-INDEX (^AEX) Amsterdam not available

### ISSUE THREAD

**Issue by jalberty2018** [finnhubio/Finnhub-API#183]
## What is the issue ? Plz describe in details
AEX index not available  for for Dutch stock market
AEX-INDEX (^AEX) Amsterdam
https://finance.yahoo.com/quote/%5EAEX

## How to reproduce the error ?
curl -k -X GET \
https://finnhub.io/api/v1/stock/symbol?exchange=indices&token=
Symbol not found in list

## What is the expected result and why do you think it's the correct result ?
Stock index symbol

**Comment by finnhubio** [comment]
We unfortunately don't have access to this symbol at the moment
