### ISSUE TITLE
^TNX - 10 Year Treasury Index Support

### ISSUE THREAD

**Issue by morizmartiner** [finnhubio/Finnhub-API#184]
## What is the issue ? Plz describe in details

Does the Finnhub API support the ^TNX - 10 Year Treasury Index? If yes, how is it possible to access it? If not, would it maybe be possible to add it?

## How to reproduce the error ?

https://finnhub.io/api/v1/stock/candle?token=<token>&resolution=D&adjusted=true&symbol=%5EDJI&count=10

## What is the expected result and why do you think it's the correct result ?

Return the candles for ^TNX.

**Comment by finnhubio** [comment]
We unfortunately don't have that data at the moment.

**Comment by morizmartiner** [comment]
Ok, thanks anyways!
