### ISSUE TITLE
Stock candle requests for certain symbols do not return up-to-date data

### ISSUE THREAD

**Issue by ravicheema** [finnhubio/Finnhub-API#185]
We have noticed that certain stock candle requests do not return up-to date data. 

For example, the request,
https://finnhub.io/api/v1/stock/candle?adjusted=false&from=1104537600&resolution=D&symbol=IDBZ.L&to=1588455045&token=

Returns 3084 candles, 2008/01/02 to 2020/04/03, this should return data up-to 2020/04/30

This is problem is repeated for various symbols across the London Stock Exchange (exchange code = L)

Another example request,
https://finnhub.io/api/v1/stock/candle?adjusted=false&from=1104537600&resolution=D&symbol=INFU.L&to=1588455620&token=

Returns 1009 candles 2016/04/13 to 2020/04/06, this should return data up-to 2020/04/30

**Comment by ravicheema** [comment]
An interesting observation - the data appears to be consistent with the free Yahoo service, i.e. Yahoo also reports the same missing data.

However, Reuters and IG Index data does not have missing data.

This raises questions, however we hope this issue can be resolved quickly.

**Comment by ravicheema** [comment]
**This is a major issue, and for a premium paid for service is not acceptable.** Many, many symbols on LSE, requests for the latest daily candles DO NOT return the latest daily candles! 

I would expect a request for the latest daily candles performed on Sat 2nd May 2020 for every single symbol on LSE to to return the latest daily candles to and including Fri 1st May 2020.

For example, on Sat 2nd May 2020, I performed the following request
https://finnhub.io/api/v1/stock/candle?adjusted=false&from=1104537600&resolution=D&symbol=JPTS.L&to=1588424400&token=

I would expect this request to return daily candles to and including Fri 1st May 2020. However the request only returned daily candles to 3rd April 2020.

The symbol is actively traded and https://uk.tradingview.com/chart/?symbol=LSE%3AJPTS, clearly shows the latest data. 

However, if you look at yahoo finance, https://uk.finance.yahoo.com/quote/JPTS.L/history?p=JPTS.L, it only shows data to 3rd April 2020, i.e. this is consistent with the data returned by finnhub.io

This is not what we would expect from a premium service. Have a look at the following screenshots.

<img width="1648" alt="Screenshot 2020-05-02 at 14 39 51" src="https://user-images.githubusercontent.com/2190518/80866033-7681a100-8c84-11ea-9bb5-590d722cfa68.png">

<img width="1648" alt="Screenshot 2020-05-02 at 14 52 45" src="https://user-images.githubusercontent.com/2190518/80866064-a29d2200-8c84-11ea-935f-1a2da9d76ea2.png">

**Comment by finnhubio** [comment]
We are looking into the issue.

**Comment by ravicheema** [comment]
I provided additional details to assist. Why on earth would you delete my comment? Your business will not be successful if you carry on like this.

**Comment by finnhubio** [comment]
Plz read our guideline before posting here. Comments violates our policy will be deleted without warnings. Specifically, we do not allow mention of other providers on our public community forum. You are free to discuss and compare providers elsewhere. 

Hope it helps. We have alert our EOD data provider regarding the issue. Should be fixed next week for UK ETFs.

**Comment by finnhubio** [comment]
Our provider said that they fixed IDBZ on daily timeframe.
