### ISSUE TITLE
Empty stock profile returned for many active stocks on LSE

### ISSUE THREAD

**Issue by ravicheema** [finnhubio/Finnhub-API#187]
Performing the following request, https://finnhub.io/api/v1/stock/profile?symbol=TYT.L&token=
Returns {}
I would expect a fully populated stock profile would be returned for Toyota Motor Corporation (TYT.L)

Another example is, https://finnhub.io/api/v1/stock/profile?symbol=RYA.L&token=
Which also returns {}
I would expect a fully populated stock profile would be returned for Ryanair Holdings plc (RYA.L)

Another example is, https://finnhub.io/api/v1/stock/profile?symbol=RDSA.L&token=
Which also returns {}
I would expect a fully populated stock profile would be returned for Royal Dutch Shell Plc (RDSA.L)

Many more examples are available.

**Comment by finnhubio** [comment]
This is just an issue with company listed on multiple exchanges. For example Toyota primary symbol is 7203.T . We have provided automatic mapping for other endpoints and will add it to company profile tomorrow so you should be able to query as you are doing right now soon.

**Comment by ravicheema** [comment]
Thank you for your response. There are many more examples of this issue, will this issue be resolved for *ALL* companies listed on multiple exchanges?

**Comment by finnhubio** [comment]
Yes it will be resolved for all companies that we have fundamental coverage. Of course we do not cover every single public company in the world and not even Bloomberg does anyway. Hope it helps.

**Comment by ravicheema** [comment]
I'm looking forward to verifying your fixes. Many Thanks

**Comment by finnhubio** [comment]
@ravicheema this issue has been fixed. plz try again. Let us know if you still encounter any difficulty. Our apology for the inconvenience.

Khoa,
Finnhub Data Science team

**Comment by ravicheema** [comment]
Definitely looks better. There are still loads missing, some examples are,
Fletcher King Plc (FLK.L)
Honeywell International Inc. (HON.L)
Mitsubishi Electric Corporation (MEL.L)
Knights Group Holdings plc (KGH.L)
Katoro Gold plc (KAT.L)

**Comment by finnhubio** [comment]
FLK and HON have been delisted. MEL we don't have coverage. We will look into KGH and KAT. Thanks for letting us know.

**Comment by finnhubio** [comment]
This issue has been fixed. All supported symbols on LSE have been mapped correctly.
