### ISSUE TITLE
Missing data (Dividend & News) for most TSX stocks

### ISSUE THREAD

**Issue by severusKen** [finnhubio/Finnhub-API#190]
So I'm developing an app and using the free api key. 

1/ For some popular stocks/ETFs listed on Toronto Stock Exchange, the dividend data is mising. 

2/ For all of the TSX tickers that I tried so far data for the [Company News] data is also missing.

I don't know if I have to pay to get this information, or it's just that you guys don't have all the data atm. Either way, please let me know, so I can have a proper plan for future development.

**Comment by finnhubio** [comment]
We do not provide news for stocks on TSX at the moment.

Can you provide a list of "popular stocks/ETFs" that you need dividend data ? We can help take a look.

**Comment by severusKen** [comment]
Thanks for replying. Do you guys have any upcoming plan for the News feature? "News" plays an important role in my project, it's the last thing that preventing me from upgrading to Professional Subscription and publishing my project.
As for the popular stocks, I meant all the stocks in the TSX 60 listing. But none of the stocks has any News data and some of them don't even have dividend data.

**Comment by jwadia** [comment]
I believe most of the Canadian REIT companies don't have proper dividend data  - one example is VRE.TO. Most stocks with xxx-un.TO or xxx.un.TO also don't have proper data.

**Comment by severusKen** [comment]
Haha sometimes I get jealous with our South Neighbor when it comes to financial services. @finnhubio our team love your products, please notify us if you guys have any plan for the Canadian stock database. Until then, we can't really release any work (Canadian) using your service.

**Comment by finnhubio** [comment]
International news is only available for enterprise clients at this point. If you are building a commercial project, feel free to reach out to us at support@finnhub.io. Regarding personal use, we are looking into it.

**Comment by finnhubio** [comment]
News for TSX is now available.

**Comment by Pooja-Ghule-9** [comment]
hello i'm trying to download data for a list of stocks on Canada, US, Singapore and Japan but it's not giving me data for all the stocks in my list (SLV and CSCO).
