### ISSUE TITLE
General NewsAPI sending newline(\n).

### ISSUE THREAD

**Issue by pius1212** [finnhubio/Finnhub-API#191]
## What is the issue ? Plz describe in details
When I query the News API, it sends the news data with '\n' in the 'summary' section which completely breaks a java library I'm using to parse the JSON.
## How to reproduce the error ?
You can view 'https://finnhub.io/api/v1/news?category=general&token=' and do a Ctrl+F search for \n
## What is the expected result and why do you think it's the correct result ?
I would expect the API to send the data without \n, as the Sample Response on the documentation doesn't include \n.

**Comment by finnhubio** [comment]
It is a strange problem. \n in string is still a valid JSON. Plz check with the author of your library instead.
