### ISSUE TITLE
Trailing 52-week prices

### ISSUE THREAD

**Issue by bernardobelchior** [finnhubio/Finnhub-API#192]
Hey, I can't find any 52-week prices (i.e., 52-week high and low), is that intentional? 
Is there any plan to implement them? 

I'd like to integrate with FinnHub, but without this I have to integrate with another API as well, or even just use the other API if that fulfills my requirements.

Thanks!

**Comment by finnhubio** [comment]
You can get it here: https://finnhub.io/api/v1/stock/metric?symbol=AMZN&metric=price

Sorry we just have a little too much data to document every single data point. It will take a bit of time to navigate around all this data :) Feel free to let us know if you need anything else.

**Comment by bernardobelchior** [comment]
Thanks!
