### ISSUE TITLE
Missing Earnings for Toronto Dominion Bank

### ISSUE THREAD

**Issue by bernardobelchior** [finnhubio/Finnhub-API#193]
## What is the issue ?

There are missing earnings for the Toronto Dominion Bank (TD). As of writing this issue, the API is returning earnings for the period Q1 2017 to Q1 2018 (both included). 

## How to reproduce the error ?

Make an API call to:
`https://finnhub.io/api/v1/stock/earnings?token=apikey&symbol=TD`

### Current Result 
```json
[{"actual":1.22,"estimate":1.15,"period":"2018-03-31","symbol":"TD"},{"actual":1.07,"estimate":1.1,"period":"2017-12-31","symbol":"TD"},{"actual":1.19,"estimate":1.07,"period":"2017-09-30","symbol":"TD"},{"actual":1.05,"estimate":0.98,"period":"2017-06-30","symbol":"TD"},{"actual":1.08,"estimate":1.03,"period":"2017-03-31","symbol":"TD"}]
```

### Expected Results:

The results according to the bank's website: https://www.td.com/investor-relations/ir-homepage/financial-reports/quarterly-results/qr-2020.jsp

The results in the website are the actual source of truth for earnings data.

**Comment by finnhubio** [comment]
Plz try https://finnhub.io/api/v1/stock/earnings?token=&symbol=TD.TO instead.

**Comment by bernardobelchior** [comment]
Thanks. However, TD is also listed in the NYSE. Why can't I access it like that?

**Comment by finnhubio** [comment]
We are trying to do better on the automatic mapping for symbols listed on multiple exchanges but it is still work in progress so you should figure out the main exchange of a company and put in the correct symbol to get full data for fundamentals endpoint.

For fundamental data, all symbols point to the same company (unlike stock price) so it doesn't make any difference in the underlying data.

**Comment by finnhubio** [comment]
We just made a huge upgrade on the automatic symbol mapping today. It also include TD -> TD.TO . You can try to query again now. Hope it helps.

**Comment by bernardobelchior** [comment]
It's working now, thanks!

**Comment by bernardobelchior** [comment]
Sorry for bothering again! This is a bit different, but still similar and happening for Berkshire Hathaway. 
When getting the earnings for the A stock, everything ok; but it doesn't return anything for the B stock.

OK: `https://finnhub.io/api/v1/stock/earnings?&symbol=BRK-A&token=`
Not OK: `https://finnhub.io/api/v1/stock/earnings?&symbol=BRK-B&token=`

**Comment by finnhubio** [comment]
> Sorry for bothering again! This is a bit different, but still similar and happening for Berkshire Hathaway.
> When getting the earnings for the A stock, everything ok; but it doesn't return anything for the B stock.
> 
> OK: `https://finnhub.io/api/v1/stock/earnings?&symbol=BRK-A&token=`
> Not OK: `https://finnhub.io/api/v1/stock/earnings?&symbol=BRK-B&token=`

Thanks for letting us know. We will look into it.

**Comment by finnhubio** [comment]
Our data team has decided not to map class B into class A at this point. You will need to query class A share to get fundamental data.
