### ISSUE TITLE
Missing Data for Commodities (Gold, Crude Oil etc.)

### ISSUE THREAD

**Issue by epickiller1989** [finnhubio/Finnhub-API#195]
Hello Finnhub-Team,

first of all, you made a great job! Your API is extremly good! Thank you!

I want to request commodity data like Gold (GC:CMX or GC=F), WTI (CL:NMX or CL=F) or Brent (BZ:NMX or BZ=F), but til now I couldn't get it to work (via Stock Candles). Is there a possibility to request the data or do you plan to offer the data in the next future?

It would be also a perfect combination to your economic data.
 
Best Regards
Christopher

**Comment by finnhubio** [comment]
We do not support data for futures at the moment. The closest thing you can get is to query future data through Forex brokers such as Oanda or FXCM.

**Comment by epickiller1989** [comment]
Thank you for your quick answer! Futures would be very nice, but your suggestion is also fine for the beginning. Thanks a lot.
