### ISSUE TITLE
No data issue

### ISSUE THREAD

**Issue by debimish** [finnhubio/Finnhub-API#197]
https://finnhub.io/api/v1/stock/candle?symbol=533096.BO&resolution=D&from=946785600&to=1577937600&token

https://finnhub.io/api/v1/stock/candle?symbol=500325.BO&resolution=D&from=946785600&to=1577937600&token

This call returns : {"s":"no_data"}

The symbols are available in the list of stocks obtained using exchange "BO" using the API call with a free tier account.

**Comment by finnhubio** [comment]
These symbols will be removed as not supported. Sorry about the confusion.
