### ISSUE TITLE
OpenAPI Spec

### ISSUE THREAD

**Issue by nothratal** [finnhubio/Finnhub-API#198]
Hello,

do you have the API's in an OpenAPI Spec so we can generate clients with the OpenAPI-Generator?https://github.com/OpenAPITools/openapi-generator

Maybe some other parsable specification?

**Comment by finnhubio** [comment]
If you go to our documentation page: https://finnhub.io/docs/api , open console -> you can find the spec in the variable `window.docSchema`

**Comment by nothratal** [comment]
Thats great!! Sorry, I didn't knew that!

**Comment by finnhubio** [comment]
No worry. Glad that I could help.
