### ISSUE TITLE
Some symbol return no_data

### ISSUE THREAD

**Issue by bestbug456** [finnhubio/Finnhub-API#199]
## What is the issue ? Plz describe in details

I was try you service for the first time and but some are missing. for instance AMD.DE return no_data

## How to reproduce the error ?

https://finnhub.io/api/v1/stock/candle?symbol=AMD.DE&resolution=D&from=1572651390&to=1572910590&token=TOKEN_ID

## What is the expected result and why do you think it's the correct result ?

I was expecting to find the same information I've got with other symbol but I got none. This is something expected? I've try with different range and different resolution without any success. I've also see the symbol is not listed on the exchange api. I'm missing something? 

Thanks for the support!

**Comment by finnhubio** [comment]
Should be fixed this week. Sr about the issue. If you have any other stocks you would like to add, feel free to let us know as well.

**Comment by bestbug456** [comment]
Hi thanks for the quick response! I've also found missing MSF.DE, APC.DE and AMZ.DE

**Comment by epickiller1989** [comment]
I also have some stocks that I miss: DHER.DE, LYYA.DE, SHL.DE, KBX.DE, HFG.DE, VAR1.DE, B4B.DE, UTX, UN01.DE, TMV.DE

**Comment by lorenzweidinger** [comment]
I have a ticker which I get for the peers of ADS.DE which is missing: ML2.F

**Comment by mrzzheng** [comment]
Same for some US equity indexes such as ^GSPC. Any idea why/when it will be fixed? Thanks.

**Comment by finnhubio** [comment]
> Same for some US equity indexes such as ^GSPC. Any idea why/when it will be fixed? Thanks.

We do have data for ^GSPC. You are just querying out of range. Try more recent days

**Comment by mrzzheng** [comment]
It indeed worked earlier but not now:
https://finnhub.io/api/v1/stock/candle?symbol=^GSPC&resolution=D&from=1104508800&to=1575243390&token=...

**Comment by finnhubio** [comment]
This issue has been fixed. We updated stock list for Xetra , Frankfurt, TSX, LSE and Euronext
