### ISSUE TITLE
Documentation - Wrong description in Stock Exchange section

### ISSUE THREAD

**Issue by pranavKVP** [finnhubio/Finnhub-API#201]
## What is the issue ? Plz describe in details
under Response Attributes, description of Array says "Array of supported forex exchanges.".
the word forex should be replaced with "Stock".
## How to reproduce the error ?
Go to: https://finnhub.io/docs/api#stock-exchanges

## What is the expected result and why do you think it's the correct result ?
As it's a list of stock exchange and not forex.

**Comment by finnhubio** [comment]
Thank you for reporting. We will fix it asap

**Comment by finnhubio** [comment]
This issue has been fixed
