### ISSUE TITLE
Documentation - Major Developments - Descripencies in output, documentation and example output

### ISSUE THREAD

**Issue by pranavKVP** [finnhubio/Finnhub-API#202]
## What is the issue ? Plz describe in details
1. in actual response, "majorDevelopment" also contains "symbol" which is not documented and also missing from Sample Response.
2. actual response has "datetime" while Sample Response has "date"
## How to reproduce the error ?
Go to: https://finnhub.io/docs/api#major-developments

## What is the expected result and why do you think it's the correct result ?
Needed clarification were "symbol" should be and change in documentation accordingly.

**Comment by finnhubio** [comment]
We have fixed it. Thanks for reporting
