### ISSUE TITLE
Company news API ignores date range

### ISSUE THREAD

**Issue by wannikid** [finnhubio/Finnhub-API#203]
## What is the issue ? Plz describe in details
I am using the example from your API documentation website to retrieve company news. Instead of returning the news for the provided date range, it returns the latest 50 news items.

API call:
https://finnhub.io/api/v1/company-news?symbol=AAPL&from=2020-04-30&to=2020-05-01&token=

Response:
_[{"category":"company","datetime":1588677909,"headline":"Zimmer Biomet: Wait And Watch",..._

The first returned timestamp translates to 05/05/2020, which is beyond the range.

## How to reproduce the error ?
Using the API example provided here: https://finnhub.io/docs/api#company-news

## What is the expected result and why do you think it's the correct result ?
I would expect to only get the news returned that meet the range.

**Comment by finnhubio** [comment]
This issue has been fixed. Our apology for the inconvenience.
