### ISSUE TITLE
feature request:  Historical stock prices

### ISSUE THREAD

**Issue by Z223I** [finnhubio/Finnhub-API#204]
Am not seeing a way to get historical stock prices in the API.

Would like to get data from date to date  [closing price | hourly | 30 minutes | etc ].

Is that currently possible?  If not, can it be added?

Thanks!!

**Comment by finnhubio** [comment]
You can use this endpoint : https://finnhub.io/docs/api#stock-candles

**Comment by Z223I** [comment]
Thank you!!
