### ISSUE TITLE
Documentation - Revenue & Earnings Estimates have same description

### ISSUE THREAD

**Issue by pranavKVP** [finnhubio/Finnhub-API#205]
## What is the issue ? Plz describe in details
Have same description for Revenue and Earnings Estimates
## How to reproduce the error ?
Go to: https://finnhub.io/docs/api#company-revenue-estimates
and: https://finnhub.io/docs/api#company-eps-estimates

**Comment by finnhubio** [comment]
We have fixed it. Thanks for reporting
