### ISSUE TITLE
Request for confirmation of UK stock adjusted price

### ISSUE THREAD

**Issue by littlehongkong** [finnhubio/Finnhub-API#206]
I am looking at the data using the url below,

https://finnhub.io/api/v1/stock/candle?symbol=BAG.L&resolution=D&from=473526000&to=1588808070&token=myToken

If you give the adjusted parameter a True value, there are a number of items that do not exist.

Isn't that right?

**Comment by finnhubio** [comment]
This issue has been fixed. Our apology for the inconvenience.
