### ISSUE TITLE
incomplete candle data

### ISSUE THREAD

**Issue by michaelwalter5** [finnhubio/Finnhub-API#208]
Why is it, that requests for 1Minute to 1hour candles for a time period of 2 days come back with only a few candles ? 

## How to reproduce the error ?

Examples (token removed) :

https://www.finnhub.io/api/v1/stock/candle?symbol=IFX.DE&resolution=1&from=1588700924&to=1588873724

result for 1 minute candles from 05.05.2020 to 07.05.2020: 5 candles , should be 960:

259 bytes
{
    c =     (
        "16.74",
        "17.582",
        "17.608",
        "17.6",
        "17.598"
    );
    h =     (
        "16.774",
        "17.604",
        "17.61",
        "17.61",
        "17.61"
    );
    l =     (
        "16.74",
        "17.568",
        "17.584",
        "17.6",
        "17.594"
    );
    o =     (
        "16.774",
        "17.604",
        "17.584",
        "17.61",
        "17.608"
    );
    s = ok;
    t =     (
        1588748400,
        1588771800,
        1588771860,
        1588771920,
        1588771980
    );
    v =     (
        0,
        5820223,
        22562,
        29354,
        28408
    );
}

https://www.finnhub.io/api/v1/stock/candle?symbol=IFX.DE&resolution=5&from=1588700924&to=1588873724

result for 5 minute candles from 05.05.2020 to 07.05.2020: 3 candles: should be 96

164 bytes
{
    c =     (
        "16.74",
        "17.598",
        "18.2"
    );
    h =     (
        "16.774",
        "17.61",
        "18.2"
    );
    l =     (
        "16.74",
        "17.568",
        "18.2"
    );
    o =     (
        "16.774",
        "17.604",
        "18.2"
    );
    s = ok;
    t =     (
        1588748400,
        1588771800,
        1588865700
    );
    v =     (
        0,
        5900547,
        0
    );
}

https://www.finnhub.io/api/v1/stock/candle?symbol=IFX.DE&resolution=15&from=1588700924&to=1588873724

result: for 15 minute candles from 05.05.2020 to 07.05.2020: 3 candles, should be 64:

164 bytes
{
    c =     (
        "16.74",
        "17.598",
        "18.2"
    );
    h =     (
        "16.774",
        "17.61",
        "18.2"
    );
    l =     (
        "16.74",
        "17.568",
        "18.2"
    );
    o =     (
        "16.774",
        "17.604",
        "18.2"
    );
    s = ok;
    t =     (
        1588748400,
        1588771800,
        1588865400
    );
    v =     (
        0,
        5900547,
        0
    );
}

https://www.finnhub.io/api/v1/stock/candle?symbol=IFX.DE&resolution=30&from=1588700924&to=1588873724

result for 30 minute candles from 05.05.2020 to 07.05.2020:3 candles: should be 32:

164 bytes
{
    c =     (
        "16.74",
        "17.598",
        "18.2"
    );
    h =     (
        "16.774",
        "17.61",
        "18.2"
    );
    l =     (
        "16.74",
        "17.568",
        "18.2"
    );
    o =     (
        "16.774",
        "17.604",
        "18.2"
    );
    s = ok;
    t =     (
        1588748400,
        1588771800,
        1588865400
    );
    v =     (
        0,
        5900547,
        0
    );
}

https://www.finnhub.io/api/v1/stock/candle?symbol=IFX.DE&resolution=60&from=1588700924&to=1588873724&token=bqkuj6frh5rcf2c462g0

result: for 60 minute candles from 05.05.2020 to 07.05.2020: 2 candles, should be 16:

131 bytes
{
    c =     (
        "16.74",
        "17.598"
    );
    h =     (
        "16.774",
        "17.61"
    );
    l =     (
        "16.74",
        "17.568"
    );
    o =     (
        "16.774",
        "17.604"
    );
    s = ok;
    t =     (
        1588748400,
        1588770000
    );
    v =     (
        0,
        5900547
    );
}

## What is the expected result and why do you think it's the correct result ?

result for 1 minute candles from 05.05.2020 to 07.05.2020 should be 960 candles
result for 5 minute candles from 05.05.2020 to 07.05.2020 should be 192 candles
result for 15 minute candles from 05.05.2020 to 07.05.2020 should be 64 candles
result for 30 minute candles from 05.05.2020 to 07.05.2020 should be 32 candles
result for 60 minute candles from 05.05.2020 to 07.05.2020 should be 16 candles

** The following cases will not be answered or deleted without warnings.
1. No reproducible example in the issue.
2. Compare data sources (We do not know how other companies prepare their data so we will not investigate these claims)
3. Being rude or use inappropriate language in the issue.

**Comment by finnhubio** [comment]
Thanks for reporting. We will look into it

**Comment by finnhubio** [comment]
We fixed it
