### ISSUE TITLE
Retrieve the type of an asset

### ISSUE THREAD

**Issue by hourliert** [finnhubio/Finnhub-API#209]
Hi,

That might be a very dumb question, but I am trying to get the category of a stock asset (eg. ETF, index fund, stock, etc). Is there a way of doing that using the API?

Thanks in advance.

**Comment by pranavKVP** [comment]
Check out Company Profile 2: https://finnhub.io/api/v1/stock/profile2?symbol=AAPL&token={{Token}}

**Comment by hourliert** [comment]
Thanks for your reply.

This seems to work well to retrieve the company info of a stock (eg.
https://finnhub.io/api/v1/stock/profile2?symbol=AAPL&token={{Token}} or
https://finnhub.io/api/v1/stock/profile2?symbol=AMD&token={{Token}}
<https://finnhub.io/api/v1/stock/profile2?symbol=AAPL&token=%7B%7BToken%7D%7D>)
but it returns an empty object {} when I use it with an ETF

Eg.
 https://finnhub.io/api/v1/stock/profile2?symbol=VWRL&token={{Token}}
<https://finnhub.io/api/v1/stock/profile2?symbol=AAPL&token=%7B%7BToken%7D%7D>
 https://finnhub.io/api/v1/stock/profile2?symbol=VWRl.L&token={{Token}}
<https://finnhub.io/api/v1/stock/profile2?symbol=AAPL&token=%7B%7BToken%7D%7D>

All return {}.

What's interesting is that when I query
https://finnhub.io/api/v1/stock/symbol?exchange=L&token={{Token}}
<https://finnhub.io/api/v1/stock/symbol?exchange=L&token=bqq7qbnrh5re9mjl1eog>
to
get all the stocks from the London Stock Exchange, I actually get VWRL.L in
the response.

Any idea what I am doing wrong?

Thanks in advance

**Comment by finnhubio** [comment]
This is not possible with the current API unfortunately.

**Comment by hourliert** [comment]
No worries. Thanks! I hope this will be available at some point :)
