### ISSUE TITLE
Stale cache in some nodes

### ISSUE THREAD

**Issue by ruralcoder** [finnhubio/Finnhub-API#21]
When I call the API call 

https://finnhub.io/api/v1/quote?symbol=MSFT&token=xxxx 

I see two responses one of which does not reflect the market price

```
{
  "c": 155.25,
  "h": 161.91,
  "l": 140.73,
  "o": 147.5,
  "pc": 139.06,
  "t": 1584072000
}
```

And the wrong one. When I refresh a couple of times it simply returns one or the other
```
  "c": 158.83,
  "h": 161.91,
  "l": 140.73,
  "o": 147.5,
  "pc": 139.06,
  "t": 1584072000
}
```

The timestamps are useless as they are always 1584072000

**Comment by ruralcoder** [comment]
OK, so I am seeing them in all my observed stocks.  Not just microsoft.

This is one Tesla, and you can see every other one is wrong...

<img width="189" alt="Screen Shot 2020-03-13 at 2 43 38 PM" src="https://user-images.githubusercontent.com/12993309/76661636-28c8a200-6539-11ea-9bad-b0854f718036.png">

**Comment by finnhubio** [comment]
Still trying to understand why it's wrong ? Giving the data and call it wrong doesn't help us understand and help you fix the issue.  Also plz read the documentation before commenting that "timestamp is useless". It's "Timestamp of current daily bar".

**Comment by ruralcoder** [comment]
When I was comparing to Robinhood, the price at the time was 155.25 and changing, which was true for one of your responses. But every other call I would get exactly the value of 158.83 which would never show up in Robinhood and always remain 158.83..

**Comment by ruralcoder** [comment]
I just noticed something. The value of 158.83 was the price at closing time. But that node was failing to update with AFTER-HOURS changes.

<img width="626" alt="Screen Shot 2020-03-14 at 7 01 12 AM" src="https://user-images.githubusercontent.com/12993309/76683485-a59f5e80-65c1-11ea-96f5-f9410bb40209.png">

While the other node was giving after-hours.

Right now, you API is always returning the closing price of 158.83
https://finnhub.io/api/v1/quote?symbol=MSFT&token=xxx

I think the price during after-hours is very valuable. Usually, it's the bloodbath hours. Right now Microsoft it's at 153.0 which was something your servers responded with until 6 hours ago.

**Comment by ruralcoder** [comment]
This is from my logs (though the seconds are not there)
So this started after 1 PM my time (pacific) so after 4 PM once the market was closed.

1:32 MSFT: Price changed: 153.20 <- after hours price (good)
1:32 MSFT: Price changed: 158.83 <- closing price (bad)
1:32 MSFT: Price changed: 153.53  <- after hours price (good)
1:32 MSFT: Price changed: 158.83  <- closing price (bad)
1:32 MSFT: Price changed: 153.75  <- after hours price (good)
1:32 MSFT: Price changed: 158.83  <- closing price (bad)
1:33 MSFT: Price changed: 153.54  <- after hours price (good)

**Comment by finnhubio** [comment]
Yes I understand the issue now. We will return return after-market hour consistently in the next update.
