### ISSUE TITLE
Multiple end-points are returning timeouts / 502 bad gateway

### ISSUE THREAD

**Issue by ravicheema** [finnhubio/Finnhub-API#210]
Date/time as of this report, multiple end-points are returning timeouts, multiple retries are needed to get a request to work. Note - These failure are not due to limits being exceeded.

Request - https://finnhub.io/api/v1/stock/profile?symbol=CAPC.L&token=
Returns - context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Expected - should not timeout

Request - https://finnhub.io/api/v1/stock/profile?symbol=CAPC.L&token= 
Returns - 502 Bad Gateway
Expected - should not return 502

Request - https://finnhub.io/api/v1/stock/candle?adjusted=false&from=1104537600&resolution=D&symbol=CAPE.L&to=1589114341&token=
Returns - context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Expected - should not timeout

Request https://finnhub.io/api/v1/stock/profile?symbol=CAT.L&token=
Returns - 401 Unauthorized
Expected - should not be unauthorised as token is valid

**Comment by jwadia** [comment]
Same issue on my end.

**Comment by finnhubio** [comment]
The issue has been resolved. Our apology for the outage. We had a huge spike in traffic this morning.
