### ISSUE TITLE
Some company profile 2 is missing

### ISSUE THREAD

**Issue by anogues** [finnhubio/Finnhub-API#211]
Hello.

Some of the companies I am tracking can't be found in the new endpoint. I can't see them neither with the symbol or the isin code

Anheuser-Busch InBev SA/NV (BUD)
British American Tobacco (BTI)
Total (TOT)

https://www.finnhub.io/api/v1/stock/profile2?symbol=BUD&token=xxxxx

Best,
Albert

**Comment by finnhubio** [comment]
They are ADRs share which we don't have automatic mapping to the underlying companies at this point. Plz use the symbol of its primary company instead.

**Comment by anogues** [comment]
Hi.

So do you mean i have to look for example, for Budweiser the ABI.BR symbol right?

I can find it then
https://www.finnhub.io/api/v1/stock/profile2?symbol=ABI.BR&token=

**Comment by finnhubio** [comment]
> Hi.
> 
> So do you mean i have to look for example, for Budweiser the ABI.BR symbol right?
> 
> I can find it then
> https://www.finnhub.io/api/v1/stock/profile2?symbol=ABI.BR&token=

Yes. We are working on automatic mapping for these cases. However, they are still work in progress at this point.
