### ISSUE TITLE
Hello, Does can provide 2/3/4 resolution? 

### ISSUE THREAD

**Issue by mdrh2048** [finnhubio/Finnhub-API#214]
## What is the issue ? Plz describe in details
we need 2/3/4 resolution data and we wanna know can be provide this data
is it in Ultimate option?

**Comment by finnhubio** [comment]
You mean 2/3/4 minute resolution ?

**Comment by mdrh2048** [comment]
2min / 3min / 4min yes right

**Comment by finnhubio** [comment]
We do not support it out of the box. However you can query 1 minute data and build 2/3/4 or any minute resolution data yourself.
