### ISSUE TITLE
No ASX quote/candle data

### ISSUE THREAD

**Issue by vbudovski** [finnhubio/Finnhub-API#215]
## What is the issue ? Plz describe in details

It appears that no data is returned for ASX listed stocks. It was working a few days ago. Candle endpoint returns "no_data". The quote endpoint just returns an empty JSON object.

## How to reproduce the error ?
https://finnhub.io/api/v1/stock/candle?symbol=CSL.AX&resolution=1&from=1572651390&to=1572910590&token=TOKEN
https://finnhub.io/api/v1/quote?symbol=CSL.AX&token=TOKEN

## What is the expected result and why do you think it's the correct result ?
Expected result is correct data for quote and candle endpoints for ASX listed stocks.

** The following cases will not be answered or deleted without warnings.
1. No reproducible example in the issue.
2. Compare data sources (We do not know how other companies prepare their data so we will not investigate these claims)
3. Being rude or use inappropriate language in the issue.

**Comment by finnhubio** [comment]
Hi, we are re-negotiating ASX CFD feeds at this point. It will be available again soon.
