### ISSUE TITLE
Unix Time when getting candles or local?

### ISSUE THREAD

**Issue by Brechard** [finnhubio/Finnhub-API#217]
## What is the issue ? Plz describe in details
When I get candles, using UNIX time it seems like I receive the 't' field on local time, or how should I treat it correctly?

## How to reproduce the error ?
from datetime import datetime, timezone
import requests

t = datetime.utcnow()
to = t.timestamp()
t_from = to - 61
url = f'https://finnhub.io/api/v1/stock/candle?symbol=AAPL&resolution=1&from={t_from}&to={to}&token={API_KEY}'
r = requests.get(url).json()

## What is the expected result and why do you think it's the correct result ?
when I do: print(t) I get:
    datetime.datetime(2020, 5, 12, 15, 56, 7, 288013)
but when I print datetime.utcfromtimestamp(r['t'][0]):
    datetime.datetime(2020, 5, 12, 13, 56)

I am in UTC +2 but I would expect that this is not reflected in the response, I am having the same issue with pd.to_datetime

**Comment by vbudovski** [comment]
Make sure you're using tz aware datetimes. See `datetime.now` and `datetime.fromtimestamp` instead.

**Comment by Brechard** [comment]
yeah but I want everything to be UNIX times so that it stays consistent through the whole pipeline and it does not matter if I am executing on my laptop or on a server in other regions.
also the time sent in the url has to be UNIX so it would mean having a mix of both

**Comment by vbudovski** [comment]
Right. So just make sure you set the tzinfo to UTC and it will be correct.

**Comment by Brechard** [comment]
well you could have been more specific and explain the problem tbh, I finally managed to find out that doing:
datetime.utcfromtimestamp(datetime.utcnow().timestamp())
gives different results than:
datetime.utcfromtimestamp(datetime.now(tz=timezone.utc).timestamp())
and using datetime.now(tz=timezone.utc) seems to do the trick and work
