### ISSUE TITLE
Candlesticks returning extra data

### ISSUE THREAD

**Issue by Z223I** [finnhubio/Finnhub-API#218]
Date:  5/12/2020

Replicate problem by using the URL:
https://finnhub.io/api/v1/stock/candle?symbol=AAPL&resolution=60&from=1577955600&to=1588406400&format=csv&token=<token>

This call is meant to return data starting from 1/2/2020.  However, it returns data starting from 11/4/2019.

**Comment by finnhubio** [comment]
This issue has been fixed. Thanks for reporting.
