### ISSUE TITLE
TSLA live data streaming with hickups

### ISSUE THREAD

**Issue by gravityctrl** [finnhubio/Finnhub-API#219]
## What is the issue?
Realtime trades for symbol `TSLA` using websocket connection are not consitently incoming:
`wss://ws.finnhub.io`

See example screenshot (Especially take a look at the `ping` responses where there are no trades in between):
![image](https://user-images.githubusercontent.com/34040477/81730594-106bf980-948e-11ea-972a-3dc5f5f7a3bb.png)

I backtested with the symbols `AAPL` and `MSFT` and they work just fine.

## How to reproduce the error ?

Use this javascript snippet, taken from the documentation:
```js
const socket = new WebSocket('wss://ws.finnhub.io?token=[insert token here]');

// Connection opened -> Subscribe
socket.addEventListener('open', function (event) {
    socket.send(JSON.stringify({'type':'subscribe', 'symbol': 'TSLA'}))
});

// Listen for messages
socket.addEventListener('message', function (event) {
    console.log('Message from server ', event.data);
});

// Unsubscribe
 var unsubscribe = function(symbol) {
    socket.send(JSON.stringify({'type':'unsubscribe','symbol': symbol}))
}
```

## What is the expected result and why do you think it's the correct result ?

A rate of incoming trades like in case of `AAPL`:
![image](https://user-images.githubusercontent.com/34040477/81730816-63de4780-948e-11ea-8294-afc556829da8.png)

Maybe I am pointing at the wrong stock exchange. If so, please let me know.

Thank you in advance
Sebastian

**Comment by finnhubio** [comment]
This is not an issue. You only receive trades when it happens on the exchange you have access to.

**Comment by gravityctrl** [comment]
Isn't `TSLA` the symbol for Tesla stocks traded at `NASDAQ`? Tesla stock trades are much more frequent on the `NASDAQ` exchange wherever I look at. I always thought that a ticker symbol uniquely identifies publicly traded shares of a particular stock on a particular stock market. So what am I missing?

Please help me understand, where I am lacking knowledge.
