### ISSUE TITLE
London exchange Stock price data missing at 12/3/2020

### ISSUE THREAD

**Issue by investorHK-developer** [finnhubio/Finnhub-API#22]
Hi,

At HK time, about 4:00 am 14/3/2020, I use the HTTP Request v1/stock/candle to get london stock. I find that there are about 2000 stock in London stock exchange which has missed the price data at 12/3/2020, why has such missing?

It make us hestiate to subscribe a paid plan as we find that there are usually missing price data in different exchange, e.g. Hong Kong/US/Taiwan

William

**Comment by finnhubio** [comment]
Can you provide a URL example ? I just tried:

[https://finnhub.io/api/v1/stock/candle?symbol=ABF.L&resolution=D&from=1583828065&to=1584173665&token=](https://finnhub.io/api/v1/stock/candle?symbol=ABF.L&resolution=D&from=1583828065&to=1584173665&token=) 

and I can see here 1584000000 is 12/3/2020 ?
