### ISSUE TITLE
Documentation - Economic Calendar - Responce attributes needs to be listed.

### ISSUE THREAD

**Issue by pranavKVP** [finnhubio/Finnhub-API#222]
## What is the issue ? Plz describe in details
Response attributes in Economic Calendar, not all attributes are listed. also Sample Response is incorrect.
## How to reproduce the error ?
Go to: https://finnhub.io/docs/api#economic-calendar
## What is the expected result and why do you think it's the correct result ?
```
economicCalendar
    result
    Array of Economic Events
        actual
        comment
        country
        currency
        date
        forecast
        id
        importance
        indicator
        link
        period
        previous
        scale
        source
        title
        unit
    status

```

**Comment by finnhubio** [comment]
We are working on a new calendar and will update the docs soon. Sorry about this but we are just too busy right now. Will get to it as soon as we can.

**Comment by finnhubio** [comment]
We updated the documentation for economic calendar
