### ISSUE TITLE
Stock profile requests keep returning 500 Internal Server Error

### ISSUE THREAD

**Issue by ravicheema** [finnhubio/Finnhub-API#223]
## What is the issue ? Plz describe in details

Various stock profile requests keep returning - 500 Internal Server Error

## How to reproduce the error ?

The following requests fail,

https://finnhub.io/api/v1/stock/profile?symbol=UNG&token=
https://finnhub.io/api/v1/stock/profile?symbol=GCC&token=
https://finnhub.io/api/v1/stock/profile?symbol=GLDM&token=
https://finnhub.io/api/v1/stock/profile?symbol=CEF&token=
https://finnhub.io/api/v1/stock/profile?symbol=ESBA&token=

## What is the expected result and why do you think it's the correct result ?

The above requests should complete successfully (provided limits have not been exceed)

**Comment by finnhubio** [comment]
The issue has been fixed. We were upgrading our symbol mapping. Those symbols are mostly ETF which we do not support profile anw.
