### ISSUE TITLE
SSLError / Band Handshake Error

### ISSUE THREAD

**Issue by kwame561** [finnhubio/Finnhub-API#224]
I received the following error using the Finnhub-API:

MaxRetryError: HTTPSConnectionPool(host='finnhub.io', port=443): Max retries exceeded with url: /api/v1/stock/profile2?symbol=TM&token={my token would go here} (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

This is the first time I'm receiving an error like this. I'm using the free API and I'm on a Windows machine. Any thoughts as to a possible cause?

**Comment by finnhubio** [comment]
This is the issue with SSL on your local machine. Plz check and fix it

**Comment by kwame561** [comment]
Ok, I used the `request` module in place of `urllib3`. Everything works now.
