### ISSUE TITLE
Add Payment date

### ISSUE THREAD

**Issue by cristipurdel** [finnhubio/Finnhub-API#229]
## What is the issue ? Plz describe in details
Add Ex-Dividend date to
https://finnhub.io/docs/api#stock-dividends

## How to reproduce the error ?
feature

## What is the expected result and why do you think it's the correct result ?
add also Ex-Dividend date field

**Comment by finnhubio** [comment]
The current date is ex-date

**Comment by cristipurdel** [comment]
Sorry, I meant to say payment date

**Comment by finnhubio** [comment]
We are already working on it. Will be available next week.

**Comment by finnhubio** [comment]
We released a new Dividend endpoint for common stocks
