### ISSUE TITLE
Missing symbols

### ISSUE THREAD

**Issue by legout** [finnhubio/Finnhub-API#231]
Hello,

following symbol is not available in the symbols list of the Stockholm Stock Exchange.
https://finnhub.io/api/v1/stock/symbol?exchange=ST

> SF.ST      Stillfront Group AB

However, I get data from all the endpoints by using this symbol. For example this works:

https://finnhub.io/api/v1/major-development?symbol=SF.ST
https://finnhub.io/api/v1/stock/earnings?symbol=SF.ST

Maybe this is true for other symbols too.

Regards,
legout

**Comment by finnhubio** [comment]
Thank you for reporting. We will add it asap.
