### ISSUE TITLE
Weight dividend limit issues

### ISSUE THREAD

**Issue by cristipurdel** [finnhubio/Finnhub-API#233]
## What is the issue ? Plz describe in details
Weight limit calculation

## How to reproduce the error ?
I am using around 10-15 dividend calls (from docs they have a weight of 10) smth like https://finnhub.io/api/v1/stock/dividend?symbol=ALB&from=2010-05-21&to=2021-05-18&token
and I am getting with an importjson UDF from googlesheets:
Error
Exception: Request failed for https://finnhub.io returned code 429. Truncated server response: API limit reached. Please try again later. (use muteHttpExceptions option to examine full response) (line 131).

## What is the expected result and why do you think it's the correct result ?
I have a free plan with 60 free API calls/minute
I was expecting based on https://finnhub.io/docs/api#rate-limit 
a 30 API calls/ second limit, basically I should be able to query 30 symbols / second with one free api key
So my questions are:
What is the query limit?
Could I query 30 stocks for dividends with a free api key?
Could I limit this query to once per day (since it is not real time)?

**Comment by finnhubio** [comment]
With a weight of 10, you can only make 6 requests a minute.

**Comment by cristipurdel** [comment]
Would it be possible to decrease the weight by reducing the interval.
E.g. weight 1 for last year or only next dividend?

**Comment by finnhubio** [comment]
That's not possible at this point unfortunately.
