### ISSUE TITLE
Euronext Stocks not found on Server Brussel and Amsterdam

### ISSUE THREAD

**Issue by jalberty2018** [finnhubio/Finnhub-API#236]
## What is the issue ?
Stocks information not found

## How to reproduce the error ?

curl -k -X GET \
https://finnhub.io/api/v1/stock/symbol?token=&exchange=BR

curl -k -X GET \
https://finnhub.io/api/v1/stock/symbol?token=&exchange=AS

## What is the expected result and why do you think it's the correct result ?

isin-code LU1598757687 
MT.AS
Euronext Amsterdam 
corporate.arcelormittal.com/investors

isin-code NL0011821202 
INGA.AS
Euronext Amsterdam 
www.ing.com

isin-code JE00B1VS3770 
PHAU.AS 
Euronext Amsterdam 
https://www.wisdomtree.eu/nl-be/products/ucits-etfs-unleveraged-etps/commodities/wisdomtree-physical-gold

isin-code BE0003470755 
SOLB.BR 
Euronext Brussels 
www.solvay-investors.com

isin-code NL0000288876
ECMPA.AS
Euronext Amsterdam
www.eurocommercialproperties.com/

**Comment by finnhubio** [comment]
Thank you for letting us know. We refreshed the list of symbols.
