### ISSUE TITLE
.AX (Australian Stock Exchange) data not available?

### ISSUE THREAD

**Issue by dacurrey** [finnhubio/Finnhub-API#237]
## What is the issue ? Plz describe in details
I am unable to download any data for .AX (Australian Stock Exchange)  Can could please advise if problem?
## How to reproduce the error ?
Have previously just used the standard calls as described from the documentation without any issues.
## What is the expected result and why do you think it's the correct result ?
I just get the "No Data" error now.

**Comment by finnhubio** [comment]
we do not support market data for ASX at this point. As there is more demand, we will add it in the future
