### ISSUE TITLE
Candle data- limited to 5k data points?

### ISSUE THREAD

**Issue by HowAlgorithmic** [finnhubio/Finnhub-API#24]
I remember you guys allowing up to 50k rows / data points per candle api call. Now it seems to be only 5k. Is this a bug or intended?

eg:
https://finnhub.io/api/v1/stock/candle?symbol=AAPL&resolution=1&from=0000000000&to=1572910590&token=

used to retrieve 50,000 price points of data, now it's either "no_data" or is limited to 5,000

**Comment by N1njaWTF** [comment]
Do you get 5k data points returned when doing this api call?

https://finnhub.io/api/v1/stock/candle?symbol=AAPL&resolution=60&count=5000&token=

**Comment by HowAlgorithmic** [comment]
> 
> 
> Do you get 5k data points returned when doing this api call?
> 
> https://finnhub.io/api/v1/stock/candle?symbol=AAPL&resolution=60&count=5000&token=

no, I get 136 from this

**Comment by N1njaWTF** [comment]
> > Do you get 5k data points returned when doing this api call?
> > https://finnhub.io/api/v1/stock/candle?symbol=AAPL&resolution=60&count=5000&token=
> 
> no, I get 137 from this.
> 2658 when I change resolution to =1

Yea same here... I think there are some bigger bugs going on right now..

**Comment by N1njaWTF** [comment]
I'm basically facing the same problem as you aswell..

for example:
https://finnhub.io/api/v1/stock/candle?symbol=APT&resolution=60&from=1580252400&to=1584140400&token=

Sometimes it randomly returns "no_data" or sometimes data from the date specified but with a huge gap of like 1 month and then the candledata from the "from" date specified..

**Comment by HowAlgorithmic** [comment]
There's definitely an issue with the time frames for pulling candle data. Was fine a week ago

**Comment by finnhubio** [comment]
This issue has been fixed. Please try again
