### ISSUE TITLE
Problems with daily price request - start date

### ISSUE THREAD

**Issue by jatorna** [finnhubio/Finnhub-API#240]
## What is the issue ? Plz describe in details
When I do a query for daily price data for some symbols is compulsory to indicate start date, if not, returns empty data 

## How to reproduce the error?
For example for the ticker ANA.MC, if ask for entire data returns empty. In some tickers, you must indicate the start date 

## What is the expected result and why do you think it's the correct result ?
Return all available data for a specific ticker without indicating the start query date

**Comment by finnhubio** [comment]
You need a start day and it's not advised to query a big range at a time. Plz do it iteratively.
