### ISSUE TITLE
Websocket Sample Program for Quote & TickbyTick Data

### ISSUE THREAD

**Issue by sujatha-gopi** [finnhubio/Finnhub-API#242]
Hi,

I am using below to get real-time quote, however I am getting error as "Url is invalid".  It would be helpful to sample program for WebSocket for real time quote and tick by tick data.

#https://pypi.org/project/websocket_client/
import websocket

def on_message(ws, message):
    print(message)

def on_error(ws, error):
    print(error)

def on_close(ws):
    print("### closed ###")

def on_open(ws):
    ws.send('{"type":"subscribe","symbol":"AAPL"}')
    #ws.send('{"type":"subscribe","symbol":"AMZN"}')
    #ws.send('{"type":"subscribe","symbol":"BINANCE:BTCUSDT"}')
    #ws.send('{"type":"subscribe","symbol":"IC MARKETS:1"}')

if __name__ == "__main__":
    websocket.enableTrace(True)
    #ws = websocket.WebSocketApp("wss://ws.finnhub.io?token=xxxxxxxxx",
    ws = websocket.WebSocketApp("wss://ws.finnhub.io/api/v1/quote?symbol=xxxxxxxxxxxxxxxx",
                              on_message = on_message,
                              on_error = on_error,
                              on_close = on_close)
    ws.on_open = on_open
    ws.run_forever()

**Comment by finnhubio** [comment]
You changed the URL:
#ws = websocket.WebSocketApp("wss://ws.finnhub.io?token=br3i3uvrh5rai6tgi2ig",
ws = websocket.WebSocketApp("wss://ws.finnhub.io/api/v1/quote?symbol=xxxxxxxxxxxxxxxx",

Plz fix it and try again.

**Comment by sujatha-gopi** [comment]
Thank you for quick reply.

How to include API key? so first pass API key and authenticate and query.

ws = websocket.WebSocketApp("wss://ws.finnhub.io?token=br3i3uvrh5rai6tgi2ig",
ws = websocket.WebSocketApp("wss://ws.finnhub.io/api/v1/quote?symbol=AAPL",

Do we need to include the below function as well?

def on_open(ws):
ws.send('{"type":"subscribe","symbol":"AAPL"}')

**Comment by sujatha-gopi** [comment]
The below is full code and still get same  error "URL is invalid"

#https://pypi.org/project/websocket_client/
import websocket

def on_message(ws, message):
    print(message)

def on_error(ws, error):
    print(error)

def on_close(ws):
    print("### closed ###")

def on_open(ws):
    ws.send('{"type":"subscribe","symbol":"AAPL"}')

if __name__ == "__main__":
    websocket.enableTrace(True)
    ws = websocket.WebSocketApp("wss://ws.finnhub.io/api/v1/quote?symbol=AAPL&token=xxxxxxxxxxx",
                              on_message = on_message,
                              on_error = on_error,
                              on_close = on_close)
    ws.on_open = on_open
    ws.run_forever()

**Comment by finnhubio** [comment]
Plz use our sample code as is. This is just a simple programming problem and you can seek help on developer's forum or from another engineers.

**Comment by sujatha-gopi** [comment]
Thank you.

I will do that can you remove API key from your reply.

**Comment by BARMIN-ROMAN** [comment]
@finnhubio How can I use this with WebSocket? Or is it impossible?
