### ISSUE TITLE
Missing Australian stock data.

### ISSUE THREAD

**Issue by asett0** [finnhubio/Finnhub-API#244]
Australian stock data appears to be missing despite the ASX being listed as one of the support exchanges.

In this URL: 
https://finnhub.io/api/v1/stock/exchange

Whilst this URL displays over 5000 stocks from the ASX: 
https://finnhub.io/api/v1/stock/symbol?exchange=AX&token=

However when I try to get, for example, candle data I receive no data: https://finnhub.io/api/v1/stock/candle?symbol=WPL.AX&resolution=D&from=946645200&to=1293714000&token=

Is Australia stock data supported by the API?

**Comment by asett0** [comment]
Also information regarding how to access supported exchanges and lists stocks from an exchange has been removed from the documentation. 

Why has this been done?

**Comment by finnhubio** [comment]
We do not support ASX data unfortunately.
