### ISSUE TITLE
Error 500 GET Quote via RapidApi

### ISSUE THREAD

**Issue by Jojado** [finnhubio/Finnhub-API#245]
GET Quote returns Error 500 no matter what stock I use. Here's how I'm accessing the endpoint:

https://finnhub-realtime-stock-price.p.rapidapi.com/quote
x-rapidapi-host = finnhub-realtime-stock-price.p.rapidapi.com
x-rapidapi-key = [PRIVATE]

Is this happening with anyone else? Let me know if you need more information.

**Comment by Jojado** [comment]
... and the parameter:

symbol = SU.TO

**Comment by finnhubio** [comment]
The issue should be fixed now
