### ISSUE TITLE
Response status 500

### ISSUE THREAD

**Issue by trugh16** [finnhubio/Finnhub-API#246]
## What is the issue ? Plz describe in details

I request candles using RapidAPI. It was working fine last week; but since yesterday the response is status 500.

## How to reproduce the error ?

url = "https://finnhub-realtime-stock-price.p.rapidapi.com/stock/candle"
querystring = {"to":1575243390,"symbol":'AAPL',"from":1572651390,"resolution":"15", "format":"csv"}
headers = {
'x-rapidapi-host': "finnhub-realtime-stock-price.p.rapidapi.com",
response = requests.request("GET", url, headers=headers, params=querystring)

## What is the expected result and why do you think it's the correct result ?

It should return the stock prices. It was working fine all week last week. Suddenly stopped working.

**Comment by finnhubio** [comment]
The issue should be fixed now.
