### ISSUE TITLE
Rate limited even with paid account

### ISSUE THREAD

**Issue by darshanbib** [finnhubio/Finnhub-API#247]
## What is the issue ? Plz describe in details
I just signed up tonight, first tried the API as a free user, then upgraded to the Basic plan (150 reqs/min).

## How to reproduce the error ?

I'm querying the API once every 1.5 seconds, yet I get rate limited after the first several requests.

## What is the expected result and why do you think it's the correct result ?

I expect to be able to call the API every 400ms and not be rate limited, because that's what the plan says.

**Comment by darshanbib** [comment]
```
url: 'https://finnhub.io/api/v1/stock/profile?symbol=ATGE&token=br4*******',
status: 429,
statusText: 'Too Many Requests',
```

**Comment by finnhubio** [comment]
Plz take a look at Weight limit: https://finnhub.io/docs/api#weight

**Comment by darshanbib** [comment]
Ok will try

**Comment by darshanbib** [comment]
Works, thanks!
