### ISSUE TITLE
'null' response for forex candles

### ISSUE THREAD

**Issue by garar** [finnhubio/Finnhub-API#249]
## What is the issue ? Plz describe in details

When you request data for: EURUSD from Forex.com I get null instead of any data.

Same goes for ICM Trader, IC Markets, Octa FX, FX Pig and Pepperstone.

FXCM returns empty response.

## How to reproduce the error ?

https://finnhub.io/api/v1/forex/candle?symbol=FXPIG%3A1&resolution=D&to=1609455599&from=1575154799&token=YOUR_TOKEN

## What is the expected result and why do you think it's the correct result ?

Correct candles with forex data.

**Comment by finnhubio** [comment]
Most forex brokers do maintenance over the weekend. you can try again now.
