### ISSUE TITLE
Not returning the amount of candles I am requesting?

### ISSUE THREAD

**Issue by N1njaWTF** [finnhubio/Finnhub-API#25]
Dear Finnhub

I just tried your free API and wanted to get the latest 5000 Candles for $BABA stock to build a chart.

I used following URL:
https://finnhub.io/api/v1/stock/candle?symbol=BABA&resolution=60&count=5000&token=

Now, it seems to only return around 150 candles, instead of the 5000 I requested.. Why is that? When I request 10k candles its even less... It never seems to return the amount I am asking for. Same for "from / to", it only gives me a few candles but not the ones i am requesting.. it also has a huge gap in missing dates then from today back a few days.

Other than that, I really like the API and wish it would be working as it should i guess. :)

**Comment by finnhubio** [comment]
"count" doesn't give you the number of candles. Plz read the docs here: https://finnhub.io/docs/api#stock-candles . Plz use from and to instead. "count" will be removed in the next version.

**Comment by N1njaWTF** [comment]
> "count" doesn't give you the number of candles. Plz read the docs here: https://finnhub.io/docs/api#stock-candles . Plz use from and to instead. "count" will be removed in the next version.

Sure thanks a lot.
However, when I use from & to, it doesn't seem to work properly aswell..

For example:
https://finnhub.io/api/v1/stock/candle?symbol=APT&resolution=60&from=1580252400&to=1584140400&token=

This returns Data from 28 January until 7 February and then Data is missing until 13 March... Do you know why it doesn't return full data from 28. January until today? i tried with multiple "to" dates and "from" dates..

**Comment by finnhubio** [comment]
This issue has been fixed
