### ISSUE TITLE
Forex rates API to support baseCurrency USD conversion 

### ISSUE THREAD

**Issue by jacko125** [finnhubio/Finnhub-API#250]
## What is the issue ? Plz describe in details
Could `https://finnhub.io/api/v1/forex/rates` API support base currency as a query param, ie, `https://finnhub.io/api/v1/forex/rates?base=USD` and return the list of quote currencies based on the base currency. 

https://finnhub.io/docs/api#forex-rates

Currently only supports `EUR` as base currency in response. 

## What is the expected result and why do you think it's the correct result ?

Sample Response 

```
{
  "base": "USD",
  "quote": {
    "AED": 3.968012,
    "AFN": 82.373308,
    "ALL": 124.235408,
    "AMD": 520.674275,
    "CAD": 1.525368,
    "CDF": 1904.576741,
    "CHF": 1.053259,
    "CNY": 7.675235,
    "COP": 4282.32676,
    "CRC": 614.796995,
    "CUC": 1.080304,
    "CUP": 28.628067,
    "CVE": 110.517004,
    "CZK": 27.096737,
    "DJF": 191.991344,
    "DKK": 7.461229,
    "DOP": 59.195018,
    "DZD": 139.384021,
    "EGP": 17.018597,
    "ERN": 16.204913,
    "ETB": 36.296767,
    "EUR": 0.989,
    "GBP": 0.874841,
    "JPY": 114.583548,
    "MDL": 19.120251,
    "MGA": 4105.156776,
    "USD": 1,
  }
}
```

**Comment by finnhubio** [comment]
We added this feature: https://finnhub.io/docs/api#forex-rates
