### ISSUE TITLE
Wrong market capitalization into result from /stock/profile2

### ISSUE THREAD

**Issue by dowhle** [finnhubio/Finnhub-API#251]
## What is the issue ? Plz describe in details
Wrong market capitalization into the result from `/stock/profile2` for **AAPL** (and many other companies)

## How to reproduce the error ?
Fetch data from `GET https://finnhub.io/api/v1/stock/profile2?symbol=AAPL`. Market capitalization in the result will be about $1,382,176

## What is the expected result and why do you think it's the correct result ?
Market capitalization of **AAPL** is about $1,380,000,000,000
https://www.google.com/search?q=NASDAQ:+AAPL

**Comment by finnhubio** [comment]
Market cap returned in profile2 is in million

**Comment by nazreen** [comment]
@finnhubio it seems like the figure is also outdated

e.g. AAPL = 1.58 Trillion,
but using Finnhub's Company Profile 2 = 1.49 Trillion
