### ISSUE TITLE
Jave an account but web sockets does not provide the stock price data

### ISSUE THREAD

**Issue by lennold** [finnhubio/Finnhub-API#252]
I purchased a basic account on FinnHub to test out our algos. However when I attempt to create a websocket for 90 NASDAQ stocks - the socket stops working and stalls. No data is coming even using the same code as provided in the documentation. It was previously working. Now has stopped completely. Works for socket subscription of - BINANCE:BTCUSDT etc .. but not for AAPL or AAL etc.

The account created is a Basic plan which should support - Websocket: 250 symbols. But it is not even providing data right now for even 1 stock symbol.

**Comment by finnhubio** [comment]
It's Memorial Day. The market is closed. Plz try again later

**Comment by lennold** [comment]
Thank u. Had the same problem on Friday too. But will wait till the next session.
