### ISSUE TITLE
Handshake status 524 Origin Time-out

### ISSUE THREAD

**Issue by Brechard** [finnhubio/Finnhub-API#255]
## What is the issue ? Plz describe in details
I am getting this error from the websocket and some days ago the connection was getting closed by itself at random moments

**Comment by oreneya** [comment]
Same here:
1. I get data w/o problems using requests
2. websocket works just fine with other urls
3. Hence - the problem is connecting to Finnhub servers via websocket

**Comment by oreneya** [comment]
Update: things got back to normal
