### ISSUE TITLE
error: [WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by Brechard** [finnhubio/Finnhub-API#256]
## What is the issue ? Plz describe in details
I keep getting this error meaning that the websocket has closed, at random times.

**Comment by finnhubio** [comment]
The server needs to close websocket so we can restart and apply new updates from time to time. Plz handle disconnection and reconnect accordingly.

**Comment by Kunderao** [comment]
" Plz handle disconnection and reconnect accordingly." 
How exactly is this disconnection handled in Go?
