### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by ludde127** [finnhubio/Finnhub-API#257]
I have been trying to request data from finnhub but when using requests for python request.text returns "Invalid API key" but when i go to the url in browser i see all the data. 

The code im using is:
 `url = f"https://finnhub.io/api/v1/stock/candle?symbol={sym}&resolution={res}&from={from_date}&to={to}&format=json&token={api_key}'"

r = requests.get(url)
    print(r.text)
    print(r.json())

`
What am i doing wrong?

**Comment by finnhubio** [comment]
Sorry we can't help you with programming problems. I can confirm that the system is working normally. Plz check your code.
