### ISSUE TITLE
Historical Data - Additional Trade Condition Details

### ISSUE THREAD

**Issue by rlshuhart** [finnhubio/Finnhub-API#262]
Hello, I've been enjoying the API and recently upgraded to Basic for Premium data. I was looking at the historical data for SPY and noticed outlier trades in the mix. There is usually a reason for these "outliers," however, given the columns timestamp, price, and volume there is no way to easily filter those out. From my limited understanding, every trade reported to the market has a flag, including normal trades. 

Would adding the trade condition flag (excuse me for not using the correct nomenclature) be a possibility or is it on the roadmap as an enhancement?  

## What is the issue? Plz describe in details
There are trades that appear reported late away from the prevailing market at the time, impacting the use of the raw data for backtesting or roll-your-own indicators. There is no flag to differentiate from normal trades. The work around would be to determine if each price is an outlier and that might be easy during low volatility, but becomes more difficult with high or sudden volatility.

## How to reproduce the ~~error~~ issue?
For SPY on 2020-05-28, there are a number of trades that fall outside the prevailing market at the time reported. There are 18 trades with the price 303.5437 that occur at timestamps across the day starting at 1590676673165 (9:37:53.165 AM EST) and ending 1590697005392 (3:16:45.392 PM EST). There are others as well like this.

## ~~What is the expected result and why do you think it's the correct result?~~ What would I like to see?

I would like to see an additional column for every trade with its trade condition flag.

**Comment by finnhubio** [comment]
Thank you for the feedback. I have forward your suggestion to the appropriate team. Should there is any new update, we will definitely let you know

**Comment by rlshuhart** [comment]
In the new API version for tick date excluding venue "D" seems to resolve the delayed print outliers.
