### ISSUE TITLE
Candles missing

### ISSUE THREAD

**Issue by michaelwalter5** [finnhubio/Finnhub-API#263]
Why does a candle request for a whole trading day with a resolution of 1 minute come back with only 20 candles? It should be around 480 candles.

https://www.finnhub.io/api/v1/stock/candle?symbol=NFC.DE&resolution=1&from=1590761862&to=1590866402
{
    c =     (
        "371.85",
        "371.5",
        "371.2",
        "371.65",
        373,
        373,
        "373.5",
        "373.45",
        "373.65",
        "374.05",
        "373.55",
        "373.85",
        "373.4",
        "373.05",
        "373.3",
        "373.85",
        "371.95",
        "372.3",
        "372.3",
        "372.85"
    );
    h =     (
        "371.85",
        "371.5",
        "371.2",
        372,
        373,
        373,
        "373.5",
        "373.45",
        "373.65",
        "374.05",
        "373.55",
        "373.85",
        "373.4",
        "373.05",
        "373.3",
        "373.85",
        "371.95",
        "372.3",
        "372.3",
        "372.85"
    );
    l =     (
        "371.85",
        "371.5",
        "371.2",
        "371.65",
        373,
        373,
        "373.5",
        "373.45",
        "373.65",
        "374.05",
        "373.55",
        "373.85",
        "373.4",
        "372.15",
        "373.3",
        "373.85",
        "371.95",
        "372.3",
        "372.3",
        "372.85"
    );
    o =     (
        "371.85",
        "371.5",
        "371.2",
        372,
        373,
        373,
        "373.5",
        "373.45",
        "373.65",
        "374.05",
        "373.55",
        "373.85",
        "373.4",
        "372.15",
        "373.3",
        "373.85",
        "371.95",
        "372.3",
        "372.3",
        "372.85"
    );
    s = ok;
    t =     (
        1590761880,
        1590762060,
        1590762120,
        1590762240,
        1590762360,
        1590762420,
        1590762480,
        1590762540,
        1590762660,
        1590762840,
        1590763320,
        1590763440,
        1590764160,
        1590764520,
        1590764940,
        1590765060,
        1590765900,
        1590765960,
        1590766020,
        1590766500
    );
    v =     (
        0,
        26,
        2,
        28,
        84,
        116,
        42,
        0,
        3904,
        46,
        32,
        47,
        86,
        177,
        70,
        10,
        34,
        70,
        120,
        111
    );
}

It should be around 480 candles.

**Comment by finnhubio** [comment]
Because you are requesting data over the weekend which doesn't exist. Plz check the from, to params
