### ISSUE TITLE
Add CUSIP to Company Profile 2 (free) API

### ISSUE THREAD

**Issue by Gen-CA** [finnhubio/Finnhub-API#264]
## What is the issue ? 
The 'Company Profile 2' API does not return the CUSIP identification number. 

## How to reproduce the error ?  
Simply call the 'Company Profile 2' API (https://finnhub.io/api/v1/stock/profile2?symbol=xxxx) with any symbol. The result returned includes interesting information such as the IPO date, but not the more important CUSIP identifier. 

## What is the expected result and why do you think it's the correct result ?  
Opinion/request:  The 'Company Profile 2' API should return the CUSIP identification number. 
Rationale:  The CUSIP is included in the original 'Company Profile' API that is now Premium-only so the data is readily available. The premium 'Company Profile' API provides info for more advanced analysis uses that presumably provides sufficient value to justify the subscription cost for users who need it. However, the CUSIP identification number is core identification information, not advanced profiling, so should be included in a basic profile. Some uses (for example, the 'Open Financial Exchange' standard (OFX; see https://www.ofx.net)) only support CUSIP, not symbols/tickers, as securities identifiers, so there is a need for a simple method to look up the CUSIP. This lookup only needs to be done once per security, so is not a high-volume or high-cost addition to the basic API.

**Comment by finnhubio** [comment]
Unfortunately this will not be supported in the free version.
