### ISSUE TITLE
Missing Income Statement (ic), Cash Flow (cf) from Financial As Report api

### ISSUE THREAD

**Issue by digicom1978** [finnhubio/Finnhub-API#268]
## What is the issue ? Plz describe in details
When API for Financials as reported (/stock/financials-reported) was called, reports of some years were missing like below.
Request   : https://finnhub.io/api/v1/stock/financials-reported?symbol=ACER&freq=annual&token=
Response : 
                 }, {
			'accessNumber': '0001564590-19-006779',
			'symbol': 'ACER',
			'cik': '1069308',
			'year': 2018,
			'quarter': 0,
			'form': '10-K',
			**'startDate': '2018-12-31 00:00:00',
			'endDate': '2018-12-31 00:00:00',**   <-- Assume this might be the reason
			'filedDate': '2019-03-07 00:00:00',
			'acceptedDate': '2019-03-07 16:11:31',
			'report': {
				'bs': {
					'Assets': 50663419,
					'Goodwill': 7647267,
					'Liabilities': 5580261,
					'AssetsCurrent': 42746305,
					'CommonStockValue': 1009,
					'StockholdersEquity': 45083158,
					'PreferredStockValue': 0,
					'OtherAssetsNoncurrent': 20380,
					'AccountsPayableCurrent': 1033829,
					'AccruedLiabilitiesCurrent': 4546432,
					'CommitmentsAndContingencies': 'N/A',
					'CommonStockSharesOutstanding': 10087363,
					'PropertyPlantAndEquipmentNet': 130867,
					'LiabilitiesAndStockholdersEquity': 50663419,
					'acer:ResearchDevelopmentInProcess': 118600,
					'AdditionalPaidInCapitalCommonStock': 91914692,
					'RetainedEarningsAccumulatedDeficit': -46832543,
					'PrepaidExpenseAndOtherAssetsCurrent': 1075021,
					'CashAndCashEquivalentsAtCarryingValue': 41671284
				},
				**'cf': {},  <-- Missing Cash Flow
				'ic': {}  <-- Missing Income Statement**
			}
		}, {

## How to reproduce the error ?
Call the url below and check the response json
https://finnhub.io/api/v1/stock/financials-reported?symbol=ACER&freq=annual&token=

## What is the expected result and why do you think it's the correct result ?
Like other years, that year (2018 in the example above) should include IC and CF.

Tested with several other symbols and all of the cases that have missing IC and CF have invalid start_date like above example.

**Comment by finnhubio** [comment]
The issue should be fixed now. Can you try again ?

**Comment by digicom1978** [comment]
The api call now gets the response as expected.

Grateful for the prompt reply.
