### ISSUE TITLE
Economic data (/economic?code) returning json error

### ISSUE THREAD

**Issue by gvanbavi** [finnhubio/Finnhub-API#27]
Hi Finnhub team,

I am trying to get economic data from that codes that are being returned from the /economic/code API call using /economic?code=MA-USA-USAJVAC

However it returns the following error:
json: error calling MarshalJSON for type controllers.JSONString: unexpected end of JSON input

Not sure if it depends on the subscription level, I am a basic paying member.

Best,

G

**Comment by dominhtri1995** [comment]
Looks like we do not have data for that economic data at the moment.

**Comment by finnhubio** [comment]
Data is not available for that economic indicator at the moment. Sorry about the issue.
