### ISSUE TITLE
Technical indicators for historic data not working

### ISSUE THREAD

**Issue by flexsankar** [finnhubio/Finnhub-API#270]
## What is the issue ? Plz describe in details

Technical indicators for historic data not working

## How to reproduce the error ?

Technical indicators for historic data was working till this morning. Not working now. Can you please look into it?

Example:

https://finnhub.io/api/v1/indicator?symbol=AAPL&resolution=5&from=1577975400&to=1577998740&indicator=sma&timeperiod=3&token=

Giving 504 error some times and no data response some times.

From: January 2, 2020 09:30:00 AM
to: January 2, 2020 3:59:00 PM

![image](https://user-images.githubusercontent.com/42661555/83439774-cc776f00-a411-11ea-9793-50a3d0acfb43.png)

**Comment by finnhubio** [comment]
Looks like error has been resolved
