### ISSUE TITLE
Constant disconnects on wesocket

### ISSUE THREAD

**Issue by alphasignal** [finnhubio/Finnhub-API#272]
I keep seeing frequent disconnects on websocket connection. From 14th May until 1st June I saw 150 socket disconnects, and this cannot be solely attributed to server upgrades. I always reconnect immediately but this sometimes tends to be a process which lasts anything from a few seconds and varies all the way up to a few minutes with the largest outage recorded being 579 seconds (nearly 10 minutes).
Do the disconnects depend on the type of plan you are as I am sure that if someone had a Professional or Enterprise plan these kind of outages and the frequency of disconnects would not be tolerated and the service would be pretty much dropped instantly.

Can someone please elaborate?

Thanks

**Comment by finnhubio** [comment]
Again, we need to apply new updates to our server so disconnect is to be expected. It will happen more often during the weekend or when the market closes. Plz reconnect in case of a disconnect. Your plan does not affect this.

Hope it helps.
