### ISSUE TITLE
Historical quotes

### ISSUE THREAD

**Issue by nisanfeigin** [finnhubio/Finnhub-API#275]
Is there an API which has historical quotes os stocks?

Thanks

**Comment by finnhubio** [comment]
Have you taken a look at https://finnhub.io/docs/api#stock-tick ?

**Comment by nisanfeigin** [comment]
Oh thanks i probably missed that because its premium. Thanks

Sent from Yahoo Mail on Android 
 
  On יום ו׳, יוני 5, 2020 at 3:16, finnhubio<notifications@github.com> wrote:   


Have you taken a look at https://finnhub.io/docs/api#stock-tick ?
