### ISSUE TITLE
SEC Filings Database Numbers are inaccurate

### ISSUE THREAD

**Issue by benbasuni1** [finnhubio/Finnhub-API#276]
https://www.kaggle.com/finnhub/sec-filings

Kaggle Notebook:
https://www.kaggle.com/kyubii/sec-filings

## What is the issue ? Plz describe in details
Look at below screenshot.

How are there only ~300 annual filings for the year of 2016 and above?

<img width="288" alt="Screen Shot 2020-06-05 at 1 20 48 PM" src="https://user-images.githubusercontent.com/13515027/83905454-b29a9c80-a72f-11ea-959f-87c526c88560.png">

## What is the expected result and why do you think it's the correct result ?
The expected result is to be above 300.

Based on Finnhub database, you are saying that in the entire Q1-Q4 annual report filings, there are 300 reports that were filed in each year of 2016 and above.

I did do a "dropna()" on the reports, so maybe it deleted a few, but if the total reports that can be used is only ~300 companies, then this database/api is useless.

**Comment by finnhubio** [comment]
Hi, 

Thank you for reporting. We missed a part of the database when exporting to Kaggle. The issue has been fixed. You can try again now.

Our apology for the inconvenience.

**Comment by benbasuni1** [comment]
Thank you @finnhubio.
How can I get more information in regards to career opportunities ?

**Comment by benbasuni1** [comment]
Possible to convert the JSON data into CSV? @finnhubio
