### ISSUE TITLE
Website login does not work

### ISSUE THREAD

**Issue by dschace** [finnhubio/Finnhub-API#278]

**Comment by dschace** [comment]
And now the entire site appears to be down

**Comment by dschace** [comment]
<img width="1617" alt="Screen Shot 2020-06-05 at 7 40 19 PM" src="https://user-images.githubusercontent.com/64915542/83931845-7e8d9e80-a764-11ea-93d1-3b210054497b.png">

**Comment by quantmoon** [comment]
Same happens. I guess is because they are updating the server or something like that. Perhaps in a couple of hours :(

**Comment by dschace** [comment]
@quantmoon  was there a posting about an update that I missed

**Comment by finnhubio** [comment]
No you didn't. It's our fault. 1 of our engineers forgot to make a post about the scheduled maintenance this weekend. I just posted it

**Comment by dschace** [comment]
@finnhubio  thank you for following up... definitely spent a few hours troubleshooting this haha

**Comment by finnhubio** [comment]
It should work now. We will be monitoring for another hour to make sure everything run smoothly.

**Comment by Koseng** [comment]
Registering new account on login does not work.

Always leads to:
Error - Network Error

**Comment by finnhubio** [comment]
> Registering new account on login does not work.
> 
> Always leads to:
> Error - Network Error

Plz try on another browser. I just created a new account and it's working fine

**Comment by KyleBurney** [comment]
@finnhubio I'm getting the same error when I try to register an account. I tried with Chrome and Edge but both had the same error.

**Comment by thrila** [comment]
hey , im trying  to register a new finnhub account but t keeps showing me the error `network error` ive tried multiple networks and the still gove me the same error  is account registration not allowed in some parts pf the world or is any current maintenace happening?
