### ISSUE TITLE
Can't upgrade my subscription, HTTP 402 on your website

### ISSUE THREAD

**Issue by 26medias** [finnhubio/Finnhub-API#282]
## What is the issue ?

I'm trying to upgrade my account (currently free)

When adding a card, a 402 error appears in the console. 

## How to reproduce the error ?

Add a Canadian debit card (TD)

## What is the expected result and why do you think it's the correct result ?

Being able to add a card to upgrade my account.

**Comment by finnhubio** [comment]
It looks like your card is declined by your bank. Plz try with another card that supports internet and international purchase.

If you need further assistance, plz email us at support@finnhub.io
