### ISSUE TITLE
Inaccurate historical intraday 15 minute candle

### ISSUE THREAD

**Issue by morissetteg** [finnhubio/Finnhub-API#284]
Currently subscribed to the basic plan. As per the plan description, subscribers have access to 10 years of OHLC data.

Downloaded intraday data (15 min OHLC candle) ranging from 2015 to end of May 2020

Realized when compiling the data that values before May 18th 2020 are off. 

For instance, MSFT closed at 135.98 on March 23rd 2020 but UNIX 1584993600 returns 135.1

These values are taken directly from raw CSV files (see attached PDF as GH doesn't accept CSV or XLSX)
[MSFT.US_15_1582405200_1590181200.pdf](https://github.com/finnhubio/Finnhub-API/files/4742676/MSFT.US_15_1582405200_1590181200.pdf)

Thank you for your help,

-Guillaume Morissette

**Comment by finnhubio** [comment]
Hi,

As per general guideline in the industry, tick included in intraday timeframe OHLC will be different from those included in the official Daily data. Hence, the closing price might not match between intraday and daily timeframe. Some providers choose to apply the same criteria of Daily to intraday bar which might looks good but it will exclude a lot of volume data.

Hope it helps.

**Comment by morissetteg** [comment]
Ok thank you for your answer. This should be mentioned upfront though.

**Comment by finnhubio** [comment]
> Ok thank you for your answer. This should be mentioned upfront though.

This is the general guideline of the industry. You can of course build your own OHLC data from tick if you wish to. Each provider usually has their own way of building OHLC data from tick so the result might vary from provider to provider. Only tick data stays the same.
