### ISSUE TITLE
Unable to retrieve historical data as I used to

### ISSUE THREAD

**Issue by RiSaMa** [finnhubio/Finnhub-API#287]
I was able to retrieve historical data with a different time frame (e.g. 1, 5, 60 minutes) month by month, but I am not able to do it since about a week ago. 

For instance, the below command should retrieve TSLA 5m time frame from 01/01/2011 to 31/01/2011, however "{"s":"no_data"}" is obtained.

`https://finnhub.io/api/v1/stock/candle?symbol=TSLA&resolution=5&from=1293840000&to=1296432000&token=<mytoken>`

Any idea what's happening?

Thank you

**Comment by finnhubio** [comment]
Hi, free plan is now limited to 1 year of intraday OHLC data. You can review the new access guideline here: https://finnhub.io/pricing

We have also sent out an email about this before the change
