### ISSUE TITLE
Earnings calendar API return no data

### ISSUE THREAD

**Issue by bkcollection** [finnhubio/Finnhub-API#288]
Earnings calendar API return no data even for AAPL, IBM or MSFT.
https://finnhub.io/api/v1/calendar/earnings?from=2019-01-01&to=2020-09-15&symbol=AAPL&token=xxxx

I have been trying for a few days and it is the same. Please let me know if you have plan to fix it.

**Comment by finnhubio** [comment]
Hi, free plan users only have access to 1 month of data on earnings calendar. You can review free plan access here: https://finnhub.io/pricing

**Comment by finnhubio** [comment]
We extended the Earnings Calendar for free tier to 1 year so it's consistent with Earnings surprises endpoint.

Hope this helps.
