### ISSUE TITLE
Data is not available for that economic indicator at the moment -> Economic codes returned have country duplicate

### ISSUE THREAD

**Issue by gvanbavi** [finnhubio/Finnhub-API#29]
Data is not available for that economic indicator at the moment. Sorry about the issue.

_Originally posted by @finnhubio in https://github.com/finnhubio/Finnhub-API/issues/27#issuecomment-599256496_

Hi,

My apologies to create a new issue with regards to the above closed issue. 

I think that the api call (/economic/code) returns the wrong codes, e.g.:
MA-USA-USAUNR

Removing the second country name returns data: MA-USA-UNR

Best,

G

**Comment by finnhubio** [comment]
Thanks for the heads up. We will fix it asap
