### ISSUE TITLE
52-week high is not correct (few days old)

### ISSUE THREAD

**Issue by Pbaboe** [finnhubio/Finnhub-API#290]
## What is the issue ? Plz describe in details

Following query : 
https://finnhub.io/api/v1/stock/metric?symbol=AAPL&metric=price&token=xxx

results (on 2020-06-13) in : 

"52WeekHigh":345.61,"52WeekHighDate":"2020-06-09"

There was a new high on 2020-06-10 though, seems the data return from /stock/metric is a few days old. Same is happening for MSFT for example.

## How to reproduce the error ?

https://finnhub.io/api/v1/stock/metric?symbol=AAPL&metric=price&token=xxx

## What is the expected result and why do you think it's the correct result ?

Expected result would be : 

"52WeekHigh":354.77,"52WeekHighDate":"2020-06-10"

https://finnhub.io/api/v1/stock/candle?symbol=AAPL&resolution=60&from=1591826400&to=1591830000&token=

gives : 

"h":[354.77,352.59]

**Comment by finnhubio** [comment]
Metrics are not updated in real-time at this point. We refreshed it as part of the routine update every few days.
