### ISSUE TITLE
Empty Object from companyProfile2 

### ISSUE THREAD

**Issue by me1k** [finnhubio/Finnhub-API#292]
## What is the issue ? Plz describe in details

I use the finnhub npm Module and the quote works totally fine. But when i want to get some profile informations from companyProfile2 i only receive an empty Object. 

```
app.get('/profile/:symbol', (req, res) => {
      console.log(req.params.symbol);
      api.companyProfile2('AAPL', (error, data, response) => {
        if (error) {
          console.error(error);
        } else {
          console.log(util.inspect(data, false, null, true));
          res.send(data);
        }
      });
    });
```
and even with the example code i receive empty object.
## How to reproduce the error ?

use example code from npm module https://www.npmjs.com/package/finnhub

## What is the expected result and why do you think it's the correct result ?

Expected result would be a object with company Informations from AAPL e.g

**Comment by finnhubio** [comment]
Plz check your code again. I just rerun our example and it is working fine.

**Comment by finnhubio** [comment]
```
const finnhub = require('finnhub');

const api_key = finnhub.ApiClient.instance.authentications['api_key'];
api_key.apiKey = "<api_key>" // Replace this
const finnhubClient = new finnhub.DefaultApi()

//Company profile2
finnhubClient.companyProfile2({'symbol': 'AAPL'}, (error, data, response) => {
    console.log(data)
});
```

This piece of code is working fine on our end.

**Comment by me1k** [comment]
Awesome! this works indeed! Didn't get it, that i have to use an object. Thank you for the fast response :)

**Comment by finnhubio** [comment]
You are welcome. It has to be an object because otherwise we wouldn't know whether you pass in a symbol, Isin or cusip. Glad I could help :)
