### ISSUE TITLE
Websocket sends tiny fraction of all trades

### ISSUE THREAD

**Issue by FreeGoldRush** [finnhubio/Finnhub-API#293]
When using the websocket we are receiving only a small fraction of all trades.  This is repeatable for any stock symbol we use.  For example, we get maybe 1% of all trades for TSLA.  Is this because we are using a free account?  Will I receive all trades if using a paid account?

Thanks!

**Comment by FreeGoldRush** [comment]
I have confirmed that Finnhub is only sending trades from the IEX exchange and only the ones IEX provides for free (orders routed to IEX are not provided).  Is this a limitation of the free account?  Why don't they tell us this on their website?  IEX handles about 2.5% of all US trades.

**Comment by finnhubio** [comment]
Hi there,

We are updating our documentation for websocket at the moment. We did mention it on the docs until 3-4 days ago. It will be on again once we are done with the documentation. We only support real-time trades from IEX via web socket. Full market tick data is available at the end of the day as mentioned here: https://finnhub.io/docs/api#stock-tick.

Hope it helps.

**Comment by finnhubio** [comment]
I have confirmation from our engineering team that we will prioritize to add back that information into websocket docs today. Feel free to reopen if you have any further questions
