### ISSUE TITLE
New tick data API change not working correctly

### ISSUE THREAD

**Issue by FreeGoldRush** [finnhubio/Finnhub-API#295]
## What is the issue ? Plz describe in details

When calling the new tick data API for a liquid stock like MSFT the number of lines returned is always 25000 regardless of the value of skip.

For example:

"https://www.finnhub.io/api/v1/stock/tick?symbol=MSFT&date=2020-06-17&token=[mytoken]&format=csv&skip=9999999"

The skip parameter is asking for results that are well past the available data, yet the number of lines returned is still 25000.  When doing the same call and getting results in json format the count value is 25000

## How to reproduce the error ?

"https://www.finnhub.io/api/v1/stock/tick?symbol=MSFT&date=2020-06-17&token=[mytoken]&format=csv&skip=9999999"

## What is the expected result and why do you think it's the correct result ?

Documentation states:  "count
Number of ticks returned. If count < limit, all data for that date has been returned."  The API will never return count < limit for a stock like MSFT.

Once all lines have been returned then incrementing skip by one should not produce 25000 more lines of data.  In the case of a csv response I expect it would produce a header only with no tick data.

**Comment by finnhubio** [comment]
Hi,

Thank you for reporting. We have fixed the issue. You can check again now.
