### ISSUE TITLE
Another bug with new tick data API

### ISSUE THREAD

**Issue by FreeGoldRush** [finnhubio/Finnhub-API#296]
## What is the issue ? Plz describe in details

25000 lines are returned when there are fewer than 25000 trades in a day

The returned csv data offers no way to determine when the last page has been reached.  In the case of a symbol that traded more than 25000 times in a day the API will continually return trade data when the skip parameter is increased.

## How to reproduce the error ?

https://www.finnhub.io/api/v1/stock/tick?symbol=CAN&date=2020-06-17&token=[mytoken]&format=csv&skip=0

It appears that after the last trade the API repeatedly returns this line: "0,0.0000,0,".  This repeats until a total of 25000 lines have been returned.  If there were more than 25000 trades in the day then all 25000 lines are filled with trade trade no matter what value is used for the skip parameter.  There is no way to determine when the end of data is reached.

## What is the expected result and why do you think it's the correct result ?

The csv response needs a way to determine when the end of data is reached.

This stock traded fewer than 25000 times on 2020-06-17.  I expect to see only data for each trade.  If the stock traded fewer than 25000 times then the csv response should contain fewer than 25000 lines.  If the skip number is increased past the last page of data then I expect to see a response with the header line only and no trade data.

**Comment by finnhubio** [comment]
Thank you for reporting. We have fixed the issue. You can check again now.
