### ISSUE TITLE
New Tick API Dropping Ticks?

### ISSUE THREAD

**Issue by fhenslee** [finnhubio/Finnhub-API#297]
## What is the issue ? Plz describe in details
The new tick API seems to be dropping ticks. For a very liquid ETF VTI, there are no ticks recorded from 8:00 to 11:00 on 11 June 2020. Total number of ticks returned is about 90K and I recall there being much more than this.

## How to reproduce the error ?
https://finnhub.io/api/v1/stock/tick?symbol=VTI&date=2020-06-11&limit=25000&skip=0&format=csv&token=token
https://finnhub.io/api/v1/stock/tick?symbol=VTI&date=2020-06-11&limit=25000&skip=25000&format=csv&token=token
https://finnhub.io/api/v1/stock/tick?symbol=VTI&date=2020-06-11&limit=25000&skip=50000&format=csv&token=token
https://finnhub.io/api/v1/stock/tick?symbol=VTI&date=2020-06-11&limit=25000&skip=75000&format=csv&token=token

## What is the expected result and why do you think it's the correct result ?
Comparing with daily bars from another source, total share volume is expected to be ~12.5M. Using the above requests, only getting ~8.4M.

**Comment by finnhubio** [comment]
Can you double check again ? I see thousands of ticks during 8 and 11 .

**Comment by fhenslee** [comment]
Below are the number of ticks I'm seeing by hour for VTI on 2020-06-11.

<img width="273" alt="image" src="https://user-images.githubusercontent.com/30094966/85213503-1d44fe00-b314-11ea-8bda-c21f53ab5e63.png">

**Comment by fhenslee** [comment]
Solved by feature request of #298. Also neglected to understand times are UTC and not US/Eastern.
