### ISSUE TITLE
Desync'd (4h) timestamps - values pairs for GET/candles and GET/indicator

### ISSUE THREAD

**Issue by vladcvoinescu** [finnhubio/Finnhub-API#299]
## What is the issue ? Plz describe in details
The timestamps that I get from finnhub's API on both candles and technical indicator endpoints are desync'd by 4 hours. It is not a timezone issue on my side. I suspect it is on yours.

## How to reproduce the error ?
`https://finnhub.io/api/v1/crypto/candle?symbol=AAPL&resolution=1&from=1592596200&to=1592596800` - this returns 11 candles that should represent the time frame **19.06.2020 22:50-23:00 (UTC+3)**. However, the values of the candles represent the time frame **19.06.2020 18:50-19:00 (UTC+3)**.

This is how the **finnhub** candles look like:
![finnhub AAPL 1min 19june2250-2300](https://user-images.githubusercontent.com/9292524/85228403-f823be80-b3eb-11ea-86c7-a60e5f5bdc08.png)

This is how the **trading view** candles look like for the corrected time frame **19.06.2020 18:50-19:00 (UTC+3)** - almost identical:
![tradingView AAPL 1min 19june1850-1900](https://user-images.githubusercontent.com/9292524/85228428-18537d80-b3ec-11ea-8a4e-7b5444f61d63.png)

This is how the **trading view** candles look like for the time frame that was requested from finnhub - **completely different**:
![tradingView AAPL 1min 19june2250-2300](https://user-images.githubusercontent.com/9292524/85228457-2e613e00-b3ec-11ea-8cfb-387624a24ead.png)

## What is the expected result and why do you think it's the correct result ?
Expected result is that I get correct timestamp - values pairs from the finnhub API, not desync'd by 4 hours.

**Comment by finnhubio** [comment]
There is nothing wrong with the result returned. Please double check your code

**Comment by vladcvoinescu** [comment]
That's the same result that I get, however I do not agree with this:
_which correctly represents data in the range 19.06.2020 22:50-23:00 (UTC+3)_

A simple visit to trading view - AAPL - 1min - 19.06.20 22:50-23:00 (UTC+3) and it can be seen that the result we both get has closes of 353, however on the trading view website, they only have closes of 349 on those 22:50-23:00 candles.

**Comment by finnhubio** [comment]
I understand now. I agree this is a bug with the current OHLC data for some symbols. Our engineers are working on it. Should be fixed this weekend.

**Comment by finnhubio** [comment]
The issue should be fixed now
