### ISSUE TITLE
Survivorship bias

### ISSUE THREAD

**Issue by emisaacson** [finnhubio/Finnhub-API#30]
Hi Finnhub team.

Thanks for creating a great product.

I was noticing survivorship bias in the historical data (only currently listed tickers can be pulled historically). I found in another issue (https://github.com/finnhubio/Finnhub-API/issues/9) that this data will be added "soon". Can you give some more details about an estimated timeline for this to roll out? I would like to sign up for a paid account for some work I am doing but would need a survivorship-free dataset to work with.

Thanks

**Comment by finnhubio** [comment]
We are working on it. However, we don't have a clear timeline at the moment.

**Comment by emisaacson** [comment]
Thanks, I appreciate your response
