### ISSUE TITLE
Unannounced API changes

### ISSUE THREAD

**Issue by tchklovski** [finnhubio/Finnhub-API#300]
## What is the issue ? Plz describe in details
`stock/exchange` endpoint seems to be gone, both from docs and in operation. With no announcement.

Ticks appear to have gained new column, "venue" in csv. No documentation of what venue
codes mean or what their exhaustive list is.

## How to reproduce the error ?
curl -i https://finnhub.io/api/v1/stock/exchange\?token\=$FINNHUB_API_KEY

## What is the expected result and why do you think it's the correct result ?
used to give list of exchanges, now redirects to front page.

I'm all for moving fast, but, for the sake of your business, I urge you to:
- keep apis running and provide deprecation notices when you turn behavior off
- use the versioning you have -- keep v1 doing what it was doing.
- when something goes away, make sure it is not replaced with a redirect to front page -- please use HTTP response codes properly.

by the time you start charging customers several hundred dollars/mo, this API has to be out of "pre-alpha". You're currently charging for something that does not work.

- Don't use github issues as announcements. You only have one item tagged "API change".
- Have regression testing to test your own APIs, and a health dashboard, so the fact that the v1 api is broken is discovered by your automated testing, not by your (again, paying) users.

Thanks, hope you take these suggestions to heart.

**Comment by finnhubio** [comment]
Thank you for the feedback. I have forwarded your post to the appropriate team for review.

**Comment by ioanwurf** [comment]
Got bitten by this as well. I would really appreciate any update about this issue.

**Comment by tchklovski** [comment]
nearly 3 days without a reply beyond "I have forwarded your post to the appropriate team for review." Look forward to a resolution.

**Comment by finnhubio** [comment]
Hi, you guys can still access that data here : https://finnhub.io/docs/api#stock-symbols

**Comment by tchklovski** [comment]
Respectfully, your response does not address improving the service going forward.
could you commit to:
1. announcing API changes in advance
2. using the HTTP response codes when api changes
3. using api versioning (v1 in url vs eg v1.1 or v2)

**Comment by finnhubio** [comment]
> Respectfully, your response does not address improving the service going forward.
> could you commit to:
> 
> 1. announcing API changes in advance
> 2. using the HTTP response codes when api changes
> 3. using api versioning (v1 in url vs eg v1.1 or v2)

Absolutely. We needed to drop the exchange endpoint to stop the some malicious attempt to abuse our system. Should any new endpoints come out, we will use versioning. We will also alert via email at least 5 days in advance in case of API deprecation. 

p/s: We missed the announcement for exchange endpoint deprecation in the previous email. Again, our apology for the miscommunication.

**Comment by tchklovski** [comment]
sounds good, thank you!

I will say it's difficult to see how dropping the exchange endpoint could possibly truly "stop some malicious attempts to abuse our system" -- if someone was requesting it too much, could not they trivially switch to any other endpoint? and it seems like the exchange is the lowest cost to respond endpoint in the whole API...

but anyhow, thanks again for committing to better deprecation practices.

I will also point out that launching _new_ endpoints requires less pre announcement or even versioning... it's only when you break the contract of the v1 (or whichever) version that versioning is particularly important.

**Comment by finnhubio** [comment]
> sounds good, thank you!
> 
> I will say it's difficult to see how dropping the exchange endpoint could possibly truly "stop some malicious attempts to abuse our system" -- if someone was requesting it too much, could not they trivially switch to any other endpoint? and it seems like the exchange is the lowest cost to respond endpoint in the whole API...
> 
> but anyhow, thanks again for committing to better deprecation practices.
> 
> I will also point out that launching _new_ endpoints requires less pre announcement or even versioning... it's only when you break the contract of the v1 (or whichever) version that versioning is particularly important.

We definitely understand your points here. Unfortunately we can't go into more details regarding this security issue. We are committed to make the API easier and more reliable to use. Appreciate your feedback !

**Comment by finnhubio** [comment]
Here is the list of support exchanges for tick data: https://docs.google.com/spreadsheets/d/1Tj53M1svmr-hfEtbk6_NpVR1yAyGLMaH6ByYU6CG0ZY/edit?usp=sharing .
