### ISSUE TITLE
API token should be accepted as a header, not a query parameter.

### ISSUE THREAD

**Issue by TJNII** [finnhubio/Finnhub-API#301]
Good evening:

This is a feature request.

Currently the user's API key is passed through as a query parameter.  This is a security concern as passing the token as a query parameter makes it part of the URL, which is frequently logged by application level logging but also commonly logged by proxies.  This practice is now discouraged as a security risk: https://stoplight.io/blog/api-keys-best-practices-to-authenticate-apis/#query-string

An easy improvement would be to also accept the token as a HTTP header, for example ```X-FINNHUB-TOKEN```.  This is a fairly common and easy to implement solution that resolves the query-parameter related security concerns and allows an easy migration path for users.  I have seen companies migrate their API authentication tokens from query parameters to HTTP headers with minimal pain.

Currently this is not a major issue as the API is largely read only, and the risk of token loss is largely limited to unauthorized consumption of API quotas.  However this will be more of a problem as your API functionality grows.  This is something that security teams look for when auditing vendors so I recommend changing this early before it causes code audit & security compliance problems for customers.  Thanks.

**Comment by finnhubio** [comment]
Thank you for the feedback. We will look into it

**Comment by finnhubio** [comment]
We added support for this feature. You can checkout our docs here: https://finnhub.io/docs/api#authentication

**Comment by TJNII** [comment]
Working great!  Thanks for the quick turnaround!
