### ISSUE TITLE
Stock exchanges list not available anymore 

### ISSUE THREAD

**Issue by LoannData** [finnhubio/Finnhub-API#302]
Before it was possible to get the list of stock exchanges from the command : 

[https://finnhub.io/api/v1/stock/exchange?token=bq8qg1frh5rc96c0ke80](https://finnhub.io/api/v1/stock/exchange?token=bq8qg1frh5rc96c0ke80)

exactly like for the forex exchanges : [https://finnhub.io/api/v1/forex/exchange?token=bq8qg1frh5rc96c0ke80](https://finnhub.io/api/v1/forex/exchange?token=bq8qg1frh5rc96c0ke80) 

It is not available anymore. Why ? And how to get it from a web request ?

**Comment by finnhubio** [comment]
You can obtain that information here: https://finnhub.io/docs/api#stock-symbols .

Hope it helps
