### ISSUE TITLE
No data response from stock candle api

### ISSUE THREAD

**Issue by ycczkl** [finnhubio/Finnhub-API#303]
the api returns 'no_data' response from https://finnhub.io/api/v1/stock/candle?symbol=MMC&resolution=D&from=1582693765&to=1593061765

Most symbols works fine with this api(returns valid data), but some of them will return 'no_data'. The other symbols I found are: nvr, ppg, ppl, pg.

This issue occurs since 24/07, can you take a look and let me know what's going wrong here?

**Comment by finnhubio** [comment]
The issue should be fixed now. We just had a spike in traffic. Can you please try again ?

**Comment by ycczkl** [comment]
Sometimes i need to call twice to get the real data. Maybe related with api cache? I think we can mark this issue as closed
