### ISSUE TITLE
how to convert finnhub_client.stock_candles returns to pandas Dataframe?

### ISSUE THREAD

**Issue by wukong7788** [finnhubio/Finnhub-API#304]
## What is the issue ? Plz describe in details
when I using your api finnhub_client.stock_candles, it returns <class 'finnhub.models.stock_candles.StockCandles'>
## How to reproduce the error ?
data = finnhub_client.stock_candles('AAPL', 'D', date_str_timestamp('2020-01-01'), date_str_timestamp('2020-06-01'))
print(type(data))
print(data)
df = pd.DataFrame.from_dict(data)
print(df)
File "C:/Users/xx/Documents/us-stocks/finnhub_api.py", line 30, in <module>
    df = pd.DataFrame.from_dict(data)
  File "C:\Users\xx\anaconda3\envs\py37\lib\site-packages\pandas\core\frame.py", line 1247, in from_dict
    return cls(data, index=index, columns=columns, dtype=dtype)
  File "C:\Users\xx\anaconda3\envs\py37\lib\site-packages\pandas\core\frame.py", line 509, in __init__
    raise ValueError("DataFrame constructor not properly called!")
ValueError: DataFrame constructor not properly called!
## What is the expected result and why do you think it's the correct result ?
how can I get dict-like returns?or How to convert it to Dataframe?

**Comment by finnhubio** [comment]
Can you plz try data.to_dict() ?

**Comment by finnhubio** [comment]
Please upgrade the library to 2.0. You should be able to do it easily. Examples can be found in README
