### ISSUE TITLE
There is no data where must be

### ISSUE THREAD

**Issue by git-farid** [finnhubio/Finnhub-API#305]
## What is the issue ? Plz describe in details

There is no data in Comcast Corporation (CMCSA) ,acoording to my downloads you can find data since 2020-04-30

https://tick.finnhub.io/api/v1/stock/tick?symbol=CMCSA&date=2020-04-30&token=brq1mffrh5rce41ggt40&limit=24000&skip=0&format=json

(Probably the same error could be in others...)

## How to reproduce the error ?

https://finnhub.io/api/v1/stock/candle?symbol=CMCSA&resolution=1&from=1572651390&to=1572910590&token=brq1mffrh5rce41ggt40

take the timestamp and go to https://www.epochconverter.com/

convert it...

from:
https://tick.finnhub.io/api/v1/stock/tick?symbol=CMCSA&date=2019-11-01&token=brq1mffrh5rce41ggt40&limit=24000&skip=0&format=json

to:
https://tick.finnhub.io/api/v1/stock/tick?symbol=CMCSA&date=2019-11-04&token=brq1mffrh5rce41ggt40&limit=24000&skip=0&format=json

or combrube the days when the stock has activity in yahoo...

https://finance.yahoo.com/quote/CMCSA/history?p=CMCSA

and use some date... before :   
https://tick.finnhub.io/api/v1/stock/tick?symbol=CMCSA&date=2020-04-30&token=brq1mffrh5rce41ggt40&limit=24000&skip=0&format=json

## What is the expected result and why do you think it's the correct result ?

Well , there should be data according to the Yahoo calendar... or the candles links from finnhub

**Comment by finnhubio** [comment]
Please open a new issue. You are exposing your API key publicly in this post. Please generate a new api key immediately.
