### ISSUE TITLE
ISINs / other profile data for ETFs

### ISSUE THREAD

**Issue by jacobparish** [finnhubio/Finnhub-API#306]
In #43 it's mentioned that you only support ISINs for common shares. Is this still the case? If so there any update on when we might be able to get ISINs (+ other profile data) for ETFs, or is that not in the works?

Thanks.

**Comment by finnhubio** [comment]
Hi Jacob, that data is currently reserved for Enterprise clients only. We do not have any plans to change it at this point unfortunately.
