### ISSUE TITLE
Your data is OLD and does not reflect the market prices

### ISSUE THREAD

**Issue by ruralcoder** [finnhubio/Finnhub-API#31]
<img width="797" alt="Screen Shot 2020-03-17 at 9 56 38 AM" src="https://user-images.githubusercontent.com/12993309/76881186-0505a480-6836-11ea-9016-d848d0f2c26c.png">

And even though your High24 hours changes, the price fails to update

<img width="439" alt="Screen Shot 2020-03-17 at 9 58 18 AM" src="https://user-images.githubusercontent.com/12993309/76881100-e1daf500-6835-11ea-8386-03f6cce91bef.png">

**Comment by ruralcoder** [comment]
Thank you. Whatever you guys did, I now see updates

<img width="395" alt="Screen Shot 2020-03-17 at 10 35 30 AM" src="https://user-images.githubusercontent.com/12993309/76884517-0c7b7c80-683b-11ea-8e23-6c9aabc5c3fa.png">

**Comment by finnhubio** [comment]
yeah we are looking into the issue with Quote endpoint. WebSocket real-time price is fine. You can try to subscribe to the socket instead if you will be polling the price a lot.

**Comment by ruralcoder** [comment]
Thank you...I am polling 1/min and for more important stocks once every 5sec
