### ISSUE TITLE
totalRatio in stock/metric request. FeatureRequest

### ISSUE THREAD

**Issue by goodarmen96** [finnhubio/Finnhub-API#310]
Hi, Finnhub. I wanna request a new feature

Now in stock/metric request has field currentRatio (annual/quarterly) which computed as
CurrentRatio = CurrentAsssets / CurrentLiabilities

I'm very need metric like "totalRatio" which will computed as
TotalRatio = TotalAsssets / TotalLiabilities

Where:
Total Assets = Current Assets + Non-current Assets
Total Liabilities = Current Liabilities + Non-current Liabilities

For example Balance sheet for Apple (AAPL) in Yahoo
https://finance.yahoo.com/quote/AAPL/balance-sheet?p=AAPL

Thanks for your attention

**Comment by finnhubio** [comment]
We added this data point : https://finnhub.io/docs/api#company-basic-financials

**Comment by goodarmen96** [comment]
Perfect!
