### ISSUE TITLE
Recommendation trend endpoint is returning data from a different symbol than requested 

### ISSUE THREAD

**Issue by nick-gaudreau** [finnhubio/Finnhub-API#314]
This endpoint does not return the response for the symbol requested:

example: https://finnhub.io/api/v1/stock/recommendation?symbol=**AUY**&token=
Return an array of data for a completely different symbol **YRI.TO**

Another issue: if you request an **NYSE symbol**:  https://finnhub.io/api/v1/stock/recommendation?symbol=**ACST**&token=
where **ACST** is a NYSE exchange,  it returns data for another exchange **ACST.V** which is in the Toronto Venture Exchange

**Comment by finnhubio** [comment]
We are mapping the symbol for fundamental data to its Primary symbol in case 1 company is listed on multiple exchanges, which is the case here.

**Comment by nick-gaudreau** [comment]
Thx for the reply on this
