### ISSUE TITLE
HTTP 500 Error on indicator API

### ISSUE THREAD

**Issue by Unberath** [finnhubio/Finnhub-API#319]
## What is the issue ? Plz describe in details
Calling the indicator API for some indicators (e.g. stoch, stochf) results in an error 500.
## How to reproduce the error ?
Call the API endpoint:
`https://finnhub.io/api/v1/indicator?symbol=AAPL&resolution=D&from=1594222858&to=1594654858&indicator=stoch&token=<your-token>`
## What is the expected result and why do you think it's the correct result ?
API should return the corresponding indicator values or hande the error properly.

**Comment by finnhubio** [comment]
Looks like you are not requesting enough data for Indicator calculation. Try this: https://finnhub.io/api/v1/indicator?symbol=AAPL&resolution=D&from=1584222858&to=1594654858&indicator=stoch&token=

**Comment by Unberath** [comment]
Thanks, makes sense.
I think it would be great if the response could provide a meaningful error message.

**Comment by finnhubio** [comment]
> Thanks, makes sense.
> I think it would be great if the response could provide a meaningful error message.

I agree. We will add this in the next release
