### ISSUE TITLE
When requesting candles in CSV file, the coloumns are not always in the format t, o, h, l, c, v as it used to be but tends to change. Is there something wrong?

### ISSUE THREAD

**Issue by Mitstronic** [finnhubio/Finnhub-API#32]

**Comment by dominhtri1995** [comment]
plz provide a reproducible example

**Comment by finnhubio** [comment]
Please follow our guideline when asking a new question. Can you provide a reproducible example so I can help you debug the issue ?

**Comment by Mitstronic** [comment]
https://finnhub.io/api/v1/stock/candle?symbol=ASML&resolution=1&from=1483228800&to=1485907199&format=csv&token=bpj9olfrh5rbrf4ncv50

https://finnhub.io/api/v1/stock/candle?symbol=ASML&resolution=1&from=1485907200&to=1488326399&format=csv&token=bpj9olfrh5rbrf4ncv50

these are two examples which does not follow the t, o, h, l, c, v

**Comment by finnhubio** [comment]
I see. We will change it asap. For now, plz use the header to extract the data.

**Comment by Mitstronic** [comment]
Thanks

**Comment by Mitstronic** [comment]
Are there any updates on this?

**Comment by dominhtri1995** [comment]
will be fixed tonight after the market closes

**Comment by finnhubio** [comment]
> Are there any updates on this?

It will be fixed after the market closes today

**Comment by finnhubio** [comment]
The problem has been fixed. Feel free to comment if you still encounter the issue.
