### ISSUE TITLE
Hourly Macd values

### ISSUE THREAD

**Issue by millionarecoin** [finnhubio/Finnhub-API#320]
## What is the issue ? 
I am trying to retrieve hourly macd values and getting an error

'https://finnhub.io/api/v1/indicator?' + 'symbol=' + ticker + '&resolution=60&from=' + from_time + '&to=' + to_time + '&indicator=macd&timeperiod=9&token=' + token

What should the value for timeperiod be, since I just want today's data. Same code works for the following modification when resolution is changed to 30:

'https://finnhub.io/api/v1/indicator?' + 'symbol=' + ticker + '&resolution=30&from=' + from_time + '&to=' + to_time + '&indicator=macd&timeperiod=9&token=' + token

![hourly_macd_error](https://user-images.githubusercontent.com/40475750/87378473-dab1c280-c55b-11ea-839f-851bd34f95ec.JPG)

## What is the expected result and why do you think it's the correct result ?
I need to get last 5 hourly macd values which I am unable to. I am able to get daily and 30m values though.

**Comment by finnhubio** [comment]
Looks like you need to expand the "from" and "to" range so that we have enough data for the indicator calculation.
