### ISSUE TITLE
Acceptable timeperiod values

### ISSUE THREAD

**Issue by millionarecoin** [finnhubio/Finnhub-API#321]
## How to reproduce the error ? get_url = 'https://finnhub.io/api/v1/indicator?' + 'symbol=' + ticker + '&resolution=30&from=' + from_time + '&to=' + to_time + '&indicator=macd&timeperiod=9&token=' + token

What should timeperiod value be when resolution is set to 60, 15, D, 30 etc.

**Comment by finnhubio** [comment]
This is technical analysis knowledge. please google MACD to learn more.
