### ISSUE TITLE
Mutual Fund symbols stopped working.

### ISSUE THREAD

**Issue by f00dl3** [finnhubio/Finnhub-API#323]
I set up the FinnHub.io API to pull feeds for mutual fund symbols, such as AFMBX, AMECX, FFFHX, etc.... but it seems that as of yesterday evening all my Mutual fund symbols are now returning "Symbol not supported" https://finnhub.io/api/v1/quote?symbol=FFFHX&token= --- is this a change that went in Friday or was it never supposed to work? MarketHub has the data - https://www.marketwatch.com/investing/fund/amecx

**Comment by finnhubio** [comment]
Mutual fund data will be available again in a new pricing package. We are working on it.
