### ISSUE TITLE
intraday historical data is missing timestamps through out  the day

### ISSUE THREAD

**Issue by zohargolan** [finnhubio/Finnhub-API#324]
## What is the issue ? Plz describe in details
Intraday data is missing in random locations for random stocks

## How to reproduce the error ?
use the following script

from api.finnhubClient import createClient

client = createClient()
res = client.stock_candles('TWLO', 1, 1577975400, 1577998800)

dictResponse = res.to_dict()
timeStamps = dictResponse['t']

for index in range(1,len(timeStamps)):
    if timeStamps[index] - timeStamps[index - 1] != 60:
        print(timeStamps[index - 1], timeStamps[index])

print(timeStamps)

This script is only taking one day worth of 1 minute interval for stock "TWLO" on January 2 2020 (other dates also failing). than it is searching the missing timestamps and printing the timestamp before and after the missing timestamp
Some other stocks are muck worse and there are tens of missing samples through out the day

## What is the expected result and why do you think it's the correct result ?
The expected results IMHO is samples from all the timestamps every 60 seconds

**Comment by finnhubio** [comment]
This question has been answered multiple times. There might not be enough qualifying trades to construct OHLC data for every minute and that's normal. If you wish to construct OHLC data yourself, please use Tick data to do that.

**Comment by zohargolan** [comment]
Thank you for the fast response. Really appreciated.
Is there a threshold for trade activity that there will not be any data below it?
