### ISSUE TITLE
Technical indicator regarding the italian market stopped working

### ISSUE THREAD

**Issue by MCoLoL** [finnhubio/Finnhub-API#325]
**What is the issue ? Plz describe in details**

All the technical indicator regarding the italian market stopped working last week (friday).
Before friday of the last week, they worked fine. The same call, but with different exchange and stock is working.

**How to reproduce the error ?**

Call the API endpoint:
curl -s 'https://finnhub.io/api/v1/indicator?symbol=RACE.MI&resolution=D&from=1592386245&to=1594978242&indicator=BBANDS&timeperiod=20&token=your-token'

**What is the expected result and why do you think it's the correct result ?**

API should return the corresponding indicator values or hande the error properly.

Any clue?
Thanks

**Comment by finnhubio** [comment]
It should be fixed now.

**Comment by MCoLoL** [comment]
I can't confirm you that is started back to work, because starting from yesterday i've this problem, Seems that i've been rate limited.

curl -I 'https://finnhub.io/api/v1/quote?symbol=AAPL&token=mytoken'

HTTP/2 302
date: Tue, 21 Jul 2020 09:44:21 GMT
content-type: text/html; charset=utf-8
set-cookie: __cfduid=d36f606d2ff48a025131867321555fd101595324661; expires=Thu, 20-Aug-20 09:44:21 GMT; path=/; domain=.finnhub.io; HttpOnly; SameSite=Lax; Secure
access-control-allow-credentials: true
access-control-allow-headers: Origin
access-control-allow-methods: POST, GET, OPTIONS, PUT, DELETE
access-control-allow-origin: *
access-control-expose-headers: Content-Length
location: /
x-ratelimit-limit: 60
x-ratelimit-remaining: 58
x-ratelimit-reset: 1595324706
cf-cache-status: DYNAMIC
cf-request-id: 04125b964f00000e124a86a200000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 5b63fb9d4a520e12-MXP

I tried to change the IP and the token, but always the same.

Can you explain me better the timing of rate limit? 
What is the number of request that can i do in free plan?
i can evaluate an upgrading of the plan, but i need to understand what will happen.
In the official documentation the rate limit is set 30 API calls/ second limit. 
I can confirm that i'm not calling more that this limit.

Thanks
Marco

**Comment by MCoLoL** [comment]
> I can't confirm you that is started back to work, because starting from yesterday i've this problem, Seems that i've been rate limited.
> 
> curl -I 'https://finnhub.io/api/v1/quote?symbol=AAPL&token=mytoken'
> 
> HTTP/2 302
> date: Tue, 21 Jul 2020 09:44:21 GMT
> content-type: text/html; charset=utf-8
> set-cookie: __cfduid=d36f606d2ff48a025131867321555fd101595324661; expires=Thu, 20-Aug-20 09:44:21 GMT; path=/; domain=.finnhub.io; HttpOnly; SameSite=Lax; Secure
> access-control-allow-credentials: true
> access-control-allow-headers: Origin
> access-control-allow-methods: POST, GET, OPTIONS, PUT, DELETE
> access-control-allow-origin: *
> access-control-expose-headers: Content-Length
> location: /
> x-ratelimit-limit: 60
> x-ratelimit-remaining: 58
> x-ratelimit-reset: 1595324706
> cf-cache-status: DYNAMIC
> cf-request-id: 04125b964f00000e124a86a200000001
> expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> server: cloudflare
> cf-ray: 5b63fb9d4a520e12-MXP
> 
> I tried to change the IP and the token, but always the same.
> 
> Can you explain me better the timing of rate limit?
> What is the number of request that can i do in free plan?
> i can evaluate an upgrading of the plan, but i need to understand what will happen.
> In the official documentation the rate limit is set 30 API calls/ second limit.
> I can confirm that i'm not calling more that this limit.
> 
> Thanks
> Marco



> It should be fixed now.

I can't confirm you that is started back to work, because starting from yesterday i've this problem, Seems that i've been rate limited.

curl -I 'https://finnhub.io/api/v1/quote?symbol=AAPL&token=mytoken'

HTTP/2 302
date: Tue, 21 Jul 2020 09:44:21 GMT
content-type: text/html; charset=utf-8
set-cookie: __cfduid=d36f606d2ff48a025131867321555fd101595324661; expires=Thu, 20-Aug-20 09:44:21 GMT; path=/; domain=.finnhub.io; HttpOnly; SameSite=Lax; Secure
access-control-allow-credentials: true
access-control-allow-headers: Origin
access-control-allow-methods: POST, GET, OPTIONS, PUT, DELETE
access-control-allow-origin: *
access-control-expose-headers: Content-Length
location: /
x-ratelimit-limit: 60
x-ratelimit-remaining: 58
x-ratelimit-reset: 1595324706
cf-cache-status: DYNAMIC
cf-request-id: 04125b964f00000e124a86a200000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 5b63fb9d4a520e12-MXP

I tried to change the IP and the token, but always the same.

Can you explain me better the timing of rate limit? 
What is the number of request that can i do in free plan?
i can evaluate an upgrading of the plan, but i need to understand what will happen.
In the official documentation the rate limit is set 30 API calls/ second limit. 
I can confirm that i'm not calling more that this limit.

Thanks
Marco
