### ISSUE TITLE
Error 500 upon Forex Exchanges API

### ISSUE THREAD

**Issue by hypo-thesis** [finnhubio/Finnhub-API#326]
The request is made as `https://finnhub.io/api/v1/quote?symbol=OANDA:US30_USD&token=xxxxxxx`

symbol is not supported it says but it used to work less than 24 hours ago.

The symbol is listed `{"description":"US Wall St 30","displaySymbol":"US30/USD","symbol":"OANDA:US30_USD"},`

What to do at this point?

**Comment by finnhubio** [comment]
The issue should be fixed now. Please try again.
