### ISSUE TITLE
Earnings Estimate Data Issue

### ISSUE THREAD

**Issue by jacobparish** [finnhubio/Finnhub-API#327]
## What is the issue ? Plz describe in details

Earnings estimate for Bank of America is off in the earnings calendar endpoint.

## How to reproduce the error ?

https://finnhub.io/api/v1/calendar/earnings?from=2020-06-03&to=2020-09-03&symbol=BAC&token=
```
{
  "earningsCalendar": [
    {
      "date": "2020-07-16",
      "epsActual": 0.37,
      "epsEstimate": 0.3855271,
      "hour": "bmo",
      "quarter": 2,
      "revenueActual": 22454000000,
      "revenueEstimate": 22010000000,
      "symbol": "BAC",
      "year": 2020
    }
  ]
}
```

## What is the expected result and why do you think it's the correct result ?

Bank of America beat it's expected earnings this quarter, which was $0.28 / share and not $0.38 / share.

**Comment by finnhubio** [comment]
Thank you for reporting. Estimates tend to vary from provider to provider. Let me have someone take a look at this.

**Comment by finnhubio** [comment]
Hi Jacob, I can confirm there were a bug in earnings calendar which map the estimate to the 3rd quarter instead of the 2nd. This issue is only limited to earnings calendar for the quarter. Earnings estimates in other endpoints are still correct. 

The issue has been resolved now.
