### ISSUE TITLE
Wildly inaccurate candle history on ODP

### ISSUE THREAD

**Issue by danbopes** [finnhubio/Finnhub-API#328]
URL: https://finnhub.io/api/v1/stock/candle?symbol=ODP&resolution=D&from=1562651390&to=1595269737

Closes are wildly inaccurate:

![](https://i.imgur.com/UEGFBvT.png)

They have not gone under $13 in the last year, so I'm not sure where these $2.5 amounts are coming from.

**Comment by finnhubio** [comment]
We had an issue earlier today which prevented the data from being adjusted for Splits. Please try again now.
