### ISSUE TITLE
Some problems with symbols in Moscow Exchange

### ISSUE THREAD

**Issue by goodarmen96** [finnhubio/Finnhub-API#329]
for request stock/symbol?exchange=ME response very strange. There are many same symbols in various form, for example, TCSG.ME

```
[
…
{
	"currency": "RUB",
	"description": "TCS Group Holding PLC",
	"displaySymbol": "TCSG_T2.ME",
	"symbol": "TCSG_T2.ME",
	"type": "DR"
}, {
	"currency": "RUB",
	"description": "TCS Group Holding PLC",
	"displaySymbol": "TCSG_RP.ME",
	"symbol": "TCSG_RP.ME",
	"type": "DR"
}, {
	"currency": "RUB",
	"description": "TCS Group Holding PLC",
	"displaySymbol": "TCSG_NT.ME",
	"symbol": "TCSG_NT.ME",
	"type": "DR"
}
…
]
```

"TCSG_T2.ME", "TCSG_RP.ME", "TCSG_NT.ME" - I don't know that means, but they useless

using this symbols in other request get no data

quote?symbol=TCSG_T2.ME
quote?symbol=TCSG_RP.ME
quote?symbol=TCSG_NT.ME

```
{
	"error": "Symbol not supported."
}
```

stock/metric?symbol=TCSG_T2.ME
stock/metric?symbol=TCSG_RP.ME
stock/metric?symbol=TCSG_NT.ME

```
{
	"metric": {},
	"metricType": "all",
	"symbol": "TCSG_RP.ME"
}
```

The same situation with all stocks from Moscow Exchange (ME)

**Comment by finnhubio** [comment]
Those are derivatives. Plz use symbol with type EQS for common stocks.
