### ISSUE TITLE
Inconsistancies with candle data

### ISSUE THREAD

**Issue by HowAlgorithmic** [finnhubio/Finnhub-API#33]
_Just wondering if you guys are aware / working on a fix for your candle data-_
There are some pretty big inconsistencies when requesting it:
[https://github.com/finnhubio/Finnhub-API/issues/32](https://github.com/finnhubio/Finnhub-API/issues/32)
[https://github.com/finnhubio/Finnhub-API/issues/25](https://github.com/finnhubio/Finnhub-API/issues/25)
[https://github.com/finnhubio/Finnhub-API/issues/24](https://github.com/finnhubio/Finnhub-API/issues/24)
(and the issue mentioned below)

___
I've noticed that pulling data doesn't return the desired time-frame correctly. As far as I recall, this problem didn't exist 2 weeks ago, including issue [https://github.com/finnhubio/Finnhub-API/issues/32](https://github.com/finnhubio/Finnhub-API/issues/32).

[https://finnhub.io/api/v1/stock/candle?symbol=AAPL&resolution=1&from=0000000000&to=1584504356&token=](https://finnhub.io/api/v1/stock/candle?symbol=AAPL&resolution=1&from=0000000000&to=1584504356&token=)

[https://finnhub.io/api/v1/stock/candle?symbol=AAPL&resolution=1&from=1268796840&to=1584504356&token=](https://finnhub.io/api/v1/stock/candle?symbol=AAPL&resolution=1&from=1268796840&to=1584504356&token=)

The second of these two api calls returns far more data than the first even though it should be the other way around in theory. This varies greatly from stock to stock. It also seems to be limited to approx 5,000 previous data points [https://github.com/finnhubio/Finnhub-API/issues/24](https://github.com/finnhubio/Finnhub-API/issues/24). 

Regards,

**Comment by Mitstronic** [comment]
I am experiencing the same issues.

**Comment by finnhubio** [comment]
we are aware of the behavior with US deep historical data and are actively working to resolve it. Sorry for the inconvenience. We will give an update once it's done.

**Comment by jeffhc** [comment]
I'm experiencing similar issues with candle data. Not only do I not get the correct time frame, most of the time I get no data at all.

[https://finnhub.io/api/v1/stock/candle?symbol=AAPL&resolution=60&from=1546664400000&to=1547096400000&token=bq2frbnrh5rb332ppng0](https://finnhub.io/api/v1/stock/candle?symbol=AAPL&resolution=60&from=1546664400000&to=1547096400000&token=)

**Comment by finnhubio** [comment]
> I'm experiencing similar issues with candle data. Not only do I not get the correct time frame, most of the time I get no data at all.
> 
> https://finnhub.io/api/v1/stock/candle?symbol=AAPL&resolution=60&from=1546664400000&to=1547096400000&token=

Your timestamp is not correct. It should be in seconds. Try this: https://finnhub.io/api/v1/stock/candle?symbol=AAPL&resolution=60&from=1546664400&to=1547096400&token=

**Comment by finnhubio** [comment]
This issue has been fixed. Note that from and to field of candle endpoint should be in seconds not milliseconds like in websocket.
