### ISSUE TITLE
^DJI symbol no longer working

### ISSUE THREAD

**Issue by danbopes** [finnhubio/Finnhub-API#330]
https://finnhub.io/api/v1/stock/candle?symbol=%5EDJI&resolution=D&from=1563768000&to=1595360831

This used to work perfectly fine, and as of recent, "Symbol is not supported". Can you please allow this symbol to be grabbed again?

**Comment by finnhubio** [comment]
Indices data will require a separate subscription. We will be announcing new pricing packages for these data at the end of the month.

Hope it helps.

**Comment by danbopes** [comment]
No, it absolutely does not help. Just removing functionality from an API, without any type of announcement, especially if people are relying on the API is god awful service. This is just horrendous.
