### ISSUE TITLE
Index access

### ISSUE THREAD

**Issue by Kunderao** [finnhubio/Finnhub-API#331]
## What is the issue ? Plz describe in details

How does one access the DOW or SP500 or VIX. What are the symbols to feed to the API? ^VIX does not work.

https://finnhub.io/api/v1/quote?symbol=^VIX&token=<deleted>  does not work.

{"error":"Symbol not supported."}

Thank you.

**Comment by zhizheng-1** [comment]
Same here.. it had worked before but indices suddenly stopped working.

**Comment by finnhubio** [comment]
We do not support ^VIX at this point. With a premium market data subscription, you can access the following indices: https://docs.google.com/spreadsheets/u/3/d/1BAbIXBgl405fj0oHeEyRFEu8mW4QD1PhvtaBATLoR14/edit?usp=sharing

**Comment by finnhubio** [comment]
Here is the list of indices you can now access with a premium subscription : https://docs.google.com/spreadsheets/u/3/d/1BAbIXBgl405fj0oHeEyRFEu8mW4QD1PhvtaBATLoR14/edit?usp=sharing . We are working to add a few more to the retail API version.

**Comment by ViennaMike** [comment]
So, essentially, I can no longer use Finnhub's free service for market index data? This is disappointing. I had been using it as the source for S&P 500 data, but it's not worth 10's of dollars or more per month to me. [https://www.mcgurrin.info/robots/620/]

**Comment by lemohammed** [comment]
How can we access the VIX? I am running the code below but I get no data
`import finnhub
import json
client = finnhub.Client('API_KEY')
data = client.stock_candles('^VIX', 1, 0, 1637110680)
with open('res.json', 'w+') as fp:
    json.dump(data, fp)
`
