### ISSUE TITLE
^DJI Data Issue

### ISSUE THREAD

**Issue by jacobparish** [finnhubio/Finnhub-API#332]
## What is the issue ? Plz describe in details

Dow quote is returning 0 for all fields.

## How to reproduce the error ?

https://finnhub.io/api/v1/quote?symbol=^DJI&token=
```
{
  "c": 0,
  "h": 0,
  "l": 0,
  "o": 0,
  "pc": 0,
  "t": 0
}
```

It has been doing this on and off all day. Yes, I do have a token that should have access to this data.

**Comment by finnhubio** [comment]
Looks like a separate issue with DJI. We will look into and follow up with you in email

**Comment by finnhubio** [comment]
The issue should be fixed for your account now.

**Comment by jacobparish** [comment]
@finnhubio Works now, thank you!
