### ISSUE TITLE
Symbol not supported - Canada

### ISSUE THREAD

**Issue by rbrite** [finnhubio/Finnhub-API#333]
I am getting the response "Symbol not supported" when I try and download the candlestick data for any tickers from the Canadian stock exchange with the '.TO' suffix. For example TD.TO returns the error, but TD (ie. the US version) of the ticker returns all the candlestick history for the US exchange.

This is a new issue that I noticed a couple of days ago. I have not changed any of my code and the download was working until recently.

**Comment by finnhubio** [comment]
Hi,

All international stocks will now require a subscription to access which we will announce later this month or early next month.

**Comment by OscarZhou** [comment]
Waiting for any new updates about international stock data access
