### ISSUE TITLE
How to acquire candlestick data for Index?

### ISSUE THREAD

**Issue by iamashwin99** [finnhubio/Finnhub-API#34]
I want to get the candlestick data for the Nifty 50 Index. 
I tried `https://finnhub.io/api/v1/stock/candle?symbol=NSEI&resolution=60&from=1572651390&to=1576452990&token=`
but got 
` {"s":"no_data"}`
However, quotes for NSEI work fine 
`https://finnhub.io/api/v1/quote?symbol=%5ENSEI&token=
`
Am I doing something wrong?

**Comment by finnhubio** [comment]
plz use the same symbol ^NSEI in candle endpoint. not NSEI

**Comment by iamashwin99** [comment]
That worked! Thankyou
