### ISSUE TITLE
Empty data on Aggregate Indicators

### ISSUE THREAD

**Issue by wilgosz** [finnhubio/Finnhub-API#347]
Today "Aggregate Indicators" return empty JSON-Object.

I calling for example: https://finnhub.io/api/v1/scan/technical-indicator?symbol=AAPL&resolution=D&token=MY-TOKEN
I get as an answer:
`{}`
instead:
`
{
  "technicalAnalysis": {
    "count": {
      "buy": 6,
      "neutral": 7,
      "sell": 4
    },
    "signal": "neutral"
  },
  "trend": {
    "adx": 24.46020733373421,
    "trending": false
  }
}
`
Best Regards

**Comment by systemzee** [comment]
Getting this as well

**Comment by systemzee** [comment]
Is it normal for finnhub to have a portion of an API down for over 17 hours? I am a paying customer, just curious.

**Comment by systemzee** [comment]
resolution of 1 minute still not working

**Comment by finnhubio** [comment]
This issue has been fixed on the same day. Sorry for the late update
