### ISSUE TITLE
getting no data when requesting candle data

### ISSUE THREAD

**Issue by copypasteearth** [finnhubio/Finnhub-API#355]
hello I am getting no-data from response when requesting candle stick data. maybe your server is down, or maintenance, it was working before, and now it is not

        `val apps = URL("https://finnhub.io/api/v1/stock/candle?symbol=$ticker&resolution=$resolution&from=$from&to=$to&token=$apiKey").readText()`

**Comment by finnhubio** [comment]
Please provide a reproducible example.

**Comment by copypasteearth** [comment]
```
GlobalScope.launch{
        val interval = getTimeInterval(context,appWidgetId)
        Log.d("stockdata--", getResolution(interval))
        val resolution = getResolution(interval)
        Log.d("stockdata--", "from: "+Date(getStartOfDayInMillis(interval)*1000).toString())
        Log.d("stockdata--", "to: " +Date(getEndOfDayInMillis(getStartOfDayInMillis(interval)*1000) * 1000).toString())
        val from = getStartOfDayInMillis(interval)*1000
        val to = getEndOfDayInMillis(getStartOfDayInMillis(interval))*1000
        //val apps = apiClient.stockCandles(ticker, getResolution(interval), getStartOfDayInMillis(interval), getEndOfDayInMillis(), null)
        //Log.d("stockdata--", "stat" + apps.toString())
        val apps = URL("https://finnhub.io/api/v1/stock/candle?symbol=$ticker&resolution=$resolution&from=$from&to=$to&token=$apiKey").readText()

        Log.d("stockdata--", "stat" + apps.toString())
}
```
that's about as reproducible as I can get, it is on android in Kotlin, I am just using the url like in the documentation

**Comment by finnhubio** [comment]
Hi plz provide us with a URL (API key removed) which contains all the parameters.

**Comment by copypasteearth** [comment]
this is the sample link in the documentation and it goes to no data

https://finnhub.io/api/v1/stock/candle?symbol=IBM&resolution=D&from=1572651390&to=1575243390&token=

**Comment by finnhubio** [comment]
Should work now, can you try again ?

**Comment by copypasteearth** [comment]
it works on the sample link from the documentation again. Is the data delayed because I am trying to get todays data on android from 9:31 to 4:00 and its telling me no data

**Comment by copypasteearth** [comment]
and also, it returns wrong resolution sometimes

**Comment by copypasteearth** [comment]
like this link doesn't work

https://finnhub.io/api/v1/stock/candle?symbol=AAPL&resolution=1&from=1599744660&to=1630800&token=

**Comment by finnhubio** [comment]
Please open another issue with a description and reproducible example. Your last url has the wrong "to" param. We will close this issue now.
