### ISSUE TITLE
api/v1/quote: You don't have access to this resource

### ISSUE THREAD

**Issue by kennethaasan** [finnhubio/Finnhub-API#356]
## What is the issue ? Plz describe in details

I'm getting "You don't have access to this resource" as a response from https://finnhub.io/api/v1/quote?symbol=MOWI.OL&trade=true&token=<TOKEN>

It has been working for months but stopped working today.

It seems to be an issue for stocks in the OL (Oslo) exchange.

**Comment by synhaptein** [comment]
Same here for some stocks on the TSX (Tonronto) exchange.

**Comment by finnhubio** [comment]
Our apology for the disruption. We will send out an email today to inform everyone that starting Monday next week, you will need to purchase a separate subscription to access international market data. You can check out the plan here: https://finnhub.io/pricing-stock-api-international-market-data

Your access has been temporarily enabled again until Monday next week. Again, our apology for the sudden disruption.

**Comment by kennethaasan** [comment]
Thanks!
