### ISSUE TITLE
websocket stucks

### ISSUE THREAD

**Issue by pycoder2020** [finnhubio/Finnhub-API#36]
Simply stops and do not do anything (token removed)
```
--- request header ---

Upgrade: websocket
Host: ws.finnhub.io
Origin: http://ws.finnhub.io
Sec-WebSocket-Key: dbiUIWjFpEA1m25jPOcD7Q==
Sec-WebSocket-Version: 13
Connection: upgrade


-----------------------
--- response header ---
```

**Comment by finnhubio** [comment]
plz try again. should be fixed now

**Comment by pycoder2020** [comment]
after few minutes I get response
```
--- response header ---
HTTP/1.1 101 Switching Protocols
Server: nginx/1.10.3
Date: Wed, 18 Mar 2020 19:59:00 GMT
Connection: upgrade
Upgrade: websocket
Sec-WebSocket-Accept: yZ2HZoHZGz/CRDZOy3t0AYVaYro=
-----------------------
send: b'\x81\xa4k@y_\x10b\r&\x1b%[eI3\x0c=\x18#\x0b6\t%[sI3\x002\t/\x15}Qb-\x0b<\x0f["'
```
But stream is also with interrupts comparing with Tradestation Tick data

**Comment by pycoder2020** [comment]
Market closed... Problem with server overload?

**Comment by finnhubio** [comment]
We can not comment on other providers' feed. We provide after market hour price as well so it doesn't if market closes, trades might still happen

**Comment by pycoder2020** [comment]
I mean interrupts :) Will continue compare real-time data tomorrow. Thanks for responses.

**Comment by pycoder2020** [comment]
Now WS works without stuck

**Comment by pycoder2020** [comment]
current delay for me is 2s
```
22:09:42 INFO     {"type":"ping"}
22:10:42 INFO     {"type":"ping"}
22:11:02 INFO     {"data":[{"p":110.5941,"s":"TTWO","t":1584562262644,"v":300}],"type":"trade"}
22:11:42 INFO     {"data":[{"p":105.064874,"s":"TTWO","t":1584562302444,"v":10334}],"type":"trade"}
```

**Comment by pycoder2020** [comment]
curren delay up to 700ms

**Comment by finnhubio** [comment]
If every ms matters for your trading strategy, we will not be the right provider at this point. Depending on the number of concurrent connection to our server, the latency can go up or down at time.
