### ISSUE TITLE
Data Issue: ETFs Holdings

### ISSUE THREAD

**Issue by sscode** [finnhubio/Finnhub-API#370]
## What is the issue ? Plz describe in details
I purchased the premium package for ETF Holdings query.  have a group of 115 active ETFs. 

When using the ETF Holdings call, no data is returned on 21 of them: 'ARMR',
 'BLCN', 'BUG', 'EKAR', 'FIVG', 'FNGS', 'KOIN', 'LEND', 'LRNZ', 'MOTO', 'OGIG', 'PRNT', 'QTUM', 'SIMS', 'SOXS', 'SRVR', 'TDV', 'THNQ',
 'TPAY', 'UFO', 'WUGI'

Additionally, 12 of them, there is partial data (# of shares) but incorrect % returns i.e. 9999.9999 is returned as %. These ETFs are: 'GRID', 'NERD', 'FTXL', 'ROBT', 'NXTG', 'FDN', 'LEGR', 'QTEC', 'FXL', 'SKYY', 'TDIV', 'CIBR'.

This is just the first run of this and will be testing many more etfs.

## How to reproduce the error ?

```
import requests
r = requests.get('https://finnhub.io/api/v1/etf/holdings?symbol=SKYY&token=XX')
print(r.json())
```

## What is the expected result and why do you think it's the correct result ?

I would expect each stock to be < 100 (as you can't exceed 100%)

Thanks for your help.

**Comment by finnhubio** [comment]
Hi,

Thank you for reaching out and I want to apologize for the issue you are encountering. I have forwarded the issue to the appropriate team for review.

We currently support data for ~2k ETFs in the US. Will look into the issue and report back to u asap.

**Comment by sscode** [comment]
Thanks for your quick response, additionally I would add that 73 of the ETFs have partial holding data.

There is 'stock', 'percentage' and 'shares'. In 73 of these, they have 1-2 of these points but not the 3rd which is somewhat counterintuitive (the combination of which varies).

**Comment by sscode** [comment]
Can I please have an update on this? Anyone I can speak to to get this resolved?

**Comment by finnhubio** [comment]
Hi, our apology for the late reply. It took us a while to standardize these ETFs data. The issue should be fixed now. We have also added support for International ETFs which will be available for purchase soon.
