### ISSUE TITLE
Inconsistent error response type

### ISSUE THREAD

**Issue by kYem** [finnhubio/Finnhub-API#372]
## What is the issue ? Plz describe in details
I'm using go SDK from: `github.com/Finnhub-Stock-API/finnhub-go`
https://finnhub.io/api/v1/stock/candle?symbol=0A00.L&resolution=D&from=1577836800&to=1606162002&token=
SDK throws an error of `undefined response type`

## How to reproduce the error ?
https://finnhub.io/api/v1/stock/candle?symbol=0A00.L&resolution=D&from=1577836800&to=1606162002&token={token}
Receive status code: `200 OK`, but the body of the text say`You don't have access to this resource.` and content type `text/plain`

Similar issue with invalid resolution
https://finnhub.io/api/v1/stock/candle?symbol=IBM&resolution=DD&from=1577836800&to=1606162466&token={token}
Where status is `200 OK`, body contains `wrong resolution` text and content type `text/plain`
## What is the expected result and why do you think it's the correct result ?
It's very hard to determine errors due to not using HTTP status codes correctly.
Therefore fallback needs to be done to try and parse body to understand if it's valid response.

Expect to receive `application/json` type response with error object populated, not `Content-Type: text/plain; charset=utf-8`

If request specify `application/json` content type, I expect response to always contain **valid json** or error HTTP status code. (400 or higher)

**Comment by finnhubio** [comment]
Thanks for the feedback. We are looking into the issue at the moment. Will issue a fix soon.

**Comment by Shathin** [comment]
Still facing this issue. Will this error be resolved?

**Comment by finnhubio** [comment]
Hi,

This issue has been corrected with today patch. Let us know if you have any further questions.

**Comment by kYem** [comment]
Seems to be resolved now.

**Comment by pdostal** [comment]
Hello, I am facing similar issue with `curl`:
```
curl -s "https://finnhub.io/api/v1/quote?symbol=$SYMBOL&token=$TOKEN"
{"error":"You don't have access to this resource."}
```
In my case the error applies only for some symbols.
Do you have a clue where the problem could be?
