### ISSUE TITLE
Error on /quote for London Exchange

### ISSUE THREAD

**Issue by polak3a** [finnhubio/Finnhub-API#376]
## What is the issue ? Plz describe in details
I can get a quote for Me (Moscow Exchange) however  I cannot do it for London Exchange (I am subscribed for All in one API plan already)
## How to reproduce the error ?
https://finnhub.io/api/v1/quote?symbol=LNTA.L&token=...
## What is the expected result and why do you think it's the correct result ?
I expect to get json as well as I get it for AFLT.Me e.g: 
{"c":72.18,"h":72.62,"l":70.7,"o":71.6,"pc":72.14,"t":1606694400}

**Comment by finnhubio** [comment]
It seems to be working fine on my end. Can you send an email to support@finnhub.io instead ? We will support you better there.
