### ISSUE TITLE
Dec. 23, 2020 historic tick data missing

### ISSUE THREAD

**Issue by FreeGoldRush** [finnhubio/Finnhub-API#382]
## What is the issue ? Plz describe in details

/v1/stock/tick returns no trades for MSFT on Dec. 23, 2020.  The market was open and MSFT was trading.

## How to reproduce the error ?

Put your personal token into the URL below and check for yourself.

https://tick.finnhub.io/api/v1/stock/tick?symbol=MSFT&date=2020-12-23&token=&limit=0&skip=0&format=csv

## What is the expected result and why do you think it's the correct result ?

I expect to see all MSFT trades on Dec. 23, 2020

**Comment by finnhubio** [comment]
Hi, the issue has been fixed. Plz let us know if you still have any difficulties accessing the data
