### ISSUE TITLE
No data available for Doordash

### ISSUE THREAD

**Issue by danielwhsu** [finnhubio/Finnhub-API#385]
## What is the issue ? Plz describe in details
There is no stock market data for Doordash. The data returned from https://finnhub.io/api/v1/stock/profile2?symbol=DASH&token= is empty.

## How to reproduce the error ?
Visit https://finnhub.io/api/v1/stock/profile2?symbol=DASH&token=

## What is the expected result and why do you think it's the correct result ?
Expected result is that there is stock market data for Doordash because Doordash is a public company.

**Comment by finnhubio** [comment]
Hi there,

Thank you for opening an issue here. New IPO companies do take a bit of time for us to get the profile data ready. DASH should be available for query now.

Let us know if you have still encounter any difficulties.
