### ISSUE TITLE
ETF data is missing, bogus, and several new ETFs show no data at all.

### ISSUE THREAD

**Issue by xeokeri** [finnhubio/Finnhub-API#386]
## What is the issue ? Plz describe in details
ARKG shows data from December 28 and earlier, no data 3 days after.

## How to reproduce the error ?
ARKG symbol, skip = 0, path = etf/holdings

## What is the expected result and why do you think it's the correct result ?
Expect ARKG data all the way up to current. ARKG December 31st data shows different holdings, as well as diffident count of holdouts. ETFs that are less than a month old provide no data at all.

**Comment by finnhubio** [comment]
Hi there,

ARK fund's ETFs are highly requested and we are working on Daily holdings for them as we speak. Should be available within this week.

Can you provide a bit more details about the new ETFs that you are looking for data ?

**Comment by finnhubio** [comment]
Data for ARK ETFs have been updated. We will now start daily holdings support for ARK ETFs.

https://finnhub.io/api/v1/etf/holdings?symbol=ARKG&token=

Hope it helps. Let us know if you have any further questions.

**Comment by finnhubio** [comment]
Close due to inactivity. Feel free to reopen if you want to provide more details.
