### ISSUE TITLE
S&P 500 data is wrong

### ISSUE THREAD

**Issue by jacobparish** [finnhubio/Finnhub-API#389]
This is what I currently get for `/v1/quote?symbol=^GSPC&token=xxx`
```json
{
  "c": 3771.5,
  "h": 3779.2,
  "l": 3751.3,
  "o": 3761.5,
  "pc": 3759.6,
  "t": 1609970400
}
```
According to both google and yahoo, the close price (for today, wednesday jan. 6th) was 3748.14, and the open price was 3712.20, which differ from finnhub. Additionally, it is currently 11:50 PM EST, and I have been periodically refreshing that endpoint and the current price has been changing (????).

**Comment by finnhubio** [comment]
Hi Jacob,

You are currently accessing CFD indices to display on your website. This instrument tracks the S&P500 closely but does not match exactly. To display real S&P500 indices data, you would need to obtain a license from S&P directly ~$350/month.

Let us know if you have any further questions.
