### ISSUE TITLE
Wrong data

### ISSUE THREAD

**Issue by yvesn7** [finnhubio/Finnhub-API#39]
I keep running in data reliability issues, to the point where I am starting to question all the data. A random example this morning - Finnhub indicates a closing price of $250.195 for AAPL last night ({"c":250.195,"h":252.84,"l":242.61,"o":247.39,"pc":246.67,"t":1584624600}), which is wrong. The closing price was $244.78. Other positions (such as GOOG or MSFT) are correct. Anybody else seeing these issues? Possibly it might be related to this recent thread: https://github.com/finnhubio/Finnhub-API/issues/21

**Comment by finnhubio** [comment]
"c" is the latest price of the day. We support after market hour trading so "c" might not reflect the official closing price but the latest trade price. After 1 day, we will use the official closing price as "pc" field , which you can check is now 244.78

**Comment by yvesn7** [comment]
Please don't close this thread by giving me the wrong answer. The quote included in the thread was pulled around 3am Eastern Time, way after the market closed, and did not include the closing price for AAPL - neither as the current nor as the pc. As I indicated above, quotes for other positions such as GOOG and MSFT were correct. Isn't it an expectation that 6 hours after closing, the market close would be reflected somewhere?

**Comment by finnhubio** [comment]
Hi, until the market opens again, we will still use "c" as the latest price from yesterday. "pc" only get updated once the market opens.

**Comment by yvesn7** [comment]
Fine, but then "c" should be the last price for yesterday, i.e. market close. Otherwise the data is not reliable. I am pulling data 6 hours after market close. Other positions were correct. AAPL was not.

**Comment by yvesn7** [comment]
in other words, i am fine with whichever documented decision is made - but a) I need to be able to pull the market close somehow (either as "c" or as "pc") before the market reopens (which I couldn't do for AAPL yesterday), and b) whichever model you adopt needs to be consistent across positions (which it wasn't yesterday). Thanks.

**Comment by yvesn7** [comment]
This is an adoption blocker for me. Without help/response I will start looking at other API's. Thanks.

**Comment by ruralcoder** [comment]
I noticed the API now changed as to 'c' being the 'current' price all the way up to closing. 
Which was unfortunate for me today. 

I am reading yvesn7 request and I think it's not incompatible with your existing fields.

I would expect at all times to see the current price even after hours. 
 Alot of market fluctuation occurs pre and post market hours which affect my prediction algos.
Price at closing time is just not the correct price.

<img width="669" alt="Screen Shot 2020-03-20 at 11 36 03 PM" src="https://user-images.githubusercontent.com/12993309/77221090-b2610c80-6b03-11ea-9954-aaaebd7858d3.png">


The compromise can be
-  **'c'** current for all time pre-, during- and post- market
- **'pc'** be set at 4PM NYC time, why wait for the next day. And it's technically correct previous close at say 5PM is todays 4PM market close.

So, just change when PC gets get. I don't know your platform, but should be easy.

I must thank you guys for being responsive.

**Comment by finnhubio** [comment]
Hi, we are debating this issue within our team. Will let you guys know what we decide.

**Comment by ruralcoder** [comment]
Thanks, I updated my comments to better reflect my thoughts.

**Comment by finnhubio** [comment]
Thanks. We are aware of the issue yvesn7 mentioned that there were inconsistencies in the approach of choosing close price and previous close price for different stocks. Let us look into it and let you guys know. 

@ruralcoder the only sure way to get after and pre market hour trading right now is to use WebSocket, all trades will be pushed there.

**Comment by ruralcoder** [comment]
I will take a look at the API, haven't yet.
But I would have expected data consistency between retrieval methods.

**Comment by yvesn7** [comment]
Thank you. It's Saturday 2:30am Eastern and I just pulled the following quotes:

AAPL: {"c":229.05,"h":251.83,"l":228,"o":247.18,"pc":244.78,"t":1584711000}
MSFT: {"c":137.35,"h":147.1,"l":135.86,"o":146,"pc":142.71,"t":1584711000}
GOOG: {"c":1072.3199,"h":1143.99,"l":1065.49,"o":1135.72,"pc":1115.29,"t":1584711000}

1- pc for all 3 stocks reflect market close for 3/19 (2 days ago). To me, that information is old and doesn't need to be locked until Monday, but at least it's consistent across all 3 stocks (good).    

2- c for MSFT and GOOG work "as expected", i.e. reflects last quote of the day (effectively market close) for 3/20 (yesterday). However it doesn't for AAPL, where the last trade was 229.24. This is an issue both in terms of consistency (different behavior across stocks) and usability (I have no way to get AAPL Friday close until Monday?).

Thank you guys for looking into this.  

As an aside, ruralcoder's suggestions do make sense. :)

**Comment by 70853n** [comment]
Today I stumbled uppon an instance of company fundamentals containing wrong data:
Boeing (BA) reported an annual revenue of $76,559M but `api/v1/stock/financials` states `84818`. The gross profit is wrong accordingly, and I assume all metrics based on the value as well.

May I kindly ask where finnhub is getting it's data from? Is it from FactSet?

To me as a potential customer transparency about the product is of utmost importance. Obviously the product will evolve and improve. I hope such feedback will help this process.

**Comment by finnhubio** [comment]
> Today I stumbled uppon an instance of company fundamentals containing wrong data:
> Boeing (BA) reported an annual revenue of $76,559M but `api/v1/stock/financials` states `84818`. The gross profit is wrong accordingly, and I assume all metrics based on the value as well.
> 
> May I kindly ask where finnhub is getting it's data from? Is it from FactSet?
> 
> To me as a potential customer transparency about the product is of utmost importance. Obviously the product will evolve and improve. I hope such feedback will help this process.

Plz be respectful to other developers and open a new issue for your question. This thread is for another for another issue and we can't help you here.

**Comment by yvesn7** [comment]
This is the response I consistently get for CSCO today: 
{"c":0,"h":0,"l":0,"o":0,"pc":0,"t":0}
It works for a couple of minutes, and then I get a pull at zero. I don't know why. I have to write code to circumvent this. 

Just too many issues with data reliability here. Please let me know if you want me to open a different issue to track this. Thank you.

**Comment by finnhubio** [comment]
We have released a new version to improve the reliability for quote endpoint for US stocks. 

Regarding "c" field, it will be the official close for now. Undocumented method to get pre/post market hour price is to add a param &trade=true into the url. It will remain undocumented until further notice as we need to check with the exchange whether pre/post market hour can be accessed with free plan.

**Comment by ruralcoder** [comment]
Just deployed my code with &trade=true

Thanks

**Comment by yvesn7** [comment]
With all due respect, this doesn't appear to be working. I have tried both &trade=true and &trade=false in pre-market this morning, and I am unable to get pre-market values. They both return the same string (the Friday market information). Response appreciated.

**Comment by ruralcoder** [comment]
They are also trying my patience. They keep breaking shit.

**Comment by yvesn7** [comment]
It appears to be working tonight in extended hours. I will check in the morning that it also works in pre-trading. Thank you.

**Comment by SovietAlex** [comment]
Please make pre market and after market prices free. IEX Api has that, Polygon.io has that. Like most websites, they have the ability to show the closing price and the after market price.
