### ISSUE TITLE
Some C3.AI (AI) stock data seems to be wrong

### ISSUE THREAD

**Issue by boherna** [finnhubio/Finnhub-API#390]
For the endpoint  **/api/v1/stock/profile2?symbol=AI&token=XXXXXX** the API returns:

```
{
  "country": "US",
  "currency": "USD",
  "exchange": "NEW YORK STOCK EXCHANGE, INC.",
  "finnhubIndustry": "Real Estate",
  "ipo": "2009-10-07",
  "logo": "",
  "marketCapitalization": 13274.95,
  "name": "Arlington Asset Investment Corp",
  "phone": "17033730200",
  "shareOutstanding": 96.33,
  "ticker": "AI",
  "weburl": "http://www.arlingtonasset.com/"
}
```

However, the industry, name, phone and webUrl should match the info on Yahoo Finance (https://uk.finance.yahoo.com/quote/AI/profile?p=AI), that is:

C3.ai, Inc.
650-503-2200
http://www.C3.ai
Sector(s): Technology
Industry: Information Technology Services

**Comment by finnhubio** [comment]
Hi AI symbol was previously used by Arlington Asset before reassigned to C3.ai. We have updated the data accordingly.

Our apology for the delay.

**Comment by boherna** [comment]
No worries. Better late than never ;-)
