### ISSUE TITLE
In price target the 'lastUpdated' date is in the future

### ISSUE THREAD

**Issue by boherna** [finnhubio/Finnhub-API#393]
For the endpoint /api/v1/stock/price-target?symbol=AAPL&token=XXXXXX the API returns:
```
{
  "lastUpdated": "2021-01-21 00:00:00",
  "symbol": "AAPL",
  "targetHigh": 160,
  "targetLow": 75,
  "targetMean": 129.84,
  "targetMedian": 135
}
```
Today is Jan 19, 2021 but the API says the data was last updated 2 days in the future?

**Comment by finnhubio** [comment]
Hi, we updated the targets every week so it basically mean the 3rd week of January. We will be moving away from this practice soon however. Will just use the date we update the data instead.
