### ISSUE TITLE
Feature request: WebSocket unsubscribe message type

### ISSUE THREAD

**Issue by aklinkert** [finnhubio/Finnhub-API#396]
Hey there,

it would be useful if we could unsubscribe from a stock real-time update stream on WebSocket, for example when I am interested in different stocks in forenoon and afternoon and don't want to reconnect.

Thanks in advance!
Alex

**Comment by finnhubio** [comment]
Hi,

You can already do that with our websocket.

socket.send(JSON.stringify({'type':'unsubscribe','symbol': symbol}))

Hope it helps.

**Comment by aklinkert** [comment]
Hey @finnhubio ,

thanks for the info! Can you please extend the documentation with that message type? :)

**Comment by finnhubio** [comment]
Hi,

It's already in the Sample code. You can take a look here: https://finnhub.io/docs/api/websocket-trades

**Comment by aklinkert** [comment]
Hm, I am unable to find the term `unsubscribe` on the docs page ... can you point me to the exact place?
