### ISSUE TITLE
What is possible in free plan ?

### ISSUE THREAD

**Issue by Taryck** [finnhubio/Finnhub-API#397]
## What is the issue ? Plz describe in details
I Call : 
https://finnhub.io/api/v1/stock/candle?symbol=SLB.PA&resolution=1&from=1612483200&to=1612483200&token=xxxxx
I get : 
{
    "error": "You don't have access to this resource."
}
## How to reproduce the error ?
Call https://finnhub.io/api/v1/stock/candle?symbol=SLB.PA&resolution=1&from=1612483200&to=1612483200&token=xxxxx

## What is the expected result and why do you think it's the correct result ?
Get slumberger last friday closing quotation

What is include and what is exclude from free plan ?

As I only need each end of month last available quotation for free stocks.
Will the free plan support that... or not ?

**Comment by finnhubio** [comment]
Hi, the free plan only gives you access to US market data. You would need a subscription to get data for Euronext: https://finnhub.io/euronext-end-of-day-level-1-data

**Comment by Taryck** [comment]
Ok thanks.

As I'm an European citizens
I do not care on US market.
