### ISSUE TITLE
Technical indicator Aroon response attribute misspelled

### ISSUE THREAD

**Issue by bliu886** [finnhubio/Finnhub-API#399]
## What is the issue ? Plz describe in details
When hitting the API for getting the Aroon technical indicator, the response attribute for aroonup is misspelled as "arronup" (2 r's and 1 o instead of 1 r and 2 o's). It doesn't match the response attributes listed in the google doc, https://docs.google.com/spreadsheets/d/1ylUvKHVYN2E87WdwIza8ROaCpd48ggEl1k5i5SgA29k/edit#gid=0

## How to reproduce the error ?
Hitting the API will return a JSON string with the misspelled response attribute. Example:
https://finnhub.io/api/v1/indicator?symbol=AAPL&resolution=1&from=1612818000&to=1612904400&indicator=aroon&timeperiod=15&token=XXXXXXXXX

## What is the expected result and why do you think it's the correct result ?
Expected result is JSON string with the correctly spelled response attribute. "aroonup" instead of "arronup"

**Comment by finnhubio** [comment]
Hi there,

Thank you for reporting the issue. We will look into it asap.

**Comment by finnhubio** [comment]
The issue has been fixed now.
