### ISSUE TITLE
Issues with API calls

### ISSUE THREAD

**Issue by coffincw** [finnhubio/Finnhub-API#40]
I noticed an issue when attempting to get the candle data for the last 5 days with 1 minute resolution.

https://finnhub.io/api/v1/stock/candle?symbol=^DJI&resolution=1&from=1584192600&to=1584730152&token=mytoken

If you try and refresh this call in the browser occasionally it returns no data despite the timeframe not changing and there being no reason for there not to be data between those time frames.

**Comment by finnhubio** [comment]
Hi, I can confirm it's an issue with indices feed. We will look into it. Thanks for reporting.

**Comment by coffincw** [comment]
Just for an additional update, I only seem to be having the issue with ^DJI and it's fairly often.

**Comment by finnhubio** [comment]
This should be fixed now. Will reopen if you still encounter the issue tmr.

**Comment by coffincw** [comment]
Still having the same issue.

https://finnhub.io/api/v1/stock/candle?symbol=^DJI&resolution=1&from=1584192600&to=1585165130&token=mytoken
