### ISSUE TITLE
Response size for "60" minute Candles

### ISSUE THREAD

**Issue by shjoshi95** [finnhubio/Finnhub-API#406]
I am making a call to collect 60 minute candles for "SPY", trying to observe the past 50 days of data (based on my start and end epochs), but in the response, I seem to only get back a couple of hundred timestamps. I have seen in other APIs there is a "limit" data param that can be passed in the request to specify how large the response can be. Is there any param like this in Finnhub to get more data back?

**Comment by finnhubio** [comment]
Hi, there is no limit param for the Candles endpoint at the moment. You will have to use the first timestamp of the result as the new "to" param in the next request to get all of the data.

If you want to be sure that the request won't be truncated, you should request for 1-month of data at a time.

**Comment by shjoshi95** [comment]
Thank you for confirming that the solution to this is to aggregate data iteratively. Would be a nice to have to collect maybe 2-3 months of hourly bars in a single call though :)
