### ISSUE TITLE
Question about FinnHub latencies

### ISSUE THREAD

**Issue by shjoshi95** [finnhubio/Finnhub-API#407]
I am testing with the sandbox API key and noticed there is a few seconds (~4s) of latency to get the response back per call. I have seen in Polygon that the comparable latency is (~2s). Does Finnhub provide faster latencies with the Premium key, or do Premium and Sandbox keys have the same latency expectations?

**Comment by mremias** [comment]
Latencies are now about 40s. I'm on free model now, but thinking about premium. is anything with the service now?
![Postman](https://user-images.githubusercontent.com/3224862/108817785-b79ec500-75b8-11eb-91fe-6003d79ab0be.png)

**Comment by mremias** [comment]
Latencies are now about 40s. is anything with the service right now?
![Postman](https://user-images.githubusercontent.com/3224862/108817901-dd2bce80-75b8-11eb-8ca5-e103645a7245.png)

**Comment by kristjanmar** [comment]
There is definitely something wrong with the service at the moment, I am also getting very slow response times. Most are timing out as I have set my API calls to time out after either 5s or 10s.

**Comment by shjoshi95** [comment]
I am seeing the same thing. Can someone with a premium key please confirm if they are also experiencing high latency?

**Comment by shjoshi95** [comment]
Received confirmation from the FinnHub support team that this was caused by a massive spike in traffic Monday evening that has since subsided.
