### ISSUE TITLE
Professional users only

### ISSUE THREAD

**Issue by trapadulli** [finnhubio/Finnhub-API#41]
I get: Professional users only.
When I call: https://finnhub.io/api/v1/stock/transcripts?id=AAPL_162777&token=bpr374frh5r8s3uv51ug

I don't understand why I don't have access to make this call?
I have a Basic subscription and Basic subscriptions claims to provide premium access.
If I don't have access to call transcripts with basic subscription, please refund me.
thanks

**Comment by finnhubio** [comment]
Hi, as stated on pricing page and in documentation, you need professional or ultimate plan to access earnings call transcripts.

<img width="520" alt="image" src="https://user-images.githubusercontent.com/61330265/77232552-0f96a580-6b78-11ea-989a-af683b01ab64.png">

**Comment by trapadulli** [comment]
how far does the data go back. I'm hesitant to test with Premium if it only returns the last 5 AAPL earnings calls... for instance

**Comment by finnhubio** [comment]
Hi, professional plan will give you access to last 5 earnings call. Ultimate plan will give you access to data going back to around 2003. To make up for the confusion, if you wish to upgrade to 1 of the 2 plans, plz email support@finnhub.io. We will give you 50% discount this month.
