### ISSUE TITLE
Quote API stopped worrking for some symbols Feb 23

### ISSUE THREAD

**Issue by cledgard** [finnhubio/Finnhub-API#410]
Hello
On about February 23, the quote API for some symbols stopped working.
One example is the following...
https://finnhub.io/api/v1/quote?symbol=ERE-UN.TO&token=xxxxxxxxxxxxxxxxxxxxxx

Does anyone know why this happened or how to get it to for the above symbol? 

Thanks

**Comment by finnhubio** [comment]
Please try ERE.UN.TO

**Comment by cledgard** [comment]
Thanks.. working now!
