### ISSUE TITLE
Financials Issue: Revenue null WEC Quarterly income statement

### ISSUE THREAD

**Issue by ddogg** [finnhubio/Finnhub-API#412]
Revenue field null for quarterly reports: https://finnhub.io/api/v1/stock/financials?symbol=WEC&statement=ic&freq=quarterly&token=TOKEN

But revenue exists if you do annual: https://finnhub.io/api/v1/stock/financials?symbol=WEC&statement=ic&freq=annual&token=TOKEN

This kind of error should not pass even the most basic audit when importing/processing the data.  This is a big company too, extra care should be taken on larger companies.

Thanks.

**Comment by finnhubio** [comment]
This issue should be corrected now.
