### ISSUE TITLE
Missing Financials as Reported for NIO, EH, SPOT, SHOP

### ISSUE THREAD

**Issue by chaschev** [finnhubio/Finnhub-API#416]
Financials are unfortunately missing for the meme & Cathie Wood stocks!

Tried with [url ](https://finnhub.io/api/v1/stock/financials-reported?symbol=SHOP&token=)

**Comment by finnhubio** [comment]
Hi there,

Financials as reported data is only available for US companies which file 10-K and 10-Q with the SEC. Companies in your list are foreign companies which do not file 10-K and 10-Q with the SEC. To access data for these companies, please use the premium Financials endpoint instead.

**Comment by chaschev** [comment]
Hey,

Under which API can I find this? Just in case, this is an ADR Symbol which is available through EDGAR API

UPDATE: found it here: https://finnhub.io/api/v1/stock/financials?symbol=NIO&statement=bs&freq=annual&token=
