### ISSUE TITLE
Company Profile returns no data for this list of tickers (US Exchange)

### ISSUE THREAD

**Issue by ddogg** [finnhubio/Finnhub-API#419]
Some of these are probably tiny companies but at least a few are pretty big.

PBI
ARYD
CRU
AKIC
KLAQ
MKC.V
GNTX
BSMX
ALYA
REPX
FVT
SCR
AIRTW
PRSR
TLC
KAIR
LWAC
PAQC
SBBP
MDGS
PPGH
IMCC
ZEPP
CUBE
GSAQ
EPWR
LFMD
INKA
IFS
TANH
EAC
VIRX
APOP
BFLY
STPC
SPNT
BCTX
AENZ
LHC
BLTS
CPAC
TMKR
H
BVN
PRTG
SUPV
EPHY
PACX
PACX
NVOS
GNUS

**Comment by finnhubio** [comment]
Added multiple profiles data in the list. Can you please check again ?
