### ISSUE TITLE
MKC dividends incorrect

### ISSUE THREAD

**Issue by ddogg** [finnhubio/Finnhub-API#424]
MKC dividends are wrong.  You are showing 6 payments for 2014.  There were only 4.  Other issues incorrect as well.  Please fix.

https://finnhub.io/api/v1/stock/dividend?symbol=MKC&from=2013-02-01&to=2020-02-01&token=TOKEN

https://ir.mccormick.com/stock-information/dividend-history

**Comment by finnhubio** [comment]
The issue should has been corrected
