### ISSUE TITLE
BABA: Marketcap showing in USD but currency returned for company info is CNY

### ISSUE THREAD

**Issue by ddogg** [finnhubio/Finnhub-API#429]

**Comment by finnhubio** [comment]
Hi this is expected behavior. BABA is listed on US exchanges so it will have USD market cap. CNY is the currency for its fundamental data such as financial statements, earnings etc.

**Comment by ddogg** [comment]
This is definitely not the case.  DEO, UL, just 2 examples that are not returning market cap in USD.  All the non-us companies listed on US exchanges that I've checked so far are returning market cap in their respective currencies, EXCEPT for BABA, which is returning it in USD.  I am converting the market cap to USD in realtime on my end so I don't really care as long as you are consistent with all companies I can deal with it.  Either have BABA return marketcap in CNY or fix all others to return in USD, thanks!
