### ISSUE TITLE
Stock candle from/to timestamps not working for certain stocks

### ISSUE THREAD

**Issue by vanzelleb** [finnhubio/Finnhub-API#435]
I discovered an issue with the historic timeseries data. Depending on the stock I select the API returns timeseries data of the last 3 months (as intended by the from/to timestamps) or the entire timeseries since the 1980s (for MSFT).

https://finnhub.io/api/v1/stock/candle?symbol=MSFT&resolution=D&from=1609842785&to=1617615185
https://finnhub.io/api/v1/stock/candle?symbol=SQ&resolution=D&from=1609842785&to=1617615185

**Comment by finnhubio** [comment]
Hi there, The issue has been fixed now.
