### ISSUE TITLE
SEC Sentiment seems broken

### ISSUE THREAD

**Issue by JimmyPettersson85** [finnhubio/Finnhub-API#438]
Hi!

Every time I try to call the SEC Sentiment endoint it returns a status of `500` with the error
`json: error calling MarshalJSON for type models.JSONString: unexpected end of JSON input`

example: https://finnhub.io/api/v1/stock/filings-sentiment?accessNumber=0001193125-21-113365&token=REDACTED

**Comment by finnhubio** [comment]
Hi there, we only support Sentiment for 10-K and 10-Q at the moment. You are requesting another filing so the data won't be available. The error with empty response has been fixed now.
