### ISSUE TITLE
stock candle - range for adjusted prices

### ISSUE THREAD

**Issue by buswedg** [finnhubio/Finnhub-API#44]
Is there a limit to the range which can be returned when specifying adjusted=true for daily (candle) stock prices?

As an example, I can specify {start=0, end=1584763200} and get something back for AAPL at a daily interval when adjusted=false. But get nothing back when adjusted=true.

Have also tried running a query with adjusted=false to get the min UNIX returned from query, and passing that back in as start with adjusted=true, and still getting nothing back.

**Comment by finnhubio** [comment]
This issue has been fixed. Our apology for the inconvenience.
