### ISSUE TITLE
Query range of OHLC data

### ISSUE THREAD

**Issue by StefanStsc** [finnhubio/Finnhub-API#445]
I'd like to pull the complete data for a few years.
If I set the from date to 1.1.2012 and to date for today, only a few hundred candles are returned for 1 minute intervals. So my questions are:

1) How does the /stock/candle endpoint work exactly for large date ranges?
2) How many candles are returned at maximum?
3) If I give a large date range, which candles are returned?

**Comment by embulldogs99** [comment]
I think their docs say only 1 year of data is available and the candle width is a parameter you can pass

https://finnhub.io/docs/api/stock-candles

**Comment by StefanStsc** [comment]
It's not really clear how many candles are returned for each call.
For example you can't get all minute candles for one year at once. And if you get the result, you would not see if and where  it's truncated.

I think this API is flawed and support from this company is mediocre.

**Comment by finnhubio** [comment]
Hi there, 

For intraday resolution, a maximum of 1 month of data is returned for each API call. You can simply use the first timestamp of the returned result in the "to" params in the next request to iteratively request all data.

The limit is in place to make sure that the system runs smoothly for all users.

Hope that helps.

**Comment by chrim5** [comment]
> The limit is in place to make sure that the system runs smoothly for all users.

Or to sell higher price plans if you need additional requests to get all the data 🤷‍♂️

**Comment by finnhubio** [comment]
> > The limit is in place to make sure that the system runs smoothly for all users.
> 
> Or to sell higher price plans if you need additional requests to get all the data 🤷‍♂️

Well that's a fair point. However, it's just not the case here since we have the same limit in place for all premium/enterprise users. Also Finnhub offers the most generous free plan on the market as we value the community and strongly believe in easy access to high-quality financial data.

Anyway, the issue will be closed now since the original question has been answered.
