### ISSUE TITLE
Missing Tick Data

### ISSUE THREAD

**Issue by SilverBullCapital** [finnhubio/Finnhub-API#448]
Hi,

I have pulled tick data for APPLE stock and also downloaded the large PDF file for tick data for January 2nd 2020. (the data is the same)

It seems there is a lot of tick data missing from FINNHUBB when I compare to FREE tick data from tickhistory.com. 

For example at the 0930 market opening I would expect to see hundreds of ticks occurring in the first 30 mins. FINNHUBB only has about 32 ticks. But with the free tick data from tickhistory.com there are hundreds of ticks. 

Please see below. I have paid $100 to get all tick data. Please explain why the finnhubb data below is so little.

Finnhubb data below (from time 0930 - 1001): there are only 32 ticks for the busiest part of trading day!

158,2020-01-02 09:30:05.441,295.7,17.0,P,1_24_12
159,2020-01-02 09:30:05.441,295.67,383.0,P,1_24
162,2020-01-02 09:30:24.243,295.67,67.0,P,1_24_12
165,2020-01-02 09:32:09.215,295.56,100.0,P,1_8_24
166,2020-01-02 09:32:09.215,295.56,100.0,P,1_8_24
167,2020-01-02 09:32:09.215,295.56,900.0,P,1_8_24
216,2020-01-02 09:37:30.782,295.72,1.0,P,1_24_12
217,2020-01-02 09:39:02.112,295.65,50.0,P,1_24_12
222,2020-01-02 09:44:24.403,295.67,1.0,P,1_24_12
225,2020-01-02 09:46:13.703,295.68,23.0,P,1_24_12
226,2020-01-02 09:46:13.836,295.68,19.0,P,1_24_12
228,2020-01-02 09:49:22.959,295.61,22.0,P,1_24_12
232,2020-01-02 09:51:13.923,295.67,200.0,P,1_8_24
233,2020-01-02 09:51:13.923,295.72,100.0,P,1_8_24
234,2020-01-02 09:51:20.836,295.72,300.0,P,1_8_24
235,2020-01-02 09:51:42.745,295.72,193.0,P,1_8_24
236,2020-01-02 09:51:42.745,295.74,107.0,P,1_8_24
237,2020-01-02 09:51:47.680,295.74,300.0,P,1_8_24
238,2020-01-02 09:51:54.304,295.74,10.0,P,1_24_12
239,2020-01-02 09:52:53.449,295.73,194.0,P,1_24
240,2020-01-02 09:52:53.449,295.73,95.0,P,1_24_12
241,2020-01-02 09:54:05.386,295.72,10.0,P,1_24_12
242,2020-01-02 09:54:20.869,295.72,54.0,P,1_24_12
243,2020-01-02 09:55:05.964,295.71,5.0,P,1_24_12
244,2020-01-02 09:56:47.163,295.7,10.0,P,1_24_12
245,2020-01-02 09:57:32.179,295.68,8.0,P,1_24_12
246,2020-01-02 09:59:47.193,295.64,2.0,P,1_24_12
247,2020-01-02 09:59:47.193,295.57,30.0,P,1_24_12
250,2020-01-02 10:01:28.191,295.73,50.0,P,1_24_12

Free tick data from tickhistory.com (from time 0930 up to the first second of market open): There are almost 50 ticks in the first second of market open! Why does Finnhubb have very little tick data?

6016,2020-01-02 09:30:00.193,296.23,5,XNGS,AAPL
6028,2020-01-02 09:30:00.324,296.23,3,XNGS,AAPL
6032,2020-01-02 09:30:00.537,296.23,1,XNGS,AAPL
6035,2020-01-02 09:30:00.638,296.21,2,XNGS,AAPL
6039,2020-01-02 09:30:00.701,296.27,424836,XNGS,AAPL
6040,2020-01-02 09:30:00.701,296.27,424836,XNGS,AAPL
6044,2020-01-02 09:30:00.724,296.265,10,XNGS,AAPL
6046,2020-01-02 09:30:00.758,296.265,10,XNGS,AAPL
6047,2020-01-02 09:30:00.758,296.265,10,XNGS,AAPL
6048,2020-01-02 09:30:00.758,296.26,10,XNGS,AAPL
6052,2020-01-02 09:30:00.835,296.26,9,XNGS,AAPL
6053,2020-01-02 09:30:00.835,296.25,35,XNGS,AAPL
6054,2020-01-02 09:30:00.835,296.25,1000,XNGS,AAPL
6055,2020-01-02 09:30:00.835,296.25,17,XNGS,AAPL
6056,2020-01-02 09:30:00.835,296.25,563,XNGS,AAPL
6057,2020-01-02 09:30:00.835,296.25,437,XNGS,AAPL
6058,2020-01-02 09:30:00.835,296.25,100,XNGS,AAPL
6059,2020-01-02 09:30:00.835,296.25,1,XNGS,AAPL
6060,2020-01-02 09:30:00.835,296.25,8,XNGS,AAPL
6061,2020-01-02 09:30:00.835,296.25,20,XNGS,AAPL
6062,2020-01-02 09:30:00.835,296.25,100,XNGS,AAPL
6063,2020-01-02 09:30:00.835,296.25,35,XNGS,AAPL
6064,2020-01-02 09:30:00.835,296.25,10,XNGS,AAPL
6065,2020-01-02 09:30:00.835,296.25,300,XNGS,AAPL
6066,2020-01-02 09:30:00.835,296.25,22,XNGS,AAPL
6090,2020-01-02 09:30:00.863,296.26,30,XNGS,AAPL
6096,2020-01-02 09:30:00.909,296.27,36,XNGS,AAPL
6100,2020-01-02 09:30:00.931,296.27,10,XNGS,AAPL
6101,2020-01-02 09:30:00.942,296.27,44,XNGS,AAPL
6102,2020-01-02 09:30:00.942,296.28,23,XNGS,AAPL
6103,2020-01-02 09:30:00.942,296.28,13,XNGS,AAPL
6104,2020-01-02 09:30:00.942,296.28,101,XNGS,AAPL
6108,2020-01-02 09:30:00.960,296.29,1,XNGS,AAPL
6109,2020-01-02 09:30:00.960,296.29,5,XNGS,AAPL
6112,2020-01-02 09:30:00.962,296.29,4,XNGS,AAPL
6114,2020-01-02 09:30:00.962,296.29,1,XNGS,AAPL
6116,2020-01-02 09:30:00.965,296.28,19,XNGS,AAPL
6117,2020-01-02 09:30:00.965,296.27,96,XNGS,AAPL

**Comment by finnhubio** [comment]
Hi there,

This looks like a timezone issue since you are showing GMT time above. Please convert the timestamp to EST to get the correct result.
