### ISSUE TITLE
Weekly call skipping weeks

### ISSUE THREAD

**Issue by migore** [finnhubio/Finnhub-API#458]
Hello,

I'm fetching weekly data for stocks and I notice that it's skipping weeks.

### Date/time of the issue

I've noticed 2 weeks ago, it's still happening

### Which endpoints are you having problems with ?

`https://finnhub.io/api/v1/stock/candle?symbol=AAPL&resolution=W&from=1603298999&to=1615302599&token=<token>`

### How to reproduce the error and what is the expected result?

Call `https://finnhub.io/api/v1/stock/candle?symbol=AAPL&resolution=W&from=1603298999&to=1615302599&token=<token>`

The endpoint returned me the timestamps on the `Epoch date` column below, I used https://www.epochconverter.com/ to convert to a date and I see the same behavior in my scripts. It is returning data for every 2 weeks, and not weekly OHLC

| Epoch date | Human-readable date (GMT) |
| -----------| -------------             |
| 1603670400 | 2020-10-26 00:00:00 |
| 1604880000 | 2020-11-09 00:00:00 |
| 1606089600 | 2020-11-23 00:00:00 |
| 1607299200 | 2020-12-07 00:00:00 |
| 1608508800 | 2020-12-21 00:00:00 |
| 1609718400 | 2021-01-04 00:00:00 |
| 1611532800 | 2021-01-25 00:00:00 |
| 1612742400 | 2021-02-08 00:00:00 |
| 1613952000 | 2021-02-22 00:00:00 |
| 1615161600 | 2021-03-08 00:00:00 |

For example:

| Epoch date | Human-readable date (GMT) |
| -----------| -------------             |
| 1604880000 | 2020-11-09 00:00:00 |
| 1606089600 | 2020-11-23 00:00:00 |

It's two weeks between `2020-11-23` and `2020-11-09`, I would expect to `2020-11-16` that is a monday between those two dates. The same behavior happens in other stocks.

Thanks!

**Comment by Rzfeng** [comment]
I am seeing this same issue, any update or fixes?

**Comment by finnhubio** [comment]
Hi guys, the issue should be corrected now.
