### ISSUE TITLE
Earnings Calendar is empty

### ISSUE THREAD

**Issue by luis003** [finnhubio/Finnhub-API#459]
https://finnhub.io/api/v1/calendar/earnings?from=2021-09-01&to=2021-09-07&symbol=AAPL&token=

Response
{"earningsCalendar":[]}

**Comment by finnhubio** [comment]
Hi there,

A free account only has access to 1 month of earnings calendar data. If you have a subscription and believe this is an error, please shoot us an email at support@finnhub.io
