### ISSUE TITLE
Crypto access down?

### ISSUE THREAD

**Issue by mateodelnorte** [finnhubio/Finnhub-API#46]
Hi there,

I'm noticing BTCUSDT on binance is moving, but I'm getting no ticks on the websocket. I also notice the UI is not updating on https://finnhub.io.  

In addition, this example from the docs returns `undefined`:
```
const request = require('request');

request('https://finnhub.io/api/v1/crypto/symbol?exchange=binance&token=[my token]', { json: true }, (err, res, body) => {
  if (err) { return console.log(err); }
  console.log(body.url);
  console.log(body.explanation);
});

```

**Comment by finnhubio** [comment]
I just tried this in the browser: [https://finnhub.io/api/v1/crypto/symbol?exchange=binance](https://finnhub.io/api/v1/crypto/symbol?exchange=binance) . It works fine

**Comment by mateodelnorte** [comment]
LOOOL. Did y'all just see this and restart the service? My websocket disconnected. Upon reconnect now it works.

**Comment by mateodelnorte** [comment]
Can you please create a status page and provide alerts for yourselves, so you know when these things go down?

**Comment by finnhubio** [comment]
Yes we are deploying new version and a new database this afternoon. It might caused the issue with WebSocket. We will keep monitoring the issue
