### ISSUE TITLE
Inconsistent data in company financials

### ISSUE THREAD

**Issue by 70853n** [finnhubio/Finnhub-API#47]
Dear finnhub team,

I notice more and more data in the company financials beeing not in alignment with the 10-K filings.

Examples:
1) Boeing (BA) 
 - Annual `revenue` for 2019 is not as in the SEC filling
2) Tanger Outlets (SKT) 
 - annual `totalOperatingExpense` for 2017 is not as in the SEC filling
 - annual `netIncome` for 2016 is not as in the SEC filling

Best regards

**Comment by finnhubio** [comment]
Hi,

It's just a matter of standardization to make the data consistent across all companies in the US and globally. The revenue breakdown for BA: Sale of products: 74,353 + sale of some services : 10,465   = 84,818

If you are looking for as reported data (not standardized), we are working on a new endpoint for that

**Comment by 70853n** [comment]
Hi and thanks for the reply. That's great you're working on such an enpoint!

I understand there are different methods of standardization, from the current endpoint or it's responses it's not clear whether all the periods are standardized by the same method. It seems odd though that most of the data is consistent with the annual reports or other APIs, but just some few values are off. 

So you say for all periods returned by you API the standardization method is the same?

**Comment by finnhubio** [comment]
We use the same method across all companies and all periods. We have certified accountants doing this job.
