### ISSUE TITLE
Issue with candles results and unclear candle size limit

### ISSUE THREAD

**Issue by borysosetinskyi** [finnhubio/Finnhub-API#491]
I have plan: Enterprise
I am testing your service with production API Key. 
What is happing with your quality ?

I did a few requests and got useless responses. 

The first I did for OANDA
https://finnhub.io/api/v1/forex/candle?symbol=OANDA:EUR_USD&resolution=1&from=1654056000&to=1655956800&token=THIS_MY_TOKEN
I got 2953 candles. 
The start candle  has time 2022-06-21T05:10+03:00[UTC+03:00]
The end candle has time 2022-06-23T06:59+03:00[UTC+03:00]
The question is there any limit for candle response? Why 2953? 

The second I did for BITFINEX
https://finnhub.io/api/v1/crypto/candle?symbol=BITFINEX:BTCUSD&resolution=1&from=1654056000&to=1655956800&token=THIS_MY_TOKEN
I got only  120 candles. Really??? only 120???
The start candle  has time 2022-06-23T05:01+03:00[UTC+03:00]
The end candle has time 2022-06-23T07:00+03:00[UTC+03:00]

The third one was for BINANCE
https://finnhub.io/api/v1/crypto/candle?symbol=BINANCE:BTCUSDT&resolution=1&from=1654056000&to=1655956800&token=THIS_MY_TOKEN
The response was {"s":"no_data"}

It is absolute useless if I don't know how it works.  will it return all candles or there is limit ? Why it is different?  When I tested your demo it was better then production. How is it possible???

**Comment by finnhubio** [comment]
Hi, please shoot an email to support@finnhub.io to get support for your plan. We do not provide support here on the community forum.
