### ISSUE TITLE
Cannot access 20 years of minute-level US stock price data? 

### ISSUE THREAD

**Issue by zkghost** [finnhubio/Finnhub-API#5]
Hey there,

Enjoy the service, thank you. 
Have a question though: the table [here](https://finnhub.io/docs/api#stock-candles) says that I should be able to pull 1 minute for 20 years. But even if I go back 5 years, my queries return no data. Can you explain the discrepancy and what I should expect?

**Comment by finnhubio** [comment]
Hi,

The issue is you can only request about 2-3 months of 1 minute data at a time. Plz do so iteratively to get all the historical data needed.

**Comment by zkghost** [comment]
@finnhubio Thanks for your update. I am not sure why it was failing (I was picking valid weekdays 10 years ago) but pulling in chunks seems to have helped.

I've noticed another issue though: Now I am only getting a month or less of data for each symbol I pull. At some point I was able to pull the full 20 years, but now it seems I don't find any data past the first month, and only get 100~2000 price points for the first month, and none after. 

Is there some sort of throttling going on here? I am walking through all the US symbols and it seems like this started occurring after I hit symbols starting with 'E'.

**Comment by zkghost** [comment]
Some output for context:
```
pulling data for stock {'description': 'WATFORD HOLDINGS LTD', 'displaySymbol': 'WTRE', 'symbol': 'WTRE'} from exchange US from 2020-02-10 to 2020-03-09                                      

[09-Mar-20 12:48:00-INFO][_request] - method: GET
[09-Mar-20 12:48:00-INFO][_request] - url: https://finnhub.io/api/v1/stock/candle
[09-Mar-20 12:48:00-INFO][_request] - query_params: {'symbol': 'WTRE.US', 'resolution': 1, 'from': 1581321600, 'to': 1583737200, 'token': <TOKEN>}
[09-Mar-20 12:48:00-INFO][_request] - rate limit: 1
found 508 rows for symbol {'description': 'WATFORD HOLDINGS LTD', 'displaySymbol': 'WTRE', 'symbol': 'WTRE'}                                                                                  

===========================

pulling data for stock {'description': 'WATFORD HOLDINGS LTD', 'displaySymbol': 'WTRE', 'symbol': 'WTRE'} from exchange US from 2020-01-13 to 2020-02-10                                      

[09-Mar-20 12:48:02-INFO][_request] - method: GET
[09-Mar-20 12:48:02-INFO][_request] - url: https://finnhub.io/api/v1/stock/candle
[09-Mar-20 12:48:02-INFO][_request] - query_params: {'symbol': 'WTRE.US', 'resolution': 1, 'from': 1578902400, 'to': 1581321600, 'token': <TOKEN>}
[09-Mar-20 12:48:02-INFO][_request] - rate limit: 1
no data found for symbol {'description': 'WATFORD HOLDINGS LTD', 'displaySymbol': 'WTRE', 'symbol': 'WTRE'} on exchange {'code': 'US', 'currency': 'USD', 'name': 'US exchanges'} for dates 2020-01-13 to 2020-02-10                                                                         
```

Here I am counting rows as the number of elements returned in the `o,h,l,c,v` lists. If status is not ok, I count that as "no data found". 

You can see the first pull there were 508 candles found. On the second pull, there were none. 
Looking at trading view for this stock: https://www.tradingview.com/symbols/NASDAQ-WTRE/ There is definitely 12M of history at least. 

This now happens for every pull I make. Any assistance/explanation you can provide would be helpful.

**Comment by zkghost** [comment]
Seems like #16 is the cause -- I will close this now and if things aren't happy after midnight I will re-open.
