### ISSUE TITLE
Sandbox API key fails to authenticate

### ISSUE THREAD

**Issue by qiuzman** [finnhubio/Finnhub-API#500]
I have a vuejs SPA I have setup to test our Finnhub and using my free API key I am able to use the free features but I wanted to test out the sandbox API which has access to all API endpoints but it returns "Failed to load resource: the server responded with a status of 401 (Unauthorized)".

My axios request is as follows:
`      const loadData = () => {
        finnhubAPI.get('/api/v1/stock/symbol?exchange=US&token=sandbox_keyblahblahblah')
        .then((response) => {
          stockTickers.value = response.data
          console.log(stockTickers.value)
        })
        .catch(() => {
          console.log('API request failed')
        })
      }`

**Comment by finnhubio** [comment]
Hi there,

We no longer support sandbox environment at this point.
