### ISSUE TITLE
what happen to sandbox API

### ISSUE THREAD

**Issue by hesnoh** [finnhubio/Finnhub-API#503]
I can't find Sandbox API in the Dashboard
<img width="611" alt="Screen Shot 2022-09-21 at 9 50 43 AM" src="https://user-images.githubusercontent.com/77089461/191522578-a5875b8d-61ce-4338-84e8-0ef06102a390.png">

**Comment by hretraite** [comment]
Same problem for me

**Comment by finnhubio** [comment]
Hi, please see #504
