### ISSUE TITLE
No data return for Crypto endpoint

### ISSUE THREAD

**Issue by wickedapp** [finnhubio/Finnhub-API#508]
I'm on Enterprise subscription. There is no data return for Crypto endpoint

https://finnhub.io/api/v1/crypto/candle?symbol=BINANCE:BTCUSDT&resolution=5&from=1641340800&to=1669852800&token={my_token}

Please resolve ASAP

**Comment by V12EF** [comment]
same here ! All exchanges are not working !

**Comment by finnhubio** [comment]
This happened due to the unexpected US IPs ban from Binance. The issue was resolved last month. Our apologies for the inconvenience.
