### ISSUE TITLE
Incorrect data

### ISSUE THREAD

**Issue by sankalpbhatia20** [finnhubio/Finnhub-API#509]
Hey! I wanted to retrieve the Earnings Call of all the companies from 6th Dec, 2022 to 7th Dec, 2022. However, when I cross-checked it seems to have been given incorrect data. 

Oracle didn't have its Earnings Call on that date but it still gave me its data.

This is the response I got for Oracle

```
        {
            "date": "2022-12-07",
            "epsActual": null,
            "epsEstimate": 1.2003,
            "hour": "amc",
            "quarter": 2,
            "revenueActual": null,
            "revenueEstimate": 12224225407,
            "symbol": "ORCL",
            "year": 2023
        },
```

The latest update on Oracle Investor's website was on 5th Dec where they wrote:
"_Oracle Corporation today announced that its second quarter fiscal year 2023 results will be released on Monday, December 12th, after the close of the market._"

Any help on this front?

Thanks!

**Comment by finnhubio** [comment]
Hi there,

The date that you are seeing is "projected" earnings date and will be changed later as we approach the earnings date. The date is usually updated to the confirmed date when the earnings date is close.
