### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by yvesn7** [finnhubio/Finnhub-API#51]
Hello all of a sudden my API key quit working this morning. Getting "Invalid API Key" returns. I generated another one which worked for a few minutes, and now it's happening again. All call return "Invalid API key". 

Are you having issues with your authentication servers and if so what is the ETA for fix?

Thank you.

**Comment by yvesn7** [comment]
It appears to back now, but leaving the issue open as it has been flaky on and off all morning. Thank you

**Comment by ruralcoder** [comment]
I have the exact same problem.

I thought my key expired or something, but I cannot even login to renew.

**Comment by yvesn7** [comment]
It started happening again this afternoon. I have a whole day of data wasted because of this.

**Comment by finnhubio** [comment]
#53
