### ISSUE TITLE
earnings calendar returns no hour value any more

### ISSUE THREAD

**Issue by bobten2005** [finnhubio/Finnhub-API#510]
request:
https://finnhub.io/api/v1/calendar/earnings?from=2023-01-01&to=2023-02-1&token=xxx=MSFT

response:
{"earningsCalendar":[{"date":"2023-01-23","epsActual":null,"epsEstimate":2.3402,"hour":"","quarter":2,"revenueActual":null,"revenueEstimate":53763821382,"symbol":"MSFT","year":2023}]}

you can see than the hour has no values anymore

**Comment by goldTpython** [comment]
3 emails in last 20 days about this subject, 0 reply from support, looks this company is dead

**Comment by bobten2005** [comment]
> 3 emails in last 20 days about this subject, 0 reply from support, looks this company is dead

are you sure? what a pity

**Comment by goldTpython** [comment]
I sent them 3 emails to support, 1 to billing and other to sales in last 20 days, 0 reply, and as you can see here no reply neither. Try your self writing to support, maybe they need pressure or more likely they are a zombie website, a pity so many hours waste with their APIs integration

**Comment by bobten2005** [comment]
> I sent them 3 emails to support, 1 to billing and other to sales in last 20 days, 0 reply, and as you can see here no reply neither. Try your self writing to support, maybe they need pressure or more likely they are a zombie website, a pity so many hours waste with their APIs integration

I mailed to supports, got no reply neither

**Comment by bobten2005** [comment]
> I sent them 3 emails to support, 1 to billing and other to sales in last 20 days, 0 reply, and as you can see here no reply neither. Try your self writing to support, maybe they need pressure or more likely they are a zombie website, a pity so many hours waste with their APIs integration

i got some information from linkin, this compary has been closed down on Jan 13

**Comment by finnhubio** [comment]
Apologies for the late update on this. The issue should be corrected on our end now.
