### ISSUE TITLE
{'s': 'no_data'} with resolution 1 using candles

### ISSUE THREAD

**Issue by Radhe-0** [finnhubio/Finnhub-API#512]
this is my code:

```python
import finnhub
finnhub_client = finnhub.Client(api_key="KEY")
candles = finnhub_client.stock_candles('QQQ', '1', 1590988249, 1591852249)

print(candles)
```
and this is the output:

```
{'s': 'no_data'} 
```

I have tried with other dates and symbols but always the same with resolution = '1'

**Comment by finnhubio** [comment]
Hi there,

If you are on the free plan, you will need to try a more recent timestamp to get the data. For example,

candles = finnhub_client.stock_candles('QQQ', '1', 1679288102, 1680497702)

**Comment by Radhe-0** [comment]
> Hi there,
> 
> If you are on the free plan, you will need to try a more recent timestamp to get the data. For example,
> 
> candles = finnhub_client.stock_candles('QQQ', '1', 1679288102, 1680497702)

Where can I see the limitations more specifically?

**Comment by finnhubio** [comment]
It's on the docs here: https://finnhub.io/docs/api/stock-candles (Free Tier: 1 year of historical data and new updates)

Or you can also see your free plan benefit here: https://finnhub.io/pricing
