### ISSUE TITLE
not able to access Indian stock exchange  data  

### ISSUE THREAD

**Issue by Sakibdevlekar** [finnhubio/Finnhub-API#513]
This API is not working for  NSE and BSE  stocks 

for example :

finnhubClient.quote("AAPL", (error, data, response) => {
    console.log(data)
});

output: 
Quote {
  o: 170.09,
  h: 170.35,
  l: 167.54,
  c: 168.54,
  pc: 169.59,
  d: -1.05,
  dp: -0.6191
}

with NASDAQ-listed stocks it works fine   but if I 

finnhubClient.quote("TCS", (error, data, response) => {
    console.log(data)
}); 

not giving any output for TCS
TCS is  Listed on the Indian stock exchange NSE and BSE

**Comment by chetanyachopra22** [comment]
+1 api is working fine for stocks other than .NS / .BO `403` as shown below
<img width="665" alt="Screenshot 2024-08-26 at 12 05 03 AM" src="https://github.com/user-attachments/assets/cc586772-49f4-43d5-bcb8-708a1cb4fc5d">
<img width="675" alt="Screenshot 2024-08-26 at 12 05 19 AM" src="https://github.com/user-attachments/assets/29e32360-ca61-4175-a54c-466187af2e3b">

**Comment by chetanyachopra22** [comment]
#363 
Above issue was also not addressed completely .. seems like extremely old and never attended issue

**Comment by chetanyachopra22** [comment]
@finnhubio  Please mark this as `BUG`

**Comment by finnhubio** [comment]
Hi guys, adding .NS and .BO to the symbol is the correct way to access Indian stocks such as SBIN.NS. However, this is simply not available on the free plan. If you have a question about subscriptions and access, please shoot us an email.
