### ISSUE TITLE
Free Tier Access

### ISSUE THREAD

**Issue by simplexityware** [finnhubio/Finnhub-API#534]
Hi,

Can a free tier account perform the following sample codes on your https://finnhubio.github.io?

```
import finnhub
finnhub_client = finnhub.Client(api_key="YOUR API KEY")

res = finnhub_client.stock_candles('AAPL', 'D', 1590988249, 1591852249)
print(res)

import pandas as pd
print(pd.DataFrame(res))

print(finnhub_client.aggregate_indicator('AAPL', 'D'))

```

I have encountered "FinnhubAPIException: FinnhubAPIException(status_code: 403): You don't have access to this resource."

Please advise.  Thank you.

**Comment by d0rb** [comment]
Same here : 

import asyncio
import requests
import finnhub
finnhub_client = finnhub.Client(api_key="API KEY")
res = finnhub_client.stock_candles('AAPL', 'D', 1590988249, 1591852249)
print(res)



API Exception for AAPL: FinnhubAPIException(status_code: 403): You don't have access to this resource.

**Comment by seraphim2008** [comment]
same issue

**Comment by sravie24** [comment]
was this resolved ? i am getting the same issue. Can i know the solution for this ?

**Comment by d0rb** [comment]
> was this resolved ? i am getting the same issue. Can i know the solution for this ?

Nope , just dropped this API.
[finnhubio](https://github.com/finnhubio) Doesn't seems to care as well and it seems as this API is not maintained anymore ( look at the issues open ) .

**Comment by finnhubio** [comment]
Hey guys, this is NOT an issue with our API. If you are accessing a premium endpoint, you would need a premium subscription for that data. Otherwise, the API will return a 403 error as you don't have access to that endpoint.

**Comment by newbie321** [comment]
@finnhubio , so is there a working endpoint for the free tier to access EOD daily candle data?
