### ISSUE TITLE
What does "periods of financial statements" mean?

### ISSUE THREAD

**Issue by Xeoncross** [finnhubio/Finnhub-API#55]
For example, the basic plan offers "5 periods of financial statements"

What does that mean? Are we talking about 5 years? 5 quarters? Is this from the current date?

**Comment by finnhubio** [comment]
Hi 5 periods means 5 years + 5 quarters. We will return 5 latest data points in our database. For example if we have data until 2019 only, we will return data for 2015,2016,2017,2018,2019.
