### ISSUE TITLE
TSLA data not up to date with pre-hours

### ISSUE THREAD

**Issue by ruralcoder** [finnhubio/Finnhub-API#56]
Hi guys,

Been up since 1AM looking at the data and seeing issues again

According to Robinhood Tesla is already at $563 once again I am missing out on my buying.

https://finnhub.io/api/v1/quote?symbol=TSLA&token=xxxx
```
{"c":505,"h":513.69,"l":474,"o":477.3,"pc":434.29,"t":1585056600}
```
TSLA,AMD,RUB are suffering

MSFT on the other hand comes in correctly matching Robinhood's pre-hours.

**Comment by finnhubio** [comment]
Duplicate with #39  ?

**Comment by ruralcoder** [comment]
No.

Here is the MSFT data without any interuptions

<img width="550" alt="Screen Shot 2020-03-25 at 10 40 08 AM" src="https://user-images.githubusercontent.com/12993309/77568067-4d037780-6e85-11ea-9f40-1a3d266dd5a2.png">

Here is the TSLA one with interuptions

<img width="547" alt="Screen Shot 2020-03-25 at 10 37 52 AM" src="https://user-images.githubusercontent.com/12993309/77568076-512f9500-6e85-11ea-9866-f9605dd81710.png">

Here is Tesla from Yahoo indicating market fluctuations and not a flat line.

<img width="650" alt="Screen Shot 2020-03-25 at 10 42 54 AM" src="https://user-images.githubusercontent.com/12993309/77568178-7b815280-6e85-11ea-9c54-f0f8b1012b89.png">

**Comment by ruralcoder** [comment]
<img width="396" alt="Screen Shot 2020-03-25 at 11 13 37 AM" src="https://user-images.githubusercontent.com/12993309/77570887-b08fa400-6e89-11ea-9620-4e1540b71b25.png">

Thanks, it started again right now

**Comment by ruralcoder** [comment]
Guys, 

I love what you guys are building, but I also feel there is something fundamentally problematic with your tech stack. Either your code is inconsistently deployed or your data sources are bad or something.  

When you data stops you need to be alerted.  You can use a different data source and the Delta should be zero. Even if you check say 1/min should be valuable. And you need dashboards to observe yours VS theirs.

I am an engineering manager my self, so even though customer findings are a thing, it should not be something that get's through your engineers, product managers and engineering leaders.

Changing the engine in-flight is never easy, and I hope you guys get through this.

**Comment by ruralcoder** [comment]
It momentarily worked and now it stopped again

<img width="396" alt="Screen Shot 2020-03-25 at 11 26 50 AM" src="https://user-images.githubusercontent.com/12993309/77572077-9bb41000-6e8b-11ea-89dc-c608d4f02a2a.png">

**Comment by finnhubio** [comment]
I understand the issue with pre and post market which we are discussing in #39 . However, TSLA data did update normally as I just check. Have no idea why you think it doesn't move. Plz review your code.

**Comment by ruralcoder** [comment]
Sure I will take a look from my end.

My collector pipeline is a simple periodic (poll finnhub -> json decode -> write to influxdb) but I did notice couple of JSON decoding errors.  

Perhaps that triggers something. Just added a metric to record occurrences of these errors and logging of the verbatim string attempted to be decoded. Let's see what we fish out..Perhaps I am exceeding my quota.

**Comment by ruralcoder** [comment]
Here is my Rubicon pipeline which has the same problem

Data from Finnhub
<img width="393" alt="Screen Shot 2020-03-25 at 12 05 32 PM" src="https://user-images.githubusercontent.com/12993309/77575611-04ea5200-6e91-11ea-9929-8e726e09b312.png">

Yahoo
<img width="647" alt="Screen Shot 2020-03-25 at 12 05 41 PM" src="https://user-images.githubusercontent.com/12993309/77575620-09af0600-6e91-11ea-8103-91e25abb44ff.png">

**Comment by ruralcoder** [comment]
And now it's back....

<img width="388" alt="Screen Shot 2020-03-25 at 12 08 58 PM" src="https://user-images.githubusercontent.com/12993309/77575915-73c7ab00-6e91-11ea-9dc6-f01ae83b5d21.png">

**Comment by ruralcoder** [comment]
And here is my AMD pipeline

<img width="303" alt="Screen Shot 2020-03-25 at 12 13 18 PM" src="https://user-images.githubusercontent.com/12993309/77576208-06684a00-6e92-11ea-981d-1d6501374e97.png">

<img width="1063" alt="Screen Shot 2020-03-25 at 12 15 29 PM" src="https://user-images.githubusercontent.com/12993309/77576608-b76ee480-6e92-11ea-8b18-9f2d2648c5f8.png">

**Comment by ruralcoder** [comment]
A different view of AMD within the past 30 minute at a polling rate of 1 every 10 seconds. I only get 88 data points when we should have had 180. Thats a 52% fail rate in which I get all fields 0 values.

<img width="1057" alt="Screen Shot 2020-03-25 at 12 47 26 PM" src="https://user-images.githubusercontent.com/12993309/77579052-dff8dd80-6e96-11ea-9300-10881e9a1c8b.png">

**Comment by 0x2b543c** [comment]
@ruralcoder I am experiencing a similar issue. I'm trying to get 30M resolution data for TSLA, SPY, and others but am receiving large holes in the data set.

For example if I make a call for SPY and set the start date to 2020-01-01 (and converting to UNIX timestamp for the actual call) it returns data from 1/1 through 1/9 and then jumps from 1/9 to 3/24. If I set the start date to 2020-02-01 it gives me data from 2/1 through 2/10 and then jumps to 3/2.

I thought it was because I was using the free plan so I upgraded to the basic plan and am still having the same issue.

**Comment by ruralcoder** [comment]
so from a previous threat the timestamp is not that of the quote as it seems 

As a timestamp I add the time of my server.

But the holes are there in some stock quotes more than others. e.g. MSFT has the least, and AMD has the most. But I also see stale data for hours. 

I am trying to add better monitoring from my side. 

Would love to see finnhub more stable.

**Comment by monism123** [comment]
@ruralcoder I have the same issue (with all symbols), also the covid data has not been updated for 2 days now.

**Comment by finnhubio** [comment]
Please see #39 for the update . Feel free to reopen if you guys still encounter the issue.
