### ISSUE TITLE
TSX data with WebSockets, is it possible?

### ISSUE THREAD

**Issue by saiOnline13** [finnhubio/Finnhub-API#58]
Would it be possible to get TSX quote data with WebSockets? Its working fine for US stocks. I wonder if there is any way to pull the TSX real time data. Thanks.

**Comment by finnhubio** [comment]
hi we do not support that at the moment.

**Comment by saiOnline13** [comment]
Thanks for the reply. Any possibility of adding this feature for Canadian exchanges? in near future?

**Comment by finnhubio** [comment]
Hi, yes we do have plan to support it. Will keep you posted !

**Comment by saiOnline13** [comment]
Thank you. I wait. :)
