### ISSUE TITLE
Incorrect data

### ISSUE THREAD

**Issue by tmorgangithub** [finnhubio/Finnhub-API#59]
Hi,

	Your data seems to be way off.  I've looked up data for several symbols recently and I keep getting numbers that are off.

	Here is an example of looking up the data for Squaer(SQ) today between 9:29 and 9:32 and the numbers do not match with at least two other applications (Thinkorswim from Ameritrade and E*Trade Pro) which both match with each other:

		https://finnhub.io/api/v1/stock/candle?symbol=SQ&resolution=1&from=1585232940&to=1585233120&token=MY_TOKEN_WAS_USED_HERE
		
		And received following output:
		
			{"c":[57.6563,57.865,57.7429,58.3193],"h":[57.97,57.88,57.97,58.35],"l":[57.6563,57.45,57.71,57.68],"o":[57.8961,57.5701,57.9099,57.7],"s":"ok","t":[1585232940,1585233000,1585233060,1585233120],"v":[132294,116960,101552,149928]}
			
	Is it possible for somebody in your team to look at this problem as I am considering your data source for serious analysis and market monitoring and as it stands it is unusable?

Thanks,

Thomas

**Comment by finnhubio** [comment]
Comparing data like this will never work. We do not know exactly which exchanges E*trade and TDAmeritrade get their data from. There are 13 exchanges in the US. If you are not paying for data, you probably just got data from a small subset of exchanges.

**Comment by tmorgangithub** [comment]
How can data be different?  Data should be consistent across regardless of the tool I use, otherwise I am fooling myself as a technical trader.  I have to be able to trust the data.

Having said that, are you saying that if I subscribe again, the data I see should change?

Thanks,

Thomas

________________________________

**Comment by tmorgangithub** [comment]
Also, I can see a difference of pennies between sources, but in this case I am talking about dollars.

**Comment by Torgny-q** [comment]
Another case of incorrect data. Evaluating your service I used an example URL 

https://finnhub.io/api/v1/quote?symbol=AAK.ST&token=bq...                   (token is hidden)

Most of the times I get a correct respons;

{"c":159.95,"h":164.1,"l":159.75,"o":164.1,"pc":163,"t":1586339116}

but sometimes i get a corrupt response;

{"c":174.8,"h":178.05,"l":174.35,"o":178.05,"pc":178.25,"t":1586338910}

Crosschecked with my trading station and all closures are around 160 SEK

**Comment by finnhubio** [comment]
> Another case of incorrect data. Evaluating your service I used an example URL
> 
> https://finnhub.io/api/v1/quote?symbol=AAK.ST&token=bq... (token is hidden)
> 
> Most of the times I get a correct respons;
> 
> {"c":159.95,"h":164.1,"l":159.75,"o":164.1,"pc":163,"t":1586339116}
> 
> but sometimes i get a corrupt response;
> 
> {"c":174.8,"h":178.05,"l":174.35,"o":178.05,"pc":178.25,"t":1586338910}
> 
> Crosschecked with my trading station and all closures are around 160 SEK

this error has been addressed a few weeks ago.
