### ISSUE TITLE
Dividends not up to date

### ISSUE THREAD

**Issue by md-pt** [finnhubio/Finnhub-API#60]
Dear Finnhub team,

hopefully you are doing well in this uncertain time.

I wanted to highlight an issue in the dividend API endpoint, which I experienced for multiple tickers.
Example: The response for the dividend call of ALB (https://finnhub.io/api/v1/stock/dividend?symbol=ALB&from=2019-02-01&to=2020-03-26&token=) is

`[{'symbol': 'ALB', 'date': '2019-12-12', 'amount': 0.368}, {'symbol': 'ALB', 'date': '2019-09-12', 'amount': 0.368}, {'symbol': 'ALB', 'date': '2019-06-13', 'amount': 0.368}, {'symbol': 'ALB', 'date': '2019-03-14', 'amount': 0.368}]`

But there was a dividend payment on 12-03-2020 (see https://www.nasdaq.com/market-activity/stocks/alb/dividend-history).

**Comment by finnhubio** [comment]
Our apology for the late update. Should be fixed now.
