### ISSUE TITLE
Missing values for fields H, L, O, PC

### ISSUE THREAD

**Issue by ruralcoder** [finnhubio/Finnhub-API#61]
Several fields `H, L, O, PC` have zeroes as value...

This happens with MSFT, TSLA and AMD 
```
"{"c":517.96,"h":0,"l":0,"o":0,"pc":0,"t":1585296137}"
```
Running with `https://finnhub.io/api/v1/quote?symbol=TSLA&token=xxx&trade=true`

But for RUBI those are present, but it seems different, the values are present but the 'c' not changing at all. (I opened #62) 
```
"{"c":6.06,"h":6.14,"l":5.62,"o":5.74,"pc":5.75,"t":1585296696}"
```
Running with `https://finnhub.io/api/v1/quote?symbol=RUBI&token=xxx&trade=true`

**Comment by finnhubio** [comment]
Just a bug from yesterday's release. Should be fixed now.
