### ISSUE TITLE
The RUBI pipeline code is not like the others

### ISSUE THREAD

**Issue by ruralcoder** [finnhubio/Finnhub-API#62]
The RUBI symbol returns stale data, with the H,L,O,PC fields filled

"{"c":6.06,"h":6.14,"l":5.62,"o":5.74,"pc":5.75,"t":1585296696}"
Running with https://finnhub.io/api/v1/quote?symbol=RUBI&token=xxx&trade=true

While,  MSFT, TSLA and AMD symbols produce a buggy output (i opened another issue for the zeros #61 )

"{"c":517.96,"h":0,"l":0,"o":0,"pc":0,"t":1585296137}"
Running with https://finnhub.io/api/v1/quote?symbol=TSLA&token=xxx&trade=true

Meaning: 
 RUBI pipeline code is different from the other 3 (as in code deployment issue)
 RUBI data not pre-market (always stuck at $6.06) (as in &trade=true was not deployed)

**Comment by finnhubio** [comment]
Just a bug from yesterday's release. Should be fixed now.
