### ISSUE TITLE
Not receiving stream data for various symbols.

### ISSUE THREAD

**Issue by JelteV** [finnhubio/Finnhub-API#65]
I'm trying to read the (real time) trade data using the websocket example from the documentation (see: [websocket example](https://finnhub.io/docs/api#websocket-price). I'm fiddling with it a few days now and from today I do not receive any data for all the symbols I tried: `AMD`, `MSFT`, `AAPL`, `TSLA`. Is maintenance still going on?

My code:

```
var WebSocket = require("websocket").w3cwebsocket;

const socket = new WebSocket('wss://ws.finnhub.io?token=<my-token>');

// Connection opened -> Subscribe
socket.addEventListener('open', function (event) {
    // socket.send(JSON.stringify({'type':'subscribe', 'symbol': 'TSLA'}))
    // socket.send(JSON.stringify({'type':'subscribe', 'symbol': 'AMD'}))
    socket.send(JSON.stringify({'type':'subscribe', 'symbol': 'MSFT'}))
});

// Listen for messages
socket.addEventListener('message', function (event) {
    console.log('Message from server ', event.data);
});

// Unsubscribe
var unsubscribe = function(symbol) {
    socket.send(JSON.stringify({'type':'unsubscribe','symbol': symbol}))
} 
```

The only output I get is:

```
Message from server  {"type":"ping"}
Message from server  {"type":"ping"}
Message from server  {"type":"ping"}
Message from server  {"type":"ping"}
Message from server  {"type":"ping"}
Message from server  {"type":"ping"}
....

**Comment by finnhubio** [comment]
It's working normally yesterday. Can you try again on Monday instead ? Market is closed right now so I can't test it for you.

**Comment by JelteV** [comment]
Ohw man... is Saterday... , sorry!

**Comment by Ayuxxh** [comment]
OMG lol i am so dumb i was searching for hours for why isnt this working TwT thanks

**Comment by The-big-boy** [comment]
I usually Subscribe to a crypto index to test the code on weekends like "BINANCE:BTCUSDT", this trades 24/7
