### ISSUE TITLE
HTTP 500 for lots of TSX and TSXV symbols.

### ISSUE THREAD

**Issue by saiOnline13** [finnhubio/Finnhub-API#66]
It started Friday afternoon around 3 PM. Getting HTTP 500 for lots of TSX and TSXV symbols.

**Comment by finnhubio** [comment]
Plz follow our guideline and provide a reproducible example

**Comment by saiOnline13** [comment]
Quote and Candle request fails for almost 50% of symbols traded on exchange. Here are few symbols that gave 500 error. They all used to work fine. It started yesterday evening. 

AHY.UN.TO,  AGU.TO, AGT.TO, AGF.B.TO, AF.TO, AEV.TO, ADW.B.TO, ADW.A.TO, ADC.UN.TO, ACZ.UN.TO, ACR.UN.TO, ACO.Y.TO, ACO.X.TO, ACC.TO, ABK.A.TO, AAR.UN.TO

**Comment by saiOnline13** [comment]
https://finnhub.io/api/v1/quote?token=&symbol=AAR.UN.TO

**Comment by finnhubio** [comment]
It should be ADW-A.TO . For some of other symbols, we simply do not have data for them

**Comment by saiOnline13** [comment]
Thanks for the reply. I just pull the symbols using the exchange API. I just checked it, and I could see that API is also modified from . to - notation.  It used to send ADW.A.TO symbol. Let me refresh symbols and give it a try. Thanks. 

{
    "description": "Andrew Peller Limited",
    "displaySymbol": "ADW-A.TO",
    "symbol": "ADW-A.TO"
  },

**Comment by saiOnline13** [comment]
After symbol refresh, it is working fine. The major change was "." is replaced with "-" in most of the symbols. Thanks for the quick reply. I really appreciate it. :)
