### ISSUE TITLE
Missing Stocks/Currencies

### ISSUE THREAD

**Issue by RomanDrk** [finnhubio/Finnhub-API#68]
Hi,
I've started using your Python API and there's at least 1 stock missing (Tel Aviv Stock exchange): FATTAL, can you add that?
Another issue is that I'd like also to follow ETF's in the Tel Aviv stock exchange, is it possible?
Edited: missing as well all the Forex for NIS (New Israeli Shekels)
Thanks!

**Comment by finnhubio** [comment]
We will look into it
