### ISSUE TITLE
Earnings Calendar end point

### ISSUE THREAD

**Issue by nick-gaudreau** [finnhubio/Finnhub-API#7]
Hi, 

Thanks for the API. 
Is there a way to use query parameters for the Earnings Calendar end points? To have more than the upcoming 7 days by default. Right now it returns the upcoming 7 days and doesn't seem to take in any query param.
Example: This is what I tried... would be great to have something like this that takes in the from and to param:
https://finnhub.io/api/v1/calendar/earnings?from=2020-03-01&to=2020-04-10&token=

**Comment by finnhubio** [comment]
Hi Nick,

We are working on it. You should be able to query data going back to 2003 with our new calendar endpoint. This should be done in a week or 2.

Also, we will support webhook to alert new earnings in real-time. Stay tuned!

**Comment by nick-gaudreau** [comment]
Great and thanks for the quick reply!
Would be really nice if we could also query future earnings date like the upcoming 2 or 3 months ahead to catch the next earnings dates.
Thx

**Comment by nick-gaudreau** [comment]
Sorry one more suggestion is if we could have a query param to pass either one symbols or many comma separated symbols... would be great too. As I can see the earnings end point returns the nest 7 days earnings for every exchanges

**Comment by nick-gaudreau** [comment]
Hi,
Thanks I saw you added the query params `from` and `to`
It still seem to return only 7 days ahead  even for a query with `to` set couple months ahead:
`https://finnhub.io/api/v1/calendar/earnings?from=2020-04-01&to=2020-06-25token=`

Last thing... would it be possible to add a Exchange/market property? Such as: NASDAQ, NYSE, TSX, ...
Thanks!

**Comment by finnhubio** [comment]
We will look into extending it into the futures. Can you elaborate why the "Exchange/market" property can be useful ? How is a symbol not enough ?

**Comment by nick-gaudreau** [comment]
oh its to be able to filter the earnings data by exchange or region. If you look at some websites per example, they let you filter calendar earnings  by **exchange or region**:
https://web.tmxmoney.com/earnings_cal.php
https://finance.yahoo.com/calendar/earnings

There's three options you could give to users calling this endpoint by exchange... 

1st and simpler option. Adding a property to the object result: 
```
{
      "date": "2020-03-04",
      "epsActual": 1.31,
      "epsEstimate": 1.24,
      "hour": "bmo",
      "revenueActual": 1185000000,
      "revenueEstimate": 1170000000,
      "symbol": "ANF",
      **"exchange": "NYSE"**
    }
```
that way the user can query the endpoint and filter it himself.

2nd option, no need to add the exchange property but instead you could add the exchange filter as a query or route. I.e:
https://finnhub.io/api/v1/calendar/earnings?from=2020-03-01&to=2020-04-10&exchange=NYSE&token=
Or:
https://finnhub.io/api/v1/calendar/earnings/NYSE?from=2020-03-01&to=2020-04-10&token=

3rd option is adding both the exchange property and the filter as query or route... but that might be a lot of work. 

So mainly is to be able as a user to query the Earning Endpoint and filter the data by specific exchange or region. I mentioned exchange a lot above but it could also be by region (i.e. USA) but whichever is simpler for you based on your existing code base and logic in place.
