### ISSUE TITLE
TSX: Symbols with a suffix like ".UN" are not working.

### ISSUE THREAD

**Issue by saiOnline13** [finnhubio/Finnhub-API#70]
https://finnhub.io/api/v1/quote?token=&symbol=TCT.UN.TO

The stock symbols API has below description, but when pulled with Quote it's not working. Throws HTTP 500 error.

 {
    "description": "Top 10 Canadian Financial Trust",
    "displaySymbol": "TCT.UN.TO",
    "symbol": "TCT.UN.TO"
  },

Note: They all used to work yesterday morning.

**Comment by finnhubio** [comment]
It should be -UN if we support them.
