### ISSUE TITLE
Commercial Use Subscription

### ISSUE THREAD

**Issue by md-pt** [finnhubio/Finnhub-API#73]
Hi Finnhub team,

This is not a technical question, but I thought the reply might be relevant to other users as well.

Previously, Professional and Ultimate subscriptions allowed commercial use. I saw on your website (Pricing section) that this changed recently.

Is it planned to bring back commercial use at some point?

**Comment by finnhubio** [comment]
Please email support@finnhub.io to discuss commercial use license. Thank you.
