### ISSUE TITLE
CSV payload missing terminator on stock/profile method

### ISSUE THREAD

**Issue by syvHp** [finnhubio/Finnhub-API#74]
The marketCapitalization property is not terminated with a " sign. This causes problems when splitting the string.

**Comment by finnhubio** [comment]
stock/profile return in JSON format so I'm not sure what csv you are talking about. Can you elaborate on the issue ?

**Comment by syvHp** [comment]
Hi,

I found FinnHub from an article on ProgrammableWeb. This is the endpoint I
was hitting
https://finnhub.io/api/v1/stock/profile?symbol=AAPL&token=my_token. I see
it does default to json through the format property (although csv is
permitted). Json works better for me so thanks!
