### ISSUE TITLE
Issue regarding realtime data for National Stock Exchange of India

### ISSUE THREAD

**Issue by nickphelis** [finnhubio/Finnhub-API#8]
Unable to access realtime data of NSE? (India)  through websocket. Is the realtime data being provided for NSE?

**Comment by finnhubio** [comment]
We do not support NSE tick data for retail investors at the moment. If you read the docs again, it says we only support US stocks, forex and crypto through the socket.

If you are looking for enterprise solutions, plz email support@finnhub.io to get integrated with our NSE realtime stream.

**Comment by chetan1507** [comment]
What is the current delay? Is there any plan to support this in the future?
