### ISSUE TITLE
Spreadsheets example request with video

### ISSUE THREAD

**Issue by cristipurdel** [finnhubio/Finnhub-API#80]
Is there any chance to have an example with the googlesheets add on? I tried it but does not really work, maybe I am doing smth wrong, Would be nice to have a video tutorial.
Now I see that there is a description. Are there any chrome limitations?

**Comment by cristipurdel** [comment]
https://docs.cryptosheets.com/providers/finnhub/ is not working
Please make a proper youtube video how to use with cryptosheets since I do not trust to install it as addon without proper tutorial

**Comment by dominhtri1995** [comment]
please reach out to cryptosheets support. On their website, there is a live chat button.

**Comment by finnhubio** [comment]
You can reach out to cryptosheets support via their website. There is a live chat button at the bottom right https://cryptosheets.com/.
