### ISSUE TITLE
Issues with covid19 endpoint

### ISSUE THREAD

**Issue by coffincw** [finnhubio/Finnhub-API#81]
The description on the documentation says that the endpoint just has U.S state data, yet there is also data from Canada as well.

The numbers for canada appear to be copied from the U.S data:
https://finnhub.io/api/v1/covid19/us?token=

`{"state":"Canada","case":135530,"death":2385,"updated":"2020-03-29 14:45:40"}`
`{"state":"United States","case":135530,"death":2385,"updated":"2020-03-29 14:45:40"}`

**Comment by finnhubio** [comment]
Our apology about the issue. 1 of our engineers mistakenly put the data for country into state table. The issue has been fixed
