### ISSUE TITLE
Websocket feed is intermittent, and delayed by *several* minutes

### ISSUE THREAD

**Issue by vgoklani** [finnhubio/Finnhub-API#84]
The websocket feed is intermittent and delayed by *several* minutes.

Please advise. If there are websocket issues, is there a status page?

**Comment by pycoder2020** [comment]
I bumped into same issue https://github.com/finnhubio/Finnhub-API/issues/42 currently I can't use finnhub as real time data provider... But monitoring websockets and belive that some day it will be posible.

**Comment by finnhubio** [comment]
Hi, we are looking into the issue. Will give an update soon.

**Comment by DEllement** [comment]
@finnhubio is this feature normally working?

**Comment by finnhubio** [comment]
this issue has been fixed about a week ago. sr about the late update.
