### ISSUE TITLE
(500 Internal Server Error) Trying to get info сompany profile TECH.L 

### ISSUE THREAD

**Issue by dolnikov** [finnhubio/Finnhub-API#87]
Trying to get info сompany profile TECH.L 
My request:
https://finnhub.io/api/v1/stock/profile?symbol=TECH.L&token=...

Response:
500 Internal Server Error

This problem only with TECH.L
Other tickers work good

**Comment by finnhubio** [comment]
it has been fixed.

**Comment by dolnikov** [comment]
Thanks! now everything is fine with TECH.L 

But I also found companies with a similar problem (here is 387 symbols):
AALR3.SA, ABCB4.SA, ABCP11.SA, ABEV3.SA, AFLT3.SA, AGRO3.SA, AHEB3.SA, ALPA4.SA, ALUP11.SA, AMAR3.SA, ANIM3.SA, APTI3.SA, ARZZ3.SA, ATOM3.SA, AZEV4.SA, B3SA3.SA, BAHI3.SA, BALM4.SA, BAUH4.SA, BAZA3.SA, BBAS3.SA, BBDC4.SA, BBPO11.SA, BBRC11.SA, BBRK3.SA, BBSE3.SA, BBVJ11.SA, BDLL4.SA, BEEF3.SA, BEES4.SA, BGIP3.SA, BIDI4.SA, BIOM3.SA, BKBR3.SA, BMEB4.SA, BMIN3.SA, BMKS3.SA, BNBR3.SA, BNFS11.SA, BOBR4.SA, BOVA11.SA, BPAC11.SA, BPAN4.SA, BPAR3.SA, BPFF11.SA, BRAP4.SA, BRAX11.SA, BRCR11.SA, BRDT3.SA, BRFS3.SA, BRGE3.SA, BRIV3.SA, BRKM5.SA, BRML3.SA, BRPR3.SA, BRSR6.SA, BSEV3.SA, BSLI3.SA, BTOW3.SA, BTTL3.SA, CALI3.SA, CAML3.SA, CARD3.SA, CASN4.SA, CBEE3.SA, CBOP11.SA, CCPR3.SA, CCRO3.SA, CEBR3.SA, CEDO3.SA, CEEB3.SA, CEED4.SA, CEGR3.SA, CEOC11.SA, CEPE5.SA, CESP6.SA, CGAS5.SA, CGRA4.SA, CIEL3.SA, CLSC4.SA, CMIG4.SA, CNES11.SA, COCE5.SA, CPFE3.SA, CPLE6.SA, CPRE3.SA, CRDE3.SA, CRFB3.SA, CRIV3.SA, CRPG5.SA, CSAB3.SA, CSAN3.SA, CSMG3.SA, CSNA3.SA, CSRN3.SA, CTKA4.SA, CTNM4.SA, CTSA3.SA, CVCB3.SA, CXRI11.SA, CXTL11.SA, CYRE3.SA, DASA3.SA, DIRR3.SA, DIVO11.SA, DMMO3.SA, DOHL3.SA, DOMC11.SA, DTCY3.SA, DTEX3.SA, EALT4.SA, ECOO11.SA, ECOR3.SA, ECPR3.SA, EEEL4.SA, EGIE3.SA, EKTR3.SA, ELEK3.SA, ELET6.SA, EMAE4.SA, EMBR3.SA, ENBR3.SA, ENEV3.SA, ENGI4.SA, ENMT4.SA, EQTL3.SA, ESTR4.SA, ESUD11.SA, ESUT11.SA, ETER3.SA, EUCA4.SA, EVEN3.SA, EZTC3.SA, FESA4.SA, FEXC11.SA, FHER3.SA, FIGE3.SA, FIGS11.SA, FIIB11.SA, FLMA11.SA, FLRY3.SA, FMOF11.SA, FNAM11.SA, FNOR11.SA, FPAB11.SA, FRAS3.SA, FRIO3.SA, FRTA3.SA, FSPE11.SA, FSRF11.SA, FSTU11.SA, FVPQ11.SA, GBIO33.SA, GEPA3.SA, GFSA3.SA, GGBR4.SA, GNDI3.SA, GOAU4.SA, GOLL4.SA, GPAR3.SA, GPCP3.SA, GPIV33.SA, GRLV11.SA, GRND3.SA, GSHP3.SA, GUAR3.SA, HAGA4.SA, HAPV3.SA, HBTS5.SA, HETA4.SA, HGBS11.SA, HGCR11.SA, HGRE11.SA, HGTX3.SA, HOOT4.SA, HTMX11.SA, HYPE3.SA, IDNT3.SA, IDVL4.SA, IGBR3.SA, IGTA3.SA, INEP4.SA, IRBR3.SA, ITSA4.SA, ITUB4.SA, JBDU4.SA, JBSS3.SA, JFEN3.SA, JHSF3.SA, JOPA4.SA, JPPC11.SA, JSLG3.SA, JSRE11.SA, KEPL3.SA, KLBN4.SA, KNCR11.SA, KNRE11.SA, LAME4.SA, LCAM3.SA, LEVE3.SA, LIGT3.SA, LINX3.SA, LIPR3.SA, LLIS3.SA, LOGN3.SA, LPSB3.SA, LREN3.SA, LUPA3.SA, LUXM3.SA, MAPT4.SA, MATB11.SA, MBRF11.SA, MDIA3.SA, MEAL3.SA, MERC3.SA, MFII11.SA, MGEL4.SA, MGLU3.SA, MILS3.SA, MMXM3.SA, MNDL3.SA, MNPR3.SA, MOAR3.SA, MOVI3.SA, MRFG3.SA, MRVE3.SA, MSPA3.SA, MSRO3.SA, MTIG4.SA, MTSA4.SA, MULT3.SA, MWET4.SA, MXRF11.SA, MYPK3.SA, NAFG4.SA, NEMO5.SA, NORD3.SA, NUTR3.SA, ODPV3.SA, OFSA3.SA, OIBR4.SA, OMGE3.SA, ONEF11.SA, OSXB3.SA, PABY11.SA, PARD3.SA, PATI4.SA, PCAR4.SA, PDGR3.SA, PEAB4.SA, PETR4.SA, PFRM3.SA, PIBB11.SA, PINE4.SA, PLAS3.SA, PLRI11.SA, PMAM3.SA, PNVL3.SA, POMO4.SA, PORD11.SA, POSI3.SA, PQDP11.SA, PRIO3.SA, PRSV11.SA, PSSA3.SA, PSVM11.SA, PTNT3.SA, QUAL3.SA, RADL3.SA, RAIL3.SA, RANI3.SA, RAPT4.SA, RBBV11.SA, RBCB11.SA, RBDS11.SA, RBGS11.SA, RBRD11.SA, RBVO11.SA, RCSL4.SA, RDES11.SA, RDNI3.SA, REDE3.SA, RENT3.SA, RLOG3.SA, RNDP11.SA, RNEW11.SA, RNGO11.SA, ROMI3.SA, RPAD3.SA, RPMG3.SA, RSID3.SA, RSUL4.SA, SAAG11.SA, SANB4.SA, SAPR4.SA, SBSP3.SA, SCAR3.SA, SCPF11.SA, SDIL11.SA, SEER3.SA, SFND11.SA, SGPS3.SA, SHOW3.SA, SHPH11.SA, SHUL4.SA, SLCE3.SA, SLED4.SA, SMAL11.SA, SMLS3.SA, SMTO3.SA, SNSY5.SA, SOND5.SA, SPRI3.SA, SPTW11.SA, SPXI11.SA, STBP3.SA, SULA11.SA, SUZB3.SA, TAEE11.SA, TBOF11.SA, TCNO3.SA, TCSA3.SA, TECN3.SA, TEKA4.SA, TELB4.SA, TEND3.SA, TGMA3.SA, TIET11.SA, TIMP3.SA, TKNO4.SA, TOTS3.SA, TPIS3.SA, TRIS3.SA, TRPL4.SA, TUPY3.SA, TXRX3.SA, UCAS3.SA, UGPA3.SA, UNIP6.SA, USIM5.SA, VALE3.SA, VIVR3.SA, VIVT4.SA, VLID3.SA, VSPT3.SA, VULC3.SA, VVAR3.SA, WEGE3.SA, WHRL4.SA, WIZS3.SA, XBOV11.SA, XPCM11.SA, XPOM11.SA, XTED11.SA, ADHM3.SA, ALSO3.SA, APER3.SA, CNTO3.SA, COGN3.SA, EDGA11.SA, ENAT3.SA, EQPA5.SA, FLRP11.SA, FVBI11.SA, HGPO11.SA, HMOC11.SA, JPSA3.SA, JRDM11.SA, KNHY11.SA, LIQO3.SA, LOGG3.SA, NEOE3.SA, NSLU11.SA, NTCO3.SA, PPLA11.SA, RBED11.SA, RBRP11.SA, RBVA11.SA, RDPD11.SA, REIT11.SA, SQIA3.SA, TASA4.SA, TESA3.SA, THRA11.SA, VIVA3.SA, WLMM4.SA, YDUQ3.SA,

**Comment by finnhubio** [comment]
Thanks for the details. We have fixed the issue

**Comment by dolnikov** [comment]
Thanks :)
