### ISSUE TITLE
Currency mismatch for London, Tel Aviv, ...

### ISSUE THREAD

**Issue by ivankohut** [finnhubio/Finnhub-API#89]
For some exchanges (London, Tel Aviv, ...) the currency of some endpoints (_Company Profile_, _Quote_, _Earnings Surprises_) is inconsistent, e.g.
* symbol RMG.L, _Company Profile_ GB**P**, Quote - GB**p**, _Earnings Surprises_ GB**P**
* symbol LUMI.TA, _Company Profile_ IL**a**, Quote - IL**a**, _Earnings Surprises_ IL**S**

It would be nice if all endpoints used the same currency (the one returned by _Company Profile_), otherwise I have to hardcode such exceptions into my application.

**Comment by finnhubio** [comment]
This is the standard way of doing it for all big providers in the market. Price on TA exchange will be in ILA and financials data in ILS. We do not have plan to change it at the moment.

**Comment by ivankohut** [comment]
Thanks for reply to the first problem. However there is a second problem (not clear from my original description, sorry): In case of London the currency in _Company Profile_ is financial data currency, in case of Tel Aviv it is price currency.
