### ISSUE TITLE
Missing RedHat (RHT) info

### ISSUE THREAD

**Issue by coffincw** [finnhubio/Finnhub-API#9]
I am trying to get the quote for RedHat (RHT) with no luck.  I'm using this api call:

https://finnhub.io/api/v1/quote?symbol=RHT&token=api_token

**Comment by coffincw** [comment]
I'm an idiot, RedHat was bought by IBM.  That's on me.

**Comment by finnhubio** [comment]
If you are looking for historical data of delisted stock, we will have that up soon :) No worry. Feel free to open another issue if you have any questions.
