### ISSUE TITLE
No indicators

### ISSUE THREAD

**Issue by Henrolph** [finnhubio/Finnhub-API#96]
Right now there is no way to get the indicators. Only the aggregated one. 
you might want to implement this to the client.py : 
def indicator(self, **params):
        params['from'] = params['_from']
        del params['_from']
        return self._get("indicator", data=params)
you cant give 'from' as a parameter thats why _from and than change it to 'from'.

**Comment by finnhubio** [comment]
You can get that data with this endpoint [https://finnhub.io/docs/api#technical-indicator](https://finnhub.io/docs/api#technical-indicator) . The python library is probably not up to date. We will contact the author.

**Comment by Henrolph** [comment]
Yes exactly, i just wanted to say that its not in the python library.
awesome how fast you guys answer 👍
