### ISSUE TITLE
The data is changed??

### ISSUE THREAD

**Issue by git-farid** [finnhubio/Finnhub-API#98]
Please confirm is someone more has the same problem.

The data that i get now is different than the data that i got some days ago.

Take a look to the docs:

https://drive.google.com/open?id=1J4g6lC4UOD7V6D8VEo5O5x-Jo-EnuS05

Notes:

"aapl_1_tradingview"  is data from tradingview.

"aapl_1_yesterday"  is the data that i downloaded from finnhub 2 days ago(aprox) , the first row was edited from t,o,h,l,c,v   to time , open , high , low , close , volume

You can see that there are not important diferences bettwen both

and then in the most recent file

"finnhub_AAPL.US_1_1585146300_1585699140"

The information is different , like if it would comes from another source.

Do im doing something wrong?? or something is wrong with the data??

**Comment by git-farid** [comment]
Ok , part of the data is fixed but the prices are changed  , only close price is in the same column , open , high and low were sorted in other order.

The documents are in the folder now, take a look  , the new document is "AAPL.US_1_1585146300_1585699140_volume_fixed" 



![updated_volume_fixed](https://user-images.githubusercontent.com/62631387/78413969-8784b700-75df-11ea-9cbc-3d24dbd19a4d.png)

**Comment by finnhubio** [comment]
we just recalculated some of the data from tick. The current version is the final one and won't be changed any further.
